[project]
name = "python"
version = "0.1.0"
description = "Beaconcryt demo"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beaconcrypt>=0.3.11",
    "pynacl>=1.6.2",
]

[tool.uv.sources]
beaconcrypt = { path = "../../target/wheels/beaconcrypt-0.4.0-cp311-abi3-win_amd64.whl" }
