module Beaconcrypt_protocol_core.Pqxdh
#set-options "--fuel 0 --ifuel 1 --z3rlimit 15"
open FStar.Mul
open Core_models

let v_RATCHET_CHAIN_SIZE: usize = Beaconcrypt_protocol_core.Ratchet.v_RATCHET_CHAIN_SIZE

let v_SIGN_TYPE_ED25519: u8 = mk_u8 1

let v_KEM_TYPE_MLKEM768: u8 = mk_u8 3

let v_KEM_TYPE_X25519: u8 = mk_u8 4

/// Key-role markers occupy the high half of the byte domain, while all
/// algorithm/type markers occupy the low half. This makes a type byte
/// impossible to reinterpret as a role byte.
let v_KEY_ROLE_PREKEY: u8 = mk_u8 128

let v_KEY_ROLE_ONE_TIME: u8 = mk_u8 129

let v_PQXDH_INFO: t_Array u8 (mk_usize 46) =
  let list =
    [
      mk_u8 66; mk_u8 101; mk_u8 97; mk_u8 99; mk_u8 111; mk_u8 110; mk_u8 99; mk_u8 114; mk_u8 121;
      mk_u8 112; mk_u8 116; mk_u8 80; mk_u8 113; mk_u8 120; mk_u8 100; mk_u8 104; mk_u8 95; mk_u8 67;
      mk_u8 85; mk_u8 82; mk_u8 86; mk_u8 69; mk_u8 50; mk_u8 53; mk_u8 53; mk_u8 49; mk_u8 57;
      mk_u8 95; mk_u8 83; mk_u8 72; mk_u8 65; mk_u8 45; mk_u8 53; mk_u8 49; mk_u8 50; mk_u8 95;
      mk_u8 77; mk_u8 76; mk_u8 45; mk_u8 75; mk_u8 69; mk_u8 77; mk_u8 45; mk_u8 55; mk_u8 54;
      mk_u8 56
    ]
  in
  FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 46);
  Rust_primitives.Hax.array_of_list 46 list

let v_SYM_RATCHET_INFO: t_Array u8 (mk_usize 41) =
  Beaconcrypt_protocol_core.Ratchet.v_SYM_RATCHET_INFO

type t_RegistrationError =
  | RegistrationError_IdentityMismatch : t_RegistrationError
  | RegistrationError_InvalidKeyEncoding : t_RegistrationError
  | RegistrationError_InvalidDhOutput : t_RegistrationError
  | RegistrationError_RegistrationReplay : t_RegistrationError
  | RegistrationError_KeyIdMismatch : t_RegistrationError
  | RegistrationError_KeyIdExhausted : t_RegistrationError
  | RegistrationError_KeyIdCollision : t_RegistrationError

/// Stable expected or accepting server identity.
/// Keeping the public key and its numeric identifier in one proof-visible
/// value prevents adapters from changing either half of the trust anchor
/// independently during registration.
type t_ServerBinding = {
  f_identity_public_key:t_Array u8 (mk_usize 32);
  f_identity_key_id:u64
}

/// Public material generated by the beacon adapter before registration.
type t_BeaconStartInputs = {
  f_identity_public_key:t_Array u8 (mk_usize 32);
  f_prekey_public_key:t_Array u8 (mk_usize 32);
  f_pq_public_key:t_Array u8 (mk_usize 1184)
}

/// Per-registration randomness generated by the beacon adapter.
type t_BeaconCoins = { f_one_time_public_key:t_Array u8 (mk_usize 32) }

/// The deterministic, unsigned payloads of an InitKex message.
/// The adapter signs `prekey`, `one_time_key`, and `pq_key`, then places the
/// resulting signed buffers and `identity_key` into Cap'n Proto. The X25519
/// payloads are `[type, role, key]`; validation assigns meaning from the
/// authenticated role byte rather than from the wire field position alone.
type t_InitKex = {
  f_identity_key:t_Array u8 (mk_usize 33);
  f_prekey:t_Array u8 (mk_usize 34);
  f_one_time_key:t_Array u8 (mk_usize 34);
  f_pq_key:t_Array u8 (mk_usize 1185)
}

/// Signature-checked and type-checked InitKex public keys.
type t_VerifiedInitKex = {
  f_beacon_identity_public_key:t_Array u8 (mk_usize 32);
  f_beacon_prekey_public_key:t_Array u8 (mk_usize 32);
  f_beacon_one_time_public_key:t_Array u8 (mk_usize 32);
  f_beacon_pq_public_key:t_Array u8 (mk_usize 1184)
}

/// The signed beacon identity and one-time X25519 public key consumed by an
/// accepted `InitKex`.
type t_RegistrationId = { f_bytes:t_Array u8 (mk_usize 64) }

/// Stable, authenticated identifier for this one-time registration.
/// Exact equality is used by the adapter's consumed-registration set; no
/// hash or collision-resistance assumption is needed.
let impl_VerifiedInitKex__registration_id (self: t_VerifiedInitKex) : t_RegistrationId =
  let bytes:t_Array u8 (mk_usize 64) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 64) in
  let bytes:t_Array u8 (mk_usize 64) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_range_to bytes
      ({ Core_models.Ops.Range.f_end = mk_usize 32 } <: Core_models.Ops.Range.t_RangeTo usize)
      (Core_models.Slice.impl__copy_from_slice #u8
          (bytes.[ { Core_models.Ops.Range.f_end = mk_usize 32 }
              <:
              Core_models.Ops.Range.t_RangeTo usize ]
            <:
            t_Slice u8)
          (self.f_beacon_identity_public_key <: t_Slice u8)
        <:
        t_Slice u8)
  in
  let bytes:t_Array u8 (mk_usize 64) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_range_from bytes
      ({ Core_models.Ops.Range.f_start = mk_usize 32 } <: Core_models.Ops.Range.t_RangeFrom usize)
      (Core_models.Slice.impl__copy_from_slice #u8
          (bytes.[ { Core_models.Ops.Range.f_start = mk_usize 32 }
              <:
              Core_models.Ops.Range.t_RangeFrom usize ]
            <:
            t_Slice u8)
          (self.f_beacon_one_time_public_key <: t_Slice u8)
        <:
        t_Slice u8)
  in
  { f_bytes = bytes } <: t_RegistrationId

/// Production abstraction used by the replay adapter and the ProVerif model.
/// The backend replacement below is deliberately limited to the exact
/// identity/one-time-key projection proved by the Stage 6 F* lemmas. It does
/// not replace the Rust implementation on ordinary builds.
let registration_id (registration: t_VerifiedInitKex) : t_RegistrationId =
  impl_VerifiedInitKex__registration_id registration

/// Adapter-supplied result of looking up a registration ID in the persistent
/// consumed-registration set.
type t_RegistrationStatus =
  | RegistrationStatus_Fresh : t_RegistrationStatus
  | RegistrationStatus_Consumed : t_RegistrationStatus

let validate_registration_status (registration_status: t_RegistrationStatus)
    : Core_models.Result.t_Result Prims.unit t_RegistrationError =
  if
    match registration_status <: t_RegistrationStatus with
    | RegistrationStatus_Consumed  -> true
    | _ -> false
  then
    Core_models.Result.Result_Err (RegistrationError_RegistrationReplay <: t_RegistrationError)
    <:
    Core_models.Result.t_Result Prims.unit t_RegistrationError
  else
    Core_models.Result.Result_Ok (() <: Prims.unit)
    <:
    Core_models.Result.t_Result Prims.unit t_RegistrationError

/// Fresh beacon state. Calling [`beacon_start`] consumes this state.
type t_BeaconFresh = { f_expected_server_binding:t_ServerBinding }

/// Beacon state tied to exactly one emitted InitKex.
type t_BeaconInitSent = {
  f_expected_server_binding:t_ServerBinding;
  f_beacon_identity_public_key:t_Array u8 (mk_usize 32)
}

type t_BeaconStart = {
  f_state:t_BeaconInitSent;
  f_message:t_InitKex
}

/// Four classical DH results followed by the post-quantum KEM secret.
type t_PqxdhSharedSecrets = {
  f_dh1:t_Array u8 (mk_usize 32);
  f_dh2:t_Array u8 (mk_usize 32);
  f_dh3:t_Array u8 (mk_usize 32);
  f_dh4:t_Array u8 (mk_usize 32);
  f_kem_shared_secret:t_Array u8 (mk_usize 32)
}

/// Exact `Padding || DH1 || DH2 || DH3 || DH4 || SS` input to the opaque
/// PQXDH HKDF operation.
type t_RootKeyInput = { f_bytes:t_Array u8 (mk_usize 192) }

/// The core-owned direction plan for splitting the opaque 64-byte ratchet
/// KDF result. Offsets are bytes into `LHS || RHS`.
type t_RatchetInitialization = {
  f_send_offset:u8;
  f_receive_offset:u8
}

let v_BEACON_RATCHETS: t_RatchetInitialization =
  { f_send_offset = cast (v_RATCHET_CHAIN_SIZE <: usize) <: u8; f_receive_offset = mk_u8 0 }
  <:
  t_RatchetInitialization

let v_SERVER_RATCHETS: t_RatchetInitialization =
  { f_send_offset = mk_u8 0; f_receive_offset = cast (v_RATCHET_CHAIN_SIZE <: usize) <: u8 }
  <:
  t_RatchetInitialization

/// Test and adapter utility for non-handshake ratchet fixtures. Production
/// PQXDH code obtains the same plan from a beacon candidate typestate.
let beacon_ratchet_initialization (_: Prims.unit) : t_RatchetInitialization = v_BEACON_RATCHETS

/// Test and adapter utility for non-handshake ratchet fixtures. Production
/// PQXDH code obtains the same plan from a server candidate typestate.
let server_ratchet_initialization (_: Prims.unit) : t_RatchetInitialization = v_SERVER_RATCHETS

/// Role-ordered fixed-width initial send and receive chains.
type t_InitialRatchetChains = {
  f_send_chain:Beaconcrypt_protocol_core.Ratchet.t_RatchetChain;
  f_receive_chain:Beaconcrypt_protocol_core.Ratchet.t_RatchetChain
}

let impl_InitialRatchetChains__into_parts (self: t_InitialRatchetChains)
    : (Beaconcrypt_protocol_core.Ratchet.t_RatchetChain &
      Beaconcrypt_protocol_core.Ratchet.t_RatchetChain) =
  self.f_send_chain, self.f_receive_chain
  <:
  (Beaconcrypt_protocol_core.Ratchet.t_RatchetChain &
    Beaconcrypt_protocol_core.Ratchet.t_RatchetChain)

/// Split an opaque 64-byte initial expansion into role-ordered fixed-width chains.
let split_initial_ratchet_kdf_output
      (output: t_Array u8 (mk_usize 64))
      (initialization: t_RatchetInitialization)
    : t_InitialRatchetChains =
  let left:t_Array u8 (mk_usize 32) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 32) in
  let left:t_Array u8 (mk_usize 32) =
    Core_models.Slice.impl__copy_from_slice #u8
      left
      (output.[ {
            Core_models.Ops.Range.f_start = mk_usize 0;
            Core_models.Ops.Range.f_end = mk_usize 32
          }
          <:
          Core_models.Ops.Range.t_Range usize ]
        <:
        t_Slice u8)
  in
  let right:t_Array u8 (mk_usize 32) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 32) in
  let right:t_Array u8 (mk_usize 32) =
    Core_models.Slice.impl__copy_from_slice #u8
      right
      (output.[ {
            Core_models.Ops.Range.f_start = mk_usize 32;
            Core_models.Ops.Range.f_end = mk_usize 64
          }
          <:
          Core_models.Ops.Range.t_Range usize ]
        <:
        t_Slice u8)
  in
  if initialization.f_send_offset =. mk_u8 0
  then
    {
      f_send_chain = Beaconcrypt_protocol_core.Ratchet.impl_RatchetChain__from_bytes left;
      f_receive_chain = Beaconcrypt_protocol_core.Ratchet.impl_RatchetChain__from_bytes right
    }
    <:
    t_InitialRatchetChains
  else
    {
      f_send_chain = Beaconcrypt_protocol_core.Ratchet.impl_RatchetChain__from_bytes right;
      f_receive_chain = Beaconcrypt_protocol_core.Ratchet.impl_RatchetChain__from_bytes left
    }
    <:
    t_InitialRatchetChains

/// Apply the sole opaque initial-chain primitive to the exact session root and order its output.
/// The primitive's complete production-facing type is `32-byte root -> 64-byte output`.
/// Label selection and HKDF details are private to that domain-specific primitive.
/// Input selection, output size, role ordering, partitioning, and fixed-width construction are owned here.
let derive_initial_ratchet_chains
      (root: t_Array u8 (mk_usize 32))
      (initialization: t_RatchetInitialization)
      (kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 64)))
    : t_InitialRatchetChains =
  let request:Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest =
    Beaconcrypt_protocol_core.Ratchet.impl_SymmetricRatchetKdfRequest__new root
  in
  let output:t_Array u8 (mk_usize 64) = kdf request in
  split_initial_ratchet_kdf_output output initialization

/// Construct a concrete kernel directly from one root, one fixed role plan,
/// and the executors for initial and subsequent core-owned KDF requests.
let derive_initial_ratchet_kernel
      (root: t_Array u8 (mk_usize 32))
      (initialization: t_RatchetInitialization)
      (initial_kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 64)))
      (ratchet_kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 76)))
    : Beaconcrypt_protocol_core.Ratchet.t_ConcreteRatchetKernel =
  let chains:t_InitialRatchetChains =
    derive_initial_ratchet_chains root initialization initial_kdf
  in
  let
  (send_chain: Beaconcrypt_protocol_core.Ratchet.t_RatchetChain),
  (receive_chain: Beaconcrypt_protocol_core.Ratchet.t_RatchetChain) =
    impl_InitialRatchetChains__into_parts chains
  in
  Beaconcrypt_protocol_core.Ratchet.impl_ConcreteRatchetKernel__new send_chain
    receive_chain
    ratchet_kdf

/// Construct the beacon role's complementary concrete kernel.
let derive_beacon_ratchet_kernel
      (root: t_Array u8 (mk_usize 32))
      (initial_kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 64)))
      (ratchet_kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 76)))
    : Beaconcrypt_protocol_core.Ratchet.t_ConcreteRatchetKernel =
  derive_initial_ratchet_kernel root v_BEACON_RATCHETS initial_kdf ratchet_kdf

/// Construct the server role's complementary concrete kernel.
let derive_server_ratchet_kernel
      (root: t_Array u8 (mk_usize 32))
      (initial_kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 64)))
      (ratchet_kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 76)))
    : Beaconcrypt_protocol_core.Ratchet.t_ConcreteRatchetKernel =
  derive_initial_ratchet_kernel root v_SERVER_RATCHETS initial_kdf ratchet_kdf

/// Candidate beacon session. Its root, AD, identity assignment, and ratchet
/// direction have been validated, but its initial ciphertext has not yet
/// authenticated. It must be consumed by [`beacon_commit`] or
/// [`beacon_abort_candidate`].
type t_BeaconRegistrationCandidate = {
  f_server_binding:t_ServerBinding;
  f_assigned_key_id:u64;
  f_root_key_input:t_RootKeyInput;
  f_associated_data:t_Array u8 (mk_usize 153)
}

let impl_BeaconRegistrationCandidate__ratchet_initialization (self: t_BeaconRegistrationCandidate)
    : t_RatchetInitialization = v_BEACON_RATCHETS

/// Bind the authenticated candidate's beacon direction directly to a
/// concrete core ratchet kernel.
let impl_BeaconRegistrationCandidate__derive_ratchet_kernel
      (self: t_BeaconRegistrationCandidate)
      (root: t_Array u8 (mk_usize 32))
      (initial_kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 64)))
      (ratchet_kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 76)))
    : Beaconcrypt_protocol_core.Ratchet.t_ConcreteRatchetKernel =
  derive_beacon_ratchet_kernel root initial_kdf ratchet_kdf

type t_BeaconFinishInputs = {
  f_response_server_identity:t_Array u8 (mk_usize 32);
  f_assigned_key_id:u64;
  f_shared_secrets:t_PqxdhSharedSecrets
}

/// Fixed-width authenticated binding carried inside the encrypted initial
/// registration payload. The adapter strips it before returning application
/// plaintext.
type t_RegistrationKeyIdBinding = { f_bytes:t_Array u8 (mk_usize 8) }

let registration_key_id_binding (key_id: u64) : t_RegistrationKeyIdBinding =
  {
    f_bytes
    =
    let list =
      [
        cast (key_id <: u64) <: u8;
        cast (key_id >>! mk_i32 8 <: u64) <: u8;
        cast (key_id >>! mk_i32 16 <: u64) <: u8;
        cast (key_id >>! mk_i32 24 <: u64) <: u8;
        cast (key_id >>! mk_i32 32 <: u64) <: u8;
        cast (key_id >>! mk_i32 40 <: u64) <: u8;
        cast (key_id >>! mk_i32 48 <: u64) <: u8;
        cast (key_id >>! mk_i32 56 <: u64) <: u8
      ]
    in
    FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 8);
    Rust_primitives.Hax.array_of_list 8 list
  }
  <:
  t_RegistrationKeyIdBinding

let impl_BeaconRegistrationCandidate__key_id_binding (self: t_BeaconRegistrationCandidate)
    : t_RegistrationKeyIdBinding = registration_key_id_binding self.f_assigned_key_id

/// A beacon candidate whose assigned key ID matches the authenticated prefix
/// carried inside `appCipherText`.
type t_AuthenticatedBeaconRegistration = { f_candidate:t_BeaconRegistrationCandidate }

/// Check the authenticated sender ID and the assigned key-ID prefix returned
/// by the initial response open. Only the resulting typestate can be committed.
let authenticate_registration_key_id_binding
      (candidate: t_BeaconRegistrationCandidate)
      (authenticated_server_key_id: u64)
      (authenticated_binding: t_Array u8 (mk_usize 8))
    : Core_models.Result.t_Result t_AuthenticatedBeaconRegistration t_RegistrationError =
  if authenticated_server_key_id <>. candidate.f_server_binding.f_identity_key_id
  then
    Core_models.Result.Result_Err (RegistrationError_IdentityMismatch <: t_RegistrationError)
    <:
    Core_models.Result.t_Result t_AuthenticatedBeaconRegistration t_RegistrationError
  else
    if
      authenticated_binding <>.
      (impl_BeaconRegistrationCandidate__key_id_binding candidate <: t_RegistrationKeyIdBinding)
        .f_bytes
    then
      Core_models.Result.Result_Err (RegistrationError_KeyIdMismatch <: t_RegistrationError)
      <:
      Core_models.Result.t_Result t_AuthenticatedBeaconRegistration t_RegistrationError
    else
      Core_models.Result.Result_Ok
      ({ f_candidate = candidate } <: t_AuthenticatedBeaconRegistration)
      <:
      Core_models.Result.t_Result t_AuthenticatedBeaconRegistration t_RegistrationError

type t_BeaconEstablished = {
  f_server_binding:t_ServerBinding;
  f_assigned_key_id:u64
}

type t_BeaconAborted = { f_server_key_id:u64 }

let beacon_commit (authenticated: t_AuthenticatedBeaconRegistration) : t_BeaconEstablished =
  let candidate:t_BeaconRegistrationCandidate = authenticated.f_candidate in
  { f_server_binding = candidate.f_server_binding; f_assigned_key_id = candidate.f_assigned_key_id }
  <:
  t_BeaconEstablished

let beacon_abort_candidate (candidate: t_BeaconRegistrationCandidate) : t_BeaconAborted =
  { f_server_key_id = candidate.f_server_binding.f_identity_key_id } <: t_BeaconAborted

let beacon_abort_init (state: t_BeaconInitSent) : t_BeaconAborted =
  { f_server_key_id = state.f_expected_server_binding.f_identity_key_id } <: t_BeaconAborted

let beacon_abort_fresh (state: t_BeaconFresh) : t_BeaconAborted =
  { f_server_key_id = state.f_expected_server_binding.f_identity_key_id } <: t_BeaconAborted

/// Active server state. Pending registrations do not mutate it.
type t_ServerState = { f_last_key_id:u64 }

/// Explicit ephemeral/KEM outputs generated by the server adapter.
type t_ServerCoins = {
  f_ephemeral_public_key:t_Array u8 (mk_usize 32);
  f_kem_ciphertext:t_Array u8 (mk_usize 1088)
}

/// Registration material that has passed parsing, signatures, key tags, DH
/// validation, and transcript construction but has not changed server state.
type t_PendingServerRegistration = {
  f_server_binding:t_ServerBinding;
  f_registration_id:t_RegistrationId;
  f_beacon_identity_public_key:t_Array u8 (mk_usize 32);
  f_ephemeral_public_key:t_Array u8 (mk_usize 32);
  f_kem_ciphertext:t_Array u8 (mk_usize 1088);
  f_root_key_input:t_RootKeyInput
}

/// Candidate server commit. The adapter must initialize a fresh ratchet,
/// encrypt the initial message, and serialize the response before consuming it
/// with [`server_commit`]. Dropping it leaves the active server unchanged.
type t_ServerRegistrationCandidate = {
  f_previous_state:t_ServerState;
  f_next_state:t_ServerState;
  f_key_id:u64;
  f_beacon_identity_public_key:t_Array u8 (mk_usize 32);
  f_server_identity_public_key:t_Array u8 (mk_usize 32);
  f_server_identity_key_id:u64;
  f_ephemeral_public_key:t_Array u8 (mk_usize 32);
  f_kem_ciphertext:t_Array u8 (mk_usize 1088);
  f_associated_data:t_Array u8 (mk_usize 153)
}

let impl_ServerRegistrationCandidate__ratchet_initialization (self: t_ServerRegistrationCandidate)
    : t_RatchetInitialization = v_SERVER_RATCHETS

let impl_ServerRegistrationCandidate__key_id_binding (self: t_ServerRegistrationCandidate)
    : t_RegistrationKeyIdBinding = registration_key_id_binding self.f_key_id

/// Bind the accepted server candidate's direction directly to a concrete
/// core ratchet kernel.
let impl_ServerRegistrationCandidate__derive_ratchet_kernel
      (self: t_ServerRegistrationCandidate)
      (root: t_Array u8 (mk_usize 32))
      (initial_kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 64)))
      (ratchet_kdf:
          (Beaconcrypt_protocol_core.Ratchet.t_SymmetricRatchetKdfRequest
              -> t_Array u8 (mk_usize 76)))
    : Beaconcrypt_protocol_core.Ratchet.t_ConcreteRatchetKernel =
  derive_server_ratchet_kernel root initial_kdf ratchet_kdf

type t_KeyIdAvailability =
  | KeyIdAvailability_Available : t_KeyIdAvailability
  | KeyIdAvailability_Occupied : t_KeyIdAvailability

/// Return the next key ID without wrapping an exhausted counter.
let server_next_key_id (state: t_ServerState) : Core_models.Result.t_Result u64 t_RegistrationError =
  if state.f_last_key_id =. Core_models.Num.impl_u64__MAX
  then
    Core_models.Result.Result_Err (RegistrationError_KeyIdExhausted <: t_RegistrationError)
    <:
    Core_models.Result.t_Result u64 t_RegistrationError
  else
    Core_models.Result.Result_Ok (state.f_last_key_id +! mk_u64 1)
    <:
    Core_models.Result.t_Result u64 t_RegistrationError

type t_EstablishedPeer = {
  f_key_id:u64;
  f_identity_public_key:t_Array u8 (mk_usize 32);
  f_associated_data:t_Array u8 (mk_usize 153)
}

let server_commit (candidate: t_ServerRegistrationCandidate) : (t_ServerState & t_EstablishedPeer) =
  candidate.f_next_state,
  ({
      f_key_id = candidate.f_key_id;
      f_identity_public_key = candidate.f_beacon_identity_public_key;
      f_associated_data = candidate.f_associated_data
    }
    <:
    t_EstablishedPeer)
  <:
  (t_ServerState & t_EstablishedPeer)

let server_abort_candidate (candidate: t_ServerRegistrationCandidate) : t_ServerState =
  candidate.f_previous_state

let tag_sign_key (key: t_Array u8 (mk_usize 32)) : t_Array u8 (mk_usize 33) =
  let output:t_Array u8 (mk_usize 33) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 33) in
  let output:t_Array u8 (mk_usize 33) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
      (mk_usize 0)
      v_SIGN_TYPE_ED25519
  in
  let output:t_Array u8 (mk_usize 33) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_range output
      ({ Core_models.Ops.Range.f_start = mk_usize 1; Core_models.Ops.Range.f_end = mk_usize 33 }
        <:
        Core_models.Ops.Range.t_Range usize)
      (Core_models.Slice.impl__copy_from_slice #u8
          (output.[ {
                Core_models.Ops.Range.f_start = mk_usize 1;
                Core_models.Ops.Range.f_end = mk_usize 33
              }
              <:
              Core_models.Ops.Range.t_Range usize ]
            <:
            t_Slice u8)
          (key <: t_Slice u8)
        <:
        t_Slice u8)
  in
  output

/// Associated data is always encoded server identity first, beacon identity
/// second, then the key-exchange and ratchet domain-separation strings.
let build_associated_data
      (server_identity_public_key beacon_identity_public_key: t_Array u8 (mk_usize 32))
    : t_Array u8 (mk_usize 153) =
  let encoded_server:t_Array u8 (mk_usize 33) = tag_sign_key server_identity_public_key in
  let encoded_beacon:t_Array u8 (mk_usize 33) = tag_sign_key beacon_identity_public_key in
  let output:t_Array u8 (mk_usize 153) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 153) in
  let output:t_Array u8 (mk_usize 153) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_range_to output
      ({ Core_models.Ops.Range.f_end = mk_usize 33 } <: Core_models.Ops.Range.t_RangeTo usize)
      (Core_models.Slice.impl__copy_from_slice #u8
          (output.[ { Core_models.Ops.Range.f_end = mk_usize 33 }
              <:
              Core_models.Ops.Range.t_RangeTo usize ]
            <:
            t_Slice u8)
          (encoded_server <: t_Slice u8)
        <:
        t_Slice u8)
  in
  let output:t_Array u8 (mk_usize 153) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_range output
      ({ Core_models.Ops.Range.f_start = mk_usize 33; Core_models.Ops.Range.f_end = mk_usize 66 }
        <:
        Core_models.Ops.Range.t_Range usize)
      (Core_models.Slice.impl__copy_from_slice #u8
          (output.[ {
                Core_models.Ops.Range.f_start = mk_usize 33;
                Core_models.Ops.Range.f_end = mk_usize 66
              }
              <:
              Core_models.Ops.Range.t_Range usize ]
            <:
            t_Slice u8)
          (encoded_beacon <: t_Slice u8)
        <:
        t_Slice u8)
  in
  let output:t_Array u8 (mk_usize 153) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_range output
      ({ Core_models.Ops.Range.f_start = mk_usize 66; Core_models.Ops.Range.f_end = mk_usize 112 }
        <:
        Core_models.Ops.Range.t_Range usize)
      (Core_models.Slice.impl__copy_from_slice #u8
          (output.[ {
                Core_models.Ops.Range.f_start = mk_usize 66;
                Core_models.Ops.Range.f_end = mk_usize 112
              }
              <:
              Core_models.Ops.Range.t_Range usize ]
            <:
            t_Slice u8)
          (v_PQXDH_INFO <: t_Slice u8)
        <:
        t_Slice u8)
  in
  let output:t_Array u8 (mk_usize 153) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_range_from output
      ({ Core_models.Ops.Range.f_start = mk_usize 112 } <: Core_models.Ops.Range.t_RangeFrom usize)
      (Core_models.Slice.impl__copy_from_slice #u8
          (output.[ { Core_models.Ops.Range.f_start = mk_usize 112 }
              <:
              Core_models.Ops.Range.t_RangeFrom usize ]
            <:
            t_Slice u8)
          (v_SYM_RATCHET_INFO <: t_Slice u8)
        <:
        t_Slice u8)
  in
  output

/// Prepare the next checked, explicitly unoccupied server key ID.
let server_prepare_commit
      (state: t_ServerState)
      (pending: t_PendingServerRegistration)
      (current_server_binding: t_ServerBinding)
      (key_id_availability: t_KeyIdAvailability)
    : Core_models.Result.t_Result t_ServerRegistrationCandidate t_RegistrationError =
  if
    pending.f_server_binding.f_identity_key_id <>. current_server_binding.f_identity_key_id ||
    pending.f_server_binding.f_identity_public_key <>. current_server_binding.f_identity_public_key
  then
    Core_models.Result.Result_Err (RegistrationError_IdentityMismatch <: t_RegistrationError)
    <:
    Core_models.Result.t_Result t_ServerRegistrationCandidate t_RegistrationError
  else
    match server_next_key_id state <: Core_models.Result.t_Result u64 t_RegistrationError with
    | Core_models.Result.Result_Ok key_id ->
      if
        match key_id_availability <: t_KeyIdAvailability with
        | KeyIdAvailability_Occupied  -> true
        | _ -> false
      then
        Core_models.Result.Result_Err (RegistrationError_KeyIdCollision <: t_RegistrationError)
        <:
        Core_models.Result.t_Result t_ServerRegistrationCandidate t_RegistrationError
      else
        Core_models.Result.Result_Ok
        ({
            f_previous_state = state;
            f_next_state = { f_last_key_id = key_id } <: t_ServerState;
            f_key_id = key_id;
            f_beacon_identity_public_key = pending.f_beacon_identity_public_key;
            f_server_identity_public_key = current_server_binding.f_identity_public_key;
            f_server_identity_key_id = current_server_binding.f_identity_key_id;
            f_ephemeral_public_key = pending.f_ephemeral_public_key;
            f_kem_ciphertext = pending.f_kem_ciphertext;
            f_associated_data
            =
            build_associated_data current_server_binding.f_identity_public_key
              pending.f_beacon_identity_public_key
          }
          <:
          t_ServerRegistrationCandidate)
        <:
        Core_models.Result.t_Result t_ServerRegistrationCandidate t_RegistrationError
    | Core_models.Result.Result_Err err ->
      Core_models.Result.Result_Err err
      <:
      Core_models.Result.t_Result t_ServerRegistrationCandidate t_RegistrationError

let tag_x25519_key (role: u8) (key: t_Array u8 (mk_usize 32)) : t_Array u8 (mk_usize 34) =
  let output:t_Array u8 (mk_usize 34) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 34) in
  let output:t_Array u8 (mk_usize 34) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
      (mk_usize 0)
      v_KEM_TYPE_X25519
  in
  let output:t_Array u8 (mk_usize 34) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output (mk_usize 1) role
  in
  let output:t_Array u8 (mk_usize 34) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_range output
      ({ Core_models.Ops.Range.f_start = mk_usize 2; Core_models.Ops.Range.f_end = mk_usize 34 }
        <:
        Core_models.Ops.Range.t_Range usize)
      (Core_models.Slice.impl__copy_from_slice #u8
          (output.[ {
                Core_models.Ops.Range.f_start = mk_usize 2;
                Core_models.Ops.Range.f_end = mk_usize 34
              }
              <:
              Core_models.Ops.Range.t_Range usize ]
            <:
            t_Slice u8)
          (key <: t_Slice u8)
        <:
        t_Slice u8)
  in
  output

let tag_mlkem768_key (key: t_Array u8 (mk_usize 1184)) : t_Array u8 (mk_usize 1185) =
  let output:t_Array u8 (mk_usize 1185) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 1185) in
  let output:t_Array u8 (mk_usize 1185) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
      (mk_usize 0)
      v_KEM_TYPE_MLKEM768
  in
  let output:t_Array u8 (mk_usize 1185) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_range output
      ({ Core_models.Ops.Range.f_start = mk_usize 1; Core_models.Ops.Range.f_end = mk_usize 1185 }
        <:
        Core_models.Ops.Range.t_Range usize)
      (Core_models.Slice.impl__copy_from_slice #u8
          (output.[ {
                Core_models.Ops.Range.f_start = mk_usize 1;
                Core_models.Ops.Range.f_end = mk_usize 1185
              }
              <:
              Core_models.Ops.Range.t_Range usize ]
            <:
            t_Slice u8)
          (key <: t_Slice u8)
        <:
        t_Slice u8)
  in
  output

/// Construct the exact tagged InitKex payloads from explicit generated
/// material and advance the beacon to its single pending registration.
let beacon_start (state: t_BeaconFresh) (inputs: t_BeaconStartInputs) (coins: t_BeaconCoins)
    : t_BeaconStart =
  {
    f_state
    =
    {
      f_expected_server_binding = state.f_expected_server_binding;
      f_beacon_identity_public_key = inputs.f_identity_public_key
    }
    <:
    t_BeaconInitSent;
    f_message
    =
    {
      f_identity_key = tag_sign_key inputs.f_identity_public_key;
      f_prekey = tag_x25519_key v_KEY_ROLE_PREKEY inputs.f_prekey_public_key;
      f_one_time_key = tag_x25519_key v_KEY_ROLE_ONE_TIME coins.f_one_time_public_key;
      f_pq_key = tag_mlkem768_key inputs.f_pq_public_key
    }
    <:
    t_InitKex
  }
  <:
  t_BeaconStart

let untag_sign_key (encoded: t_Array u8 (mk_usize 33))
    : Core_models.Option.t_Option (t_Array u8 (mk_usize 32)) =
  if (encoded.[ mk_usize 0 ] <: u8) <>. v_SIGN_TYPE_ED25519
  then Core_models.Option.Option_None <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))
  else
    let key:t_Array u8 (mk_usize 32) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 32) in
    let key:t_Array u8 (mk_usize 32) =
      Core_models.Slice.impl__copy_from_slice #u8
        key
        (encoded.[ {
              Core_models.Ops.Range.f_start = mk_usize 1;
              Core_models.Ops.Range.f_end = mk_usize 33
            }
            <:
            Core_models.Ops.Range.t_Range usize ]
          <:
          t_Slice u8)
    in
    Core_models.Option.Option_Some key <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))

let untag_x25519_key (encoded: t_Array u8 (mk_usize 34)) (expected_role: u8)
    : Core_models.Option.t_Option (t_Array u8 (mk_usize 32)) =
  if
    (encoded.[ mk_usize 0 ] <: u8) <>. v_KEM_TYPE_X25519 ||
    (encoded.[ mk_usize 1 ] <: u8) <>. expected_role
  then Core_models.Option.Option_None <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))
  else
    let key:t_Array u8 (mk_usize 32) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 32) in
    let key:t_Array u8 (mk_usize 32) =
      Core_models.Slice.impl__copy_from_slice #u8
        key
        (encoded.[ {
              Core_models.Ops.Range.f_start = mk_usize 2;
              Core_models.Ops.Range.f_end = mk_usize 34
            }
            <:
            Core_models.Ops.Range.t_Range usize ]
          <:
          t_Slice u8)
    in
    Core_models.Option.Option_Some key <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))

let untag_mlkem768_key (encoded: t_Array u8 (mk_usize 1185))
    : Core_models.Option.t_Option (t_Array u8 (mk_usize 1184)) =
  if (encoded.[ mk_usize 0 ] <: u8) <>. v_KEM_TYPE_MLKEM768
  then Core_models.Option.Option_None <: Core_models.Option.t_Option (t_Array u8 (mk_usize 1184))
  else
    let key:t_Array u8 (mk_usize 1184) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 1184) in
    let key:t_Array u8 (mk_usize 1184) =
      Core_models.Slice.impl__copy_from_slice #u8
        key
        (encoded.[ {
              Core_models.Ops.Range.f_start = mk_usize 1;
              Core_models.Ops.Range.f_end = mk_usize 1185
            }
            <:
            Core_models.Ops.Range.t_Range usize ]
          <:
          t_Slice u8)
    in
    Core_models.Option.Option_Some key <: Core_models.Option.t_Option (t_Array u8 (mk_usize 1184))

/// Re-establish typed, verified registration keys after signature checks in
/// the adapter. Incorrect type tags or X25519 field roles are rejected here.
let validate_init_kex (message: t_InitKex)
    : Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError =
  match
    untag_sign_key message.f_identity_key <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))
  with
  | Core_models.Option.Option_Some identity ->
    (match
        untag_x25519_key message.f_prekey v_KEY_ROLE_PREKEY
        <:
        Core_models.Option.t_Option (t_Array u8 (mk_usize 32))
      with
      | Core_models.Option.Option_Some prekey ->
        (match
            untag_x25519_key message.f_one_time_key v_KEY_ROLE_ONE_TIME
            <:
            Core_models.Option.t_Option (t_Array u8 (mk_usize 32))
          with
          | Core_models.Option.Option_Some one_time ->
            (match
                untag_mlkem768_key message.f_pq_key
                <:
                Core_models.Option.t_Option (t_Array u8 (mk_usize 1184))
              with
              | Core_models.Option.Option_Some pq ->
                Core_models.Result.Result_Ok
                ({
                    f_beacon_identity_public_key = identity;
                    f_beacon_prekey_public_key = prekey;
                    f_beacon_one_time_public_key = one_time;
                    f_beacon_pq_public_key = pq
                  }
                  <:
                  t_VerifiedInitKex)
                <:
                Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError
              | _ ->
                Core_models.Result.Result_Err
                (RegistrationError_InvalidKeyEncoding <: t_RegistrationError)
                <:
                Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError)
          | _ ->
            Core_models.Result.Result_Err
            (RegistrationError_InvalidKeyEncoding <: t_RegistrationError)
            <:
            Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError)
      | _ ->
        Core_models.Result.Result_Err (RegistrationError_InvalidKeyEncoding <: t_RegistrationError)
        <:
        Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError)
  | _ ->
    Core_models.Result.Result_Err (RegistrationError_InvalidKeyEncoding <: t_RegistrationError)
    <:
    Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError

let is_all_zero (bytes: t_Array u8 (mk_usize 32)) : bool =
  bytes =. (Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 32) <: t_Array u8 (mk_usize 32))

let build_root_key_input (secrets: t_PqxdhSharedSecrets)
    : Core_models.Result.t_Result t_RootKeyInput t_RegistrationError =
  if
    is_all_zero secrets.f_dh1 || is_all_zero secrets.f_dh2 || is_all_zero secrets.f_dh3 ||
    is_all_zero secrets.f_dh4
  then
    Core_models.Result.Result_Err (RegistrationError_InvalidDhOutput <: t_RegistrationError)
    <:
    Core_models.Result.t_Result t_RootKeyInput t_RegistrationError
  else
    let bytes:t_Array u8 (mk_usize 192) = Rust_primitives.Hax.repeat (mk_u8 255) (mk_usize 192) in
    let bytes:t_Array u8 (mk_usize 192) =
      Rust_primitives.Hax.Monomorphized_update_at.update_at_range bytes
        ({ Core_models.Ops.Range.f_start = mk_usize 32; Core_models.Ops.Range.f_end = mk_usize 64 }
          <:
          Core_models.Ops.Range.t_Range usize)
        (Core_models.Slice.impl__copy_from_slice #u8
            (bytes.[ {
                  Core_models.Ops.Range.f_start = mk_usize 32;
                  Core_models.Ops.Range.f_end = mk_usize 64
                }
                <:
                Core_models.Ops.Range.t_Range usize ]
              <:
              t_Slice u8)
            (secrets.f_dh1 <: t_Slice u8)
          <:
          t_Slice u8)
    in
    let bytes:t_Array u8 (mk_usize 192) =
      Rust_primitives.Hax.Monomorphized_update_at.update_at_range bytes
        ({ Core_models.Ops.Range.f_start = mk_usize 64; Core_models.Ops.Range.f_end = mk_usize 96 }
          <:
          Core_models.Ops.Range.t_Range usize)
        (Core_models.Slice.impl__copy_from_slice #u8
            (bytes.[ {
                  Core_models.Ops.Range.f_start = mk_usize 64;
                  Core_models.Ops.Range.f_end = mk_usize 96
                }
                <:
                Core_models.Ops.Range.t_Range usize ]
              <:
              t_Slice u8)
            (secrets.f_dh2 <: t_Slice u8)
          <:
          t_Slice u8)
    in
    let bytes:t_Array u8 (mk_usize 192) =
      Rust_primitives.Hax.Monomorphized_update_at.update_at_range bytes
        ({ Core_models.Ops.Range.f_start = mk_usize 96; Core_models.Ops.Range.f_end = mk_usize 128 }
          <:
          Core_models.Ops.Range.t_Range usize)
        (Core_models.Slice.impl__copy_from_slice #u8
            (bytes.[ {
                  Core_models.Ops.Range.f_start = mk_usize 96;
                  Core_models.Ops.Range.f_end = mk_usize 128
                }
                <:
                Core_models.Ops.Range.t_Range usize ]
              <:
              t_Slice u8)
            (secrets.f_dh3 <: t_Slice u8)
          <:
          t_Slice u8)
    in
    let bytes:t_Array u8 (mk_usize 192) =
      Rust_primitives.Hax.Monomorphized_update_at.update_at_range bytes
        ({
            Core_models.Ops.Range.f_start = mk_usize 128;
            Core_models.Ops.Range.f_end = mk_usize 160
          }
          <:
          Core_models.Ops.Range.t_Range usize)
        (Core_models.Slice.impl__copy_from_slice #u8
            (bytes.[ {
                  Core_models.Ops.Range.f_start = mk_usize 128;
                  Core_models.Ops.Range.f_end = mk_usize 160
                }
                <:
                Core_models.Ops.Range.t_Range usize ]
              <:
              t_Slice u8)
            (secrets.f_dh4 <: t_Slice u8)
          <:
          t_Slice u8)
    in
    let bytes:t_Array u8 (mk_usize 192) =
      Rust_primitives.Hax.Monomorphized_update_at.update_at_range bytes
        ({
            Core_models.Ops.Range.f_start = mk_usize 160;
            Core_models.Ops.Range.f_end = mk_usize 192
          }
          <:
          Core_models.Ops.Range.t_Range usize)
        (Core_models.Slice.impl__copy_from_slice #u8
            (bytes.[ {
                  Core_models.Ops.Range.f_start = mk_usize 160;
                  Core_models.Ops.Range.f_end = mk_usize 192
                }
                <:
                Core_models.Ops.Range.t_Range usize ]
              <:
              t_Slice u8)
            (secrets.f_kem_shared_secret <: t_Slice u8)
          <:
          t_Slice u8)
    in
    Core_models.Result.Result_Ok ({ f_bytes = bytes } <: t_RootKeyInput)
    <:
    Core_models.Result.t_Result t_RootKeyInput t_RegistrationError

let beacon_prepare_finish (state: t_BeaconInitSent) (inputs: t_BeaconFinishInputs)
    : Core_models.Result.t_Result t_BeaconRegistrationCandidate t_RegistrationError =
  if state.f_expected_server_binding.f_identity_public_key <>. inputs.f_response_server_identity
  then
    Core_models.Result.Result_Err (RegistrationError_IdentityMismatch <: t_RegistrationError)
    <:
    Core_models.Result.t_Result t_BeaconRegistrationCandidate t_RegistrationError
  else
    match
      build_root_key_input inputs.f_shared_secrets
      <:
      Core_models.Result.t_Result t_RootKeyInput t_RegistrationError
    with
    | Core_models.Result.Result_Ok root_key_input ->
      let associated_data:t_Array u8 (mk_usize 153) =
        build_associated_data state.f_expected_server_binding.f_identity_public_key
          state.f_beacon_identity_public_key
      in
      Core_models.Result.Result_Ok
      ({
          f_server_binding = state.f_expected_server_binding;
          f_assigned_key_id = inputs.f_assigned_key_id;
          f_root_key_input = root_key_input;
          f_associated_data = associated_data
        }
        <:
        t_BeaconRegistrationCandidate)
      <:
      Core_models.Result.t_Result t_BeaconRegistrationCandidate t_RegistrationError
    | Core_models.Result.Result_Err err ->
      Core_models.Result.Result_Err err
      <:
      Core_models.Result.t_Result t_BeaconRegistrationCandidate t_RegistrationError

/// Accept a verified InitKex without committing any peer or counter state.
let server_accept
      (state: t_ServerState)
      (registration: t_VerifiedInitKex)
      (registration_status: t_RegistrationStatus)
      (server_binding: t_ServerBinding)
      (coins: t_ServerCoins)
      (shared_secrets: t_PqxdhSharedSecrets)
    : Core_models.Result.t_Result (t_ServerState & t_PendingServerRegistration) t_RegistrationError =
  match
    validate_registration_status registration_status
    <:
    Core_models.Result.t_Result Prims.unit t_RegistrationError
  with
  | Core_models.Result.Result_Ok _ ->
    (match
        build_root_key_input shared_secrets
        <:
        Core_models.Result.t_Result t_RootKeyInput t_RegistrationError
      with
      | Core_models.Result.Result_Ok root_key_input ->
        Core_models.Result.Result_Ok
        (state,
          ({
              f_server_binding = server_binding;
              f_registration_id = registration_id registration;
              f_beacon_identity_public_key = registration.f_beacon_identity_public_key;
              f_ephemeral_public_key = coins.f_ephemeral_public_key;
              f_kem_ciphertext = coins.f_kem_ciphertext;
              f_root_key_input = root_key_input
            }
            <:
            t_PendingServerRegistration)
          <:
          (t_ServerState & t_PendingServerRegistration))
        <:
        Core_models.Result.t_Result (t_ServerState & t_PendingServerRegistration)
          t_RegistrationError
      | Core_models.Result.Result_Err err ->
        Core_models.Result.Result_Err err
        <:
        Core_models.Result.t_Result (t_ServerState & t_PendingServerRegistration)
          t_RegistrationError)
  | Core_models.Result.Result_Err err ->
    Core_models.Result.Result_Err err
    <:
    Core_models.Result.t_Result (t_ServerState & t_PendingServerRegistration) t_RegistrationError
