module Beaconcrypt_protocol_core.Pqxdh
#set-options "--fuel 0 --ifuel 1 --z3rlimit 15"
open FStar.Mul
open Core_models

let v_SIGN_PUBLIC_KEY_SIZE: usize = mk_usize 32

let v_MLKEM768_PUBLIC_KEY_SIZE: usize = mk_usize 1184

let v_SHARED_SECRET_SIZE: usize = mk_usize 32

let v_DH_SECRET_SIZE: usize = mk_usize 32

let v_PQXDH_PADDING_SIZE: usize = mk_usize 32

let v_RATCHET_CHAIN_SIZE: usize = mk_usize 32

let v_SIGN_TYPE_ED25519: u8 = mk_u8 1

let v_KEM_TYPE_MLKEM768: u8 = mk_u8 3

let v_KEM_TYPE_X25519: u8 = mk_u8 4

let v_ENCODED_SIGN_PUBLIC_KEY_SIZE: usize = v_SIGN_PUBLIC_KEY_SIZE +! mk_usize 1

let v_PQXDH_INFO: t_Array u8 (mk_usize 46) =
  let list =
    [
      mk_u8 66; mk_u8 101; mk_u8 97; mk_u8 99; mk_u8 111; mk_u8 110; mk_u8 99; mk_u8 114; mk_u8 121;
      mk_u8 112; mk_u8 116; mk_u8 80; mk_u8 113; mk_u8 120; mk_u8 100; mk_u8 104; mk_u8 95; mk_u8 67;
      mk_u8 85; mk_u8 82; mk_u8 86; mk_u8 69; mk_u8 50; mk_u8 53; mk_u8 53; mk_u8 49; mk_u8 57;
      mk_u8 95; mk_u8 83; mk_u8 72; mk_u8 65; mk_u8 45; mk_u8 53; mk_u8 49; mk_u8 50; mk_u8 95;
      mk_u8 77; mk_u8 76; mk_u8 45; mk_u8 75; mk_u8 69; mk_u8 77; mk_u8 45; mk_u8 55; mk_u8 54;
      mk_u8 56
    ]
  in
  FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 46);
  Rust_primitives.Hax.array_of_list 46 list

let v_SYM_RATCHET_INFO: t_Array u8 (mk_usize 41) =
  let list =
    [
      mk_u8 83; mk_u8 121; mk_u8 109; mk_u8 82; mk_u8 97; mk_u8 116; mk_u8 99; mk_u8 104; mk_u8 101;
      mk_u8 116; mk_u8 95; mk_u8 72; mk_u8 75; mk_u8 68; mk_u8 70; mk_u8 95; mk_u8 83; mk_u8 72;
      mk_u8 65; mk_u8 45; mk_u8 53; mk_u8 49; mk_u8 50; mk_u8 95; mk_u8 67; mk_u8 72; mk_u8 65;
      mk_u8 67; mk_u8 72; mk_u8 65; mk_u8 50; mk_u8 48; mk_u8 95; mk_u8 80; mk_u8 79; mk_u8 76;
      mk_u8 89; mk_u8 49; mk_u8 51; mk_u8 48; mk_u8 53
    ]
  in
  FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 41);
  Rust_primitives.Hax.array_of_list 41 list

let v_ROOT_KEY_INPUT_SIZE: usize =
  (v_PQXDH_PADDING_SIZE +! (mk_usize 4 *! v_DH_SECRET_SIZE <: usize) <: usize) +!
  v_SHARED_SECRET_SIZE

let v_ASSOCIATED_DATA_SIZE: usize =
  ((mk_usize 2 *! v_ENCODED_SIGN_PUBLIC_KEY_SIZE <: usize) +!
    (Core_models.Slice.impl__len #u8 (v_PQXDH_INFO <: t_Slice u8) <: usize)
    <:
    usize) +!
  (Core_models.Slice.impl__len #u8 (v_SYM_RATCHET_INFO <: t_Slice u8) <: usize)

type t_RegistrationError =
  | RegistrationError_IdentityMismatch : t_RegistrationError
  | RegistrationError_InvalidKeyEncoding : t_RegistrationError
  | RegistrationError_InvalidDhOutput : t_RegistrationError

/// Public material generated by the beacon adapter before registration.
type t_BeaconStartInputs = {
  f_identity_public_key:t_Array u8 (mk_usize 32);
  f_prekey_public_key:t_Array u8 (mk_usize 32);
  f_pq_public_key:t_Array u8 (mk_usize 1184)
}

/// Per-registration randomness generated by the beacon adapter.
type t_BeaconCoins = { f_one_time_public_key:t_Array u8 (mk_usize 32) }

/// The deterministic, unsigned payloads of an InitKex message.
/// The adapter signs `prekey`, `one_time_key`, and `pq_key`, then places the
/// resulting signed buffers and `identity_key` into Cap'n Proto.
type t_InitKex = {
  f_identity_key:t_Array u8 (mk_usize 33);
  f_prekey:t_Array u8 (mk_usize 33);
  f_one_time_key:t_Array u8 (mk_usize 33);
  f_pq_key:t_Array u8 (mk_usize 1185)
}

/// Signature-checked and type-checked InitKex public keys.
type t_VerifiedInitKex = {
  f_beacon_identity_public_key:t_Array u8 (mk_usize 32);
  f_beacon_prekey_public_key:t_Array u8 (mk_usize 32);
  f_beacon_one_time_public_key:t_Array u8 (mk_usize 32);
  f_beacon_pq_public_key:t_Array u8 (mk_usize 1184)
}

/// Fresh beacon state. Calling [`beacon_start`] consumes this state.
type t_BeaconFresh = { f_server_key_id:u64 }

/// Beacon state tied to exactly one emitted InitKex.
type t_BeaconInitSent = {
  f_server_key_id:u64;
  f_beacon_identity_public_key:t_Array u8 (mk_usize 32)
}

type t_BeaconStart = {
  f_state:t_BeaconInitSent;
  f_message:t_InitKex
}

/// Four classical DH results followed by the post-quantum KEM secret.
type t_PqxdhSharedSecrets = {
  f_dh1:t_Array u8 (mk_usize 32);
  f_dh2:t_Array u8 (mk_usize 32);
  f_dh3:t_Array u8 (mk_usize 32);
  f_dh4:t_Array u8 (mk_usize 32);
  f_kem_shared_secret:t_Array u8 (mk_usize 32)
}

/// Exact `Padding || DH1 || DH2 || DH3 || DH4 || SS` input to the opaque
/// PQXDH HKDF operation.
type t_RootKeyInput = { f_bytes:t_Array u8 (mk_usize 192) }

/// The core-owned direction plan for splitting the opaque 64-byte ratchet
/// KDF result. Offsets are bytes into `LHS || RHS`.
type t_RatchetInitialization = {
  f_send_offset:u8;
  f_receive_offset:u8
}

let v_BEACON_RATCHETS: t_RatchetInitialization =
  { f_send_offset = cast (v_RATCHET_CHAIN_SIZE <: usize) <: u8; f_receive_offset = mk_u8 0 }
  <:
  t_RatchetInitialization

let v_SERVER_RATCHETS: t_RatchetInitialization =
  { f_send_offset = mk_u8 0; f_receive_offset = cast (v_RATCHET_CHAIN_SIZE <: usize) <: u8 }
  <:
  t_RatchetInitialization

/// Test and adapter utility for non-handshake ratchet fixtures. Production
/// PQXDH code obtains the same plan from a beacon candidate typestate.
let beacon_ratchet_initialization (_: Prims.unit) : t_RatchetInitialization = v_BEACON_RATCHETS

/// Test and adapter utility for non-handshake ratchet fixtures. Production
/// PQXDH code obtains the same plan from a server candidate typestate.
let server_ratchet_initialization (_: Prims.unit) : t_RatchetInitialization = v_SERVER_RATCHETS

/// Candidate beacon session. Its root, AD, identity assignment, and ratchet
/// direction have been validated, but its initial ciphertext has not yet
/// authenticated. It must be consumed by [`beacon_commit`] or
/// [`beacon_abort_candidate`].
type t_BeaconRegistrationCandidate = {
  f_server_key_id:u64;
  f_assigned_key_id:u64;
  f_root_key_input:t_RootKeyInput;
  f_associated_data:t_Array u8 (mk_usize 153)
}

type t_BeaconFinishInputs = {
  f_expected_server_identity:t_Array u8 (mk_usize 32);
  f_response_server_identity:t_Array u8 (mk_usize 32);
  f_assigned_key_id:u64;
  f_shared_secrets:t_PqxdhSharedSecrets
}

type t_BeaconEstablished = {
  f_server_key_id:u64;
  f_assigned_key_id:u64
}

type t_BeaconAborted = { f_server_key_id:u64 }

let beacon_commit (candidate: t_BeaconRegistrationCandidate) : t_BeaconEstablished =
  { f_server_key_id = candidate.f_server_key_id; f_assigned_key_id = candidate.f_assigned_key_id }
  <:
  t_BeaconEstablished

let beacon_abort_candidate (candidate: t_BeaconRegistrationCandidate) : t_BeaconAborted =
  { f_server_key_id = candidate.f_server_key_id } <: t_BeaconAborted

let beacon_abort_init (state: t_BeaconInitSent) : t_BeaconAborted =
  { f_server_key_id = state.f_server_key_id } <: t_BeaconAborted

let beacon_abort_fresh (state: t_BeaconFresh) : t_BeaconAborted =
  { f_server_key_id = state.f_server_key_id } <: t_BeaconAborted

/// Active server state. Pending registrations do not mutate it.
type t_ServerState = { f_last_key_id:u64 }

/// Explicit ephemeral/KEM outputs generated by the server adapter.
type t_ServerCoins = {
  f_ephemeral_public_key:t_Array u8 (mk_usize 32);
  f_kem_ciphertext:t_Array u8 (mk_usize 1088)
}

/// Stable identity of the server adapter that accepted a registration.
/// Pending registration tokens are checked against this binding before they
/// can prepare a commit, preventing a token created by one server instance
/// from mutating a differently identified server.
type t_ServerBinding = {
  f_identity_public_key:t_Array u8 (mk_usize 32);
  f_identity_key_id:u64
}

[@@ FStar.Tactics.Typeclasses.tcinstance]
assume
val impl_95': Core_models.Cmp.t_PartialEq t_ServerBinding t_ServerBinding

unfold
let impl_95 = impl_95'

/// Registration material that has passed parsing, signatures, key tags, DH
/// validation, and transcript construction but has not changed server state.
type t_PendingServerRegistration = {
  f_server_binding:t_ServerBinding;
  f_beacon_identity_public_key:t_Array u8 (mk_usize 32);
  f_ephemeral_public_key:t_Array u8 (mk_usize 32);
  f_kem_ciphertext:t_Array u8 (mk_usize 1088);
  f_root_key_input:t_RootKeyInput
}

/// Candidate server commit. The adapter must initialize a fresh ratchet,
/// encrypt the initial message, and serialize the response before consuming it
/// with [`server_commit`]. Dropping it leaves the active server unchanged.
type t_ServerRegistrationCandidate = {
  f_previous_state:t_ServerState;
  f_next_state:t_ServerState;
  f_key_id:u64;
  f_beacon_identity_public_key:t_Array u8 (mk_usize 32);
  f_server_identity_public_key:t_Array u8 (mk_usize 32);
  f_server_identity_key_id:u64;
  f_ephemeral_public_key:t_Array u8 (mk_usize 32);
  f_kem_ciphertext:t_Array u8 (mk_usize 1088);
  f_associated_data:t_Array u8 (mk_usize 153)
}

type t_EstablishedPeer = {
  f_key_id:u64;
  f_identity_public_key:t_Array u8 (mk_usize 32);
  f_associated_data:t_Array u8 (mk_usize 153)
}

let server_commit (candidate: t_ServerRegistrationCandidate) : (t_ServerState & t_EstablishedPeer) =
  candidate.f_next_state,
  ({
      f_key_id = candidate.f_key_id;
      f_identity_public_key = candidate.f_beacon_identity_public_key;
      f_associated_data = candidate.f_associated_data
    }
    <:
    t_EstablishedPeer)
  <:
  (t_ServerState & t_EstablishedPeer)

let server_abort_candidate (candidate: t_ServerRegistrationCandidate) : t_ServerState =
  candidate.f_previous_state

let is_all_zero (bytes: t_Array u8 (mk_usize 32)) : bool =
  bytes =. (Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 32) <: t_Array u8 (mk_usize 32))

let copy_32_ (output: t_Array u8 (mk_usize 192)) (offset: usize) (input: t_Array u8 (mk_usize 32))
    : t_Array u8 (mk_usize 192) =
  let index:usize = mk_usize 0 in
  match
    Rust_primitives.Hax.while_loop_return (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 192)) = temp_0_ in
          true)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 192)) = temp_0_ in
          index <. mk_usize 32 <: bool)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 192)) = temp_0_ in
          Rust_primitives.Hax.Int.from_machine (mk_u32 0) <: Hax_lib.Int.t_Int)
      (index, output <: (usize & t_Array u8 (mk_usize 192)))
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 192)) = temp_0_ in
          if
            (index >=. mk_usize 32 <: bool) || (offset >. v_ROOT_KEY_INPUT_SIZE <: bool) ||
            (index >=. (v_ROOT_KEY_INPUT_SIZE -! offset <: usize) <: bool)
          then
            Core_models.Ops.Control_flow.ControlFlow_Break
            (Core_models.Ops.Control_flow.ControlFlow_Break output
              <:
              Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 192))
                (Prims.unit & (usize & t_Array u8 (mk_usize 192))))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 192))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 192))))
              (usize & t_Array u8 (mk_usize 192))
          else
            let output:t_Array u8 (mk_usize 192) =
              Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
                (offset +! index <: usize)
                (input.[ index ] <: u8)
            in
            let index:usize = index +! mk_usize 1 in
            Core_models.Ops.Control_flow.ControlFlow_Continue
            (index, output <: (usize & t_Array u8 (mk_usize 192)))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 192))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 192))))
              (usize & t_Array u8 (mk_usize 192)))
    <:
    Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 192))
      (usize & t_Array u8 (mk_usize 192))
  with
  | Core_models.Ops.Control_flow.ControlFlow_Break ret -> ret
  | Core_models.Ops.Control_flow.ControlFlow_Continue (index, output) -> output

let build_root_key_input (secrets: t_PqxdhSharedSecrets)
    : Core_models.Result.t_Result t_RootKeyInput t_RegistrationError =
  if
    is_all_zero secrets.f_dh1 || is_all_zero secrets.f_dh2 || is_all_zero secrets.f_dh3 ||
    is_all_zero secrets.f_dh4
  then
    Core_models.Result.Result_Err (RegistrationError_InvalidDhOutput <: t_RegistrationError)
    <:
    Core_models.Result.t_Result t_RootKeyInput t_RegistrationError
  else
    let bytes:t_Array u8 (mk_usize 192) = Rust_primitives.Hax.repeat (mk_u8 255) (mk_usize 192) in
    let offset:usize = v_PQXDH_PADDING_SIZE in
    let bytes:t_Array u8 (mk_usize 192) = copy_32_ bytes offset secrets.f_dh1 in
    let offset:usize = offset +! v_DH_SECRET_SIZE in
    let bytes:t_Array u8 (mk_usize 192) = copy_32_ bytes offset secrets.f_dh2 in
    let offset:usize = offset +! v_DH_SECRET_SIZE in
    let bytes:t_Array u8 (mk_usize 192) = copy_32_ bytes offset secrets.f_dh3 in
    let offset:usize = offset +! v_DH_SECRET_SIZE in
    let bytes:t_Array u8 (mk_usize 192) = copy_32_ bytes offset secrets.f_dh4 in
    let offset:usize = offset +! v_DH_SECRET_SIZE in
    let bytes:t_Array u8 (mk_usize 192) = copy_32_ bytes offset secrets.f_kem_shared_secret in
    Core_models.Result.Result_Ok ({ f_bytes = bytes } <: t_RootKeyInput)
    <:
    Core_models.Result.t_Result t_RootKeyInput t_RegistrationError

/// Accept a verified InitKex without committing any peer or counter state.
let server_accept
      (state: t_ServerState)
      (registration: t_VerifiedInitKex)
      (server_binding: t_ServerBinding)
      (coins: t_ServerCoins)
      (shared_secrets: t_PqxdhSharedSecrets)
    : Core_models.Result.t_Result (t_ServerState & t_PendingServerRegistration) t_RegistrationError =
  match
    build_root_key_input shared_secrets
    <:
    Core_models.Result.t_Result t_RootKeyInput t_RegistrationError
  with
  | Core_models.Result.Result_Ok root_key_input ->
    Core_models.Result.Result_Ok
    (state,
      ({
          f_server_binding = server_binding;
          f_beacon_identity_public_key = registration.f_beacon_identity_public_key;
          f_ephemeral_public_key = coins.f_ephemeral_public_key;
          f_kem_ciphertext = coins.f_kem_ciphertext;
          f_root_key_input = root_key_input
        }
        <:
        t_PendingServerRegistration)
      <:
      (t_ServerState & t_PendingServerRegistration))
    <:
    Core_models.Result.t_Result (t_ServerState & t_PendingServerRegistration) t_RegistrationError
  | Core_models.Result.Result_Err err ->
    Core_models.Result.Result_Err err
    <:
    Core_models.Result.t_Result (t_ServerState & t_PendingServerRegistration) t_RegistrationError

let copy_associated_data (output: t_Array u8 (mk_usize 153)) (offset: usize) (input: t_Slice u8)
    : t_Array u8 (mk_usize 153) =
  let index:usize = mk_usize 0 in
  match
    Rust_primitives.Hax.while_loop_return (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 153)) = temp_0_ in
          true)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 153)) = temp_0_ in
          index <. (Core_models.Slice.impl__len #u8 input <: usize) <: bool)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 153)) = temp_0_ in
          Rust_primitives.Hax.Int.from_machine (mk_u32 0) <: Hax_lib.Int.t_Int)
      (index, output <: (usize & t_Array u8 (mk_usize 153)))
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 153)) = temp_0_ in
          if
            (index >=. (Core_models.Slice.impl__len #u8 input <: usize) <: bool) ||
            (offset >. v_ASSOCIATED_DATA_SIZE <: bool) ||
            (index >=. (v_ASSOCIATED_DATA_SIZE -! offset <: usize) <: bool)
          then
            Core_models.Ops.Control_flow.ControlFlow_Break
            (Core_models.Ops.Control_flow.ControlFlow_Break output
              <:
              Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 153))
                (Prims.unit & (usize & t_Array u8 (mk_usize 153))))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 153))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 153))))
              (usize & t_Array u8 (mk_usize 153))
          else
            let output:t_Array u8 (mk_usize 153) =
              Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
                (offset +! index <: usize)
                (input.[ index ] <: u8)
            in
            let index:usize = index +! mk_usize 1 in
            Core_models.Ops.Control_flow.ControlFlow_Continue
            (index, output <: (usize & t_Array u8 (mk_usize 153)))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 153))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 153))))
              (usize & t_Array u8 (mk_usize 153)))
    <:
    Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 153))
      (usize & t_Array u8 (mk_usize 153))
  with
  | Core_models.Ops.Control_flow.ControlFlow_Break ret -> ret
  | Core_models.Ops.Control_flow.ControlFlow_Continue (index, output) -> output

let copy_32_to_encoded (output: t_Array u8 (mk_usize 33)) (input: t_Array u8 (mk_usize 32))
    : t_Array u8 (mk_usize 33) =
  let index:usize = mk_usize 0 in
  match
    Rust_primitives.Hax.while_loop_return (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 33)) = temp_0_ in
          true)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 33)) = temp_0_ in
          index <. v_SIGN_PUBLIC_KEY_SIZE <: bool)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 33)) = temp_0_ in
          Rust_primitives.Hax.Int.from_machine (mk_u32 0) <: Hax_lib.Int.t_Int)
      (index, output <: (usize & t_Array u8 (mk_usize 33)))
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 33)) = temp_0_ in
          if index >=. v_SIGN_PUBLIC_KEY_SIZE <: bool
          then
            Core_models.Ops.Control_flow.ControlFlow_Break
            (Core_models.Ops.Control_flow.ControlFlow_Break output
              <:
              Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 33))
                (Prims.unit & (usize & t_Array u8 (mk_usize 33))))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 33))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 33))))
              (usize & t_Array u8 (mk_usize 33))
          else
            let output:t_Array u8 (mk_usize 33) =
              Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
                (mk_usize 1 +! index <: usize)
                (input.[ index ] <: u8)
            in
            let index:usize = index +! mk_usize 1 in
            Core_models.Ops.Control_flow.ControlFlow_Continue
            (index, output <: (usize & t_Array u8 (mk_usize 33)))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 33))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 33))))
              (usize & t_Array u8 (mk_usize 33)))
    <:
    Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 33))
      (usize & t_Array u8 (mk_usize 33))
  with
  | Core_models.Ops.Control_flow.ControlFlow_Break ret -> ret
  | Core_models.Ops.Control_flow.ControlFlow_Continue (index, output) -> output

let tag_sign_key (key: t_Array u8 (mk_usize 32)) : t_Array u8 (mk_usize 33) =
  let output:t_Array u8 (mk_usize 33) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 33) in
  let output:t_Array u8 (mk_usize 33) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
      (mk_usize 0)
      v_SIGN_TYPE_ED25519
  in
  let output:t_Array u8 (mk_usize 33) = copy_32_to_encoded output key in
  output

/// Associated data is always encoded server identity first, beacon identity
/// second, then the key-exchange and ratchet domain-separation strings.
let build_associated_data
      (server_identity_public_key beacon_identity_public_key: t_Array u8 (mk_usize 32))
    : t_Array u8 (mk_usize 153) =
  let encoded_server:t_Array u8 (mk_usize 33) = tag_sign_key server_identity_public_key in
  let encoded_beacon:t_Array u8 (mk_usize 33) = tag_sign_key beacon_identity_public_key in
  let output:t_Array u8 (mk_usize 153) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 153) in
  let offset:usize = mk_usize 0 in
  let output:t_Array u8 (mk_usize 153) =
    copy_associated_data output offset (encoded_server <: t_Slice u8)
  in
  let offset:usize = offset +! v_ENCODED_SIGN_PUBLIC_KEY_SIZE in
  let output:t_Array u8 (mk_usize 153) =
    copy_associated_data output offset (encoded_beacon <: t_Slice u8)
  in
  let offset:usize = offset +! v_ENCODED_SIGN_PUBLIC_KEY_SIZE in
  let output:t_Array u8 (mk_usize 153) =
    copy_associated_data output offset (v_PQXDH_INFO <: t_Slice u8)
  in
  let offset:usize =
    offset +! (Core_models.Slice.impl__len #u8 (v_PQXDH_INFO <: t_Slice u8) <: usize)
  in
  let output:t_Array u8 (mk_usize 153) =
    copy_associated_data output offset (v_SYM_RATCHET_INFO <: t_Slice u8)
  in
  output

let beacon_prepare_finish (state: t_BeaconInitSent) (inputs: t_BeaconFinishInputs)
    : Core_models.Result.t_Result t_BeaconRegistrationCandidate t_RegistrationError =
  if inputs.f_expected_server_identity <>. inputs.f_response_server_identity
  then
    Core_models.Result.Result_Err (RegistrationError_IdentityMismatch <: t_RegistrationError)
    <:
    Core_models.Result.t_Result t_BeaconRegistrationCandidate t_RegistrationError
  else
    match
      build_root_key_input inputs.f_shared_secrets
      <:
      Core_models.Result.t_Result t_RootKeyInput t_RegistrationError
    with
    | Core_models.Result.Result_Ok root_key_input ->
      let associated_data:t_Array u8 (mk_usize 153) =
        build_associated_data inputs.f_response_server_identity state.f_beacon_identity_public_key
      in
      Core_models.Result.Result_Ok
      ({
          f_server_key_id = state.f_server_key_id;
          f_assigned_key_id = inputs.f_assigned_key_id;
          f_root_key_input = root_key_input;
          f_associated_data = associated_data
        }
        <:
        t_BeaconRegistrationCandidate)
      <:
      Core_models.Result.t_Result t_BeaconRegistrationCandidate t_RegistrationError
    | Core_models.Result.Result_Err err ->
      Core_models.Result.Result_Err err
      <:
      Core_models.Result.t_Result t_BeaconRegistrationCandidate t_RegistrationError

/// Prepare the next server key ID using the current Stage-4 allocation rule.
/// Collision-safe checked allocation remains a Stage-5 obligation.
let server_prepare_commit
      (state: t_ServerState)
      (pending: t_PendingServerRegistration)
      (current_server_binding: t_ServerBinding)
    : Core_models.Result.t_Result t_ServerRegistrationCandidate t_RegistrationError =
  if pending.f_server_binding <>. current_server_binding
  then
    Core_models.Result.Result_Err (RegistrationError_IdentityMismatch <: t_RegistrationError)
    <:
    Core_models.Result.t_Result t_ServerRegistrationCandidate t_RegistrationError
  else
    let key_id:u64 = Core_models.Num.impl_u64__wrapping_add state.f_last_key_id (mk_u64 1) in
    Core_models.Result.Result_Ok
    ({
        f_previous_state = state;
        f_next_state = { f_last_key_id = key_id } <: t_ServerState;
        f_key_id = key_id;
        f_beacon_identity_public_key = pending.f_beacon_identity_public_key;
        f_server_identity_public_key = current_server_binding.f_identity_public_key;
        f_server_identity_key_id = current_server_binding.f_identity_key_id;
        f_ephemeral_public_key = pending.f_ephemeral_public_key;
        f_kem_ciphertext = pending.f_kem_ciphertext;
        f_associated_data
        =
        build_associated_data current_server_binding.f_identity_public_key
          pending.f_beacon_identity_public_key
      }
      <:
      t_ServerRegistrationCandidate)
    <:
    Core_models.Result.t_Result t_ServerRegistrationCandidate t_RegistrationError

let tag_x25519_key (key: t_Array u8 (mk_usize 32)) : t_Array u8 (mk_usize 33) =
  let output:t_Array u8 (mk_usize 33) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 33) in
  let output:t_Array u8 (mk_usize 33) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
      (mk_usize 0)
      v_KEM_TYPE_X25519
  in
  let output:t_Array u8 (mk_usize 33) = copy_32_to_encoded output key in
  output

let copy_mlkem768_to_encoded
      (output: t_Array u8 (mk_usize 1185))
      (input: t_Array u8 (mk_usize 1184))
    : t_Array u8 (mk_usize 1185) =
  let index:usize = mk_usize 0 in
  match
    Rust_primitives.Hax.while_loop_return (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 1185)) = temp_0_ in
          true)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 1185)) = temp_0_ in
          index <. v_MLKEM768_PUBLIC_KEY_SIZE <: bool)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 1185)) = temp_0_ in
          Rust_primitives.Hax.Int.from_machine (mk_u32 0) <: Hax_lib.Int.t_Int)
      (index, output <: (usize & t_Array u8 (mk_usize 1185)))
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 1185)) = temp_0_ in
          if index >=. v_MLKEM768_PUBLIC_KEY_SIZE <: bool
          then
            Core_models.Ops.Control_flow.ControlFlow_Break
            (Core_models.Ops.Control_flow.ControlFlow_Break output
              <:
              Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 1185))
                (Prims.unit & (usize & t_Array u8 (mk_usize 1185))))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 1185))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 1185))))
              (usize & t_Array u8 (mk_usize 1185))
          else
            let output:t_Array u8 (mk_usize 1185) =
              Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
                (mk_usize 1 +! index <: usize)
                (input.[ index ] <: u8)
            in
            let index:usize = index +! mk_usize 1 in
            Core_models.Ops.Control_flow.ControlFlow_Continue
            (index, output <: (usize & t_Array u8 (mk_usize 1185)))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 1185))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 1185))))
              (usize & t_Array u8 (mk_usize 1185)))
    <:
    Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 1185))
      (usize & t_Array u8 (mk_usize 1185))
  with
  | Core_models.Ops.Control_flow.ControlFlow_Break ret -> ret
  | Core_models.Ops.Control_flow.ControlFlow_Continue (index, output) -> output

let tag_mlkem768_key (key: t_Array u8 (mk_usize 1184)) : t_Array u8 (mk_usize 1185) =
  let output:t_Array u8 (mk_usize 1185) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 1185) in
  let output:t_Array u8 (mk_usize 1185) =
    Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
      (mk_usize 0)
      v_KEM_TYPE_MLKEM768
  in
  let output:t_Array u8 (mk_usize 1185) = copy_mlkem768_to_encoded output key in
  output

/// Construct the exact tagged InitKex payloads from explicit generated
/// material and advance the beacon to its single pending registration.
let beacon_start (state: t_BeaconFresh) (inputs: t_BeaconStartInputs) (coins: t_BeaconCoins)
    : t_BeaconStart =
  {
    f_state
    =
    {
      f_server_key_id = state.f_server_key_id;
      f_beacon_identity_public_key = inputs.f_identity_public_key
    }
    <:
    t_BeaconInitSent;
    f_message
    =
    {
      f_identity_key = tag_sign_key inputs.f_identity_public_key;
      f_prekey = tag_x25519_key inputs.f_prekey_public_key;
      f_one_time_key = tag_x25519_key coins.f_one_time_public_key;
      f_pq_key = tag_mlkem768_key inputs.f_pq_public_key
    }
    <:
    t_InitKex
  }
  <:
  t_BeaconStart

let copy_32_from_encoded (output: t_Array u8 (mk_usize 32)) (input: t_Array u8 (mk_usize 33))
    : t_Array u8 (mk_usize 32) =
  let index:usize = mk_usize 0 in
  match
    Rust_primitives.Hax.while_loop_return (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 32)) = temp_0_ in
          true)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 32)) = temp_0_ in
          index <. v_SIGN_PUBLIC_KEY_SIZE <: bool)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 32)) = temp_0_ in
          Rust_primitives.Hax.Int.from_machine (mk_u32 0) <: Hax_lib.Int.t_Int)
      (index, output <: (usize & t_Array u8 (mk_usize 32)))
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 32)) = temp_0_ in
          if index >=. v_SIGN_PUBLIC_KEY_SIZE <: bool
          then
            Core_models.Ops.Control_flow.ControlFlow_Break
            (Core_models.Ops.Control_flow.ControlFlow_Break output
              <:
              Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 32))
                (Prims.unit & (usize & t_Array u8 (mk_usize 32))))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 32))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 32))))
              (usize & t_Array u8 (mk_usize 32))
          else
            let output:t_Array u8 (mk_usize 32) =
              Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
                index
                (input.[ mk_usize 1 +! index <: usize ] <: u8)
            in
            let index:usize = index +! mk_usize 1 in
            Core_models.Ops.Control_flow.ControlFlow_Continue
            (index, output <: (usize & t_Array u8 (mk_usize 32)))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 32))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 32))))
              (usize & t_Array u8 (mk_usize 32)))
    <:
    Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 32))
      (usize & t_Array u8 (mk_usize 32))
  with
  | Core_models.Ops.Control_flow.ControlFlow_Break ret -> ret
  | Core_models.Ops.Control_flow.ControlFlow_Continue (index, output) -> output

let untag_sign_key (encoded: t_Array u8 (mk_usize 33))
    : Core_models.Option.t_Option (t_Array u8 (mk_usize 32)) =
  if (encoded.[ mk_usize 0 ] <: u8) <>. v_SIGN_TYPE_ED25519
  then Core_models.Option.Option_None <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))
  else
    let key:t_Array u8 (mk_usize 32) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 32) in
    let key:t_Array u8 (mk_usize 32) = copy_32_from_encoded key encoded in
    Core_models.Option.Option_Some key <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))

let untag_x25519_key (encoded: t_Array u8 (mk_usize 33))
    : Core_models.Option.t_Option (t_Array u8 (mk_usize 32)) =
  if (encoded.[ mk_usize 0 ] <: u8) <>. v_KEM_TYPE_X25519
  then Core_models.Option.Option_None <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))
  else
    let key:t_Array u8 (mk_usize 32) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 32) in
    let key:t_Array u8 (mk_usize 32) = copy_32_from_encoded key encoded in
    Core_models.Option.Option_Some key <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))

let copy_mlkem768_from_encoded
      (output: t_Array u8 (mk_usize 1184))
      (input: t_Array u8 (mk_usize 1185))
    : t_Array u8 (mk_usize 1184) =
  let index:usize = mk_usize 0 in
  match
    Rust_primitives.Hax.while_loop_return (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 1184)) = temp_0_ in
          true)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 1184)) = temp_0_ in
          index <. v_MLKEM768_PUBLIC_KEY_SIZE <: bool)
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 1184)) = temp_0_ in
          Rust_primitives.Hax.Int.from_machine (mk_u32 0) <: Hax_lib.Int.t_Int)
      (index, output <: (usize & t_Array u8 (mk_usize 1184)))
      (fun temp_0_ ->
          let (index: usize), (output: t_Array u8 (mk_usize 1184)) = temp_0_ in
          if index >=. v_MLKEM768_PUBLIC_KEY_SIZE <: bool
          then
            Core_models.Ops.Control_flow.ControlFlow_Break
            (Core_models.Ops.Control_flow.ControlFlow_Break output
              <:
              Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 1184))
                (Prims.unit & (usize & t_Array u8 (mk_usize 1184))))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 1184))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 1184))))
              (usize & t_Array u8 (mk_usize 1184))
          else
            let output:t_Array u8 (mk_usize 1184) =
              Rust_primitives.Hax.Monomorphized_update_at.update_at_usize output
                index
                (input.[ mk_usize 1 +! index <: usize ] <: u8)
            in
            let index:usize = index +! mk_usize 1 in
            Core_models.Ops.Control_flow.ControlFlow_Continue
            (index, output <: (usize & t_Array u8 (mk_usize 1184)))
            <:
            Core_models.Ops.Control_flow.t_ControlFlow
              (Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 1184))
                  (Prims.unit & (usize & t_Array u8 (mk_usize 1184))))
              (usize & t_Array u8 (mk_usize 1184)))
    <:
    Core_models.Ops.Control_flow.t_ControlFlow (t_Array u8 (mk_usize 1184))
      (usize & t_Array u8 (mk_usize 1184))
  with
  | Core_models.Ops.Control_flow.ControlFlow_Break ret -> ret
  | Core_models.Ops.Control_flow.ControlFlow_Continue (index, output) -> output

let untag_mlkem768_key (encoded: t_Array u8 (mk_usize 1185))
    : Core_models.Option.t_Option (t_Array u8 (mk_usize 1184)) =
  if (encoded.[ mk_usize 0 ] <: u8) <>. v_KEM_TYPE_MLKEM768
  then Core_models.Option.Option_None <: Core_models.Option.t_Option (t_Array u8 (mk_usize 1184))
  else
    let key:t_Array u8 (mk_usize 1184) = Rust_primitives.Hax.repeat (mk_u8 0) (mk_usize 1184) in
    let key:t_Array u8 (mk_usize 1184) = copy_mlkem768_from_encoded key encoded in
    Core_models.Option.Option_Some key <: Core_models.Option.t_Option (t_Array u8 (mk_usize 1184))

/// Re-establish typed, verified registration keys after signature checks in
/// the adapter. Incorrect or non-disjoint algorithm tags are rejected here.
let validate_init_kex (message: t_InitKex)
    : Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError =
  match
    untag_sign_key message.f_identity_key <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))
  with
  | Core_models.Option.Option_Some identity ->
    (match
        untag_x25519_key message.f_prekey <: Core_models.Option.t_Option (t_Array u8 (mk_usize 32))
      with
      | Core_models.Option.Option_Some prekey ->
        (match
            untag_x25519_key message.f_one_time_key
            <:
            Core_models.Option.t_Option (t_Array u8 (mk_usize 32))
          with
          | Core_models.Option.Option_Some one_time ->
            (match
                untag_mlkem768_key message.f_pq_key
                <:
                Core_models.Option.t_Option (t_Array u8 (mk_usize 1184))
              with
              | Core_models.Option.Option_Some pq ->
                Core_models.Result.Result_Ok
                ({
                    f_beacon_identity_public_key = identity;
                    f_beacon_prekey_public_key = prekey;
                    f_beacon_one_time_public_key = one_time;
                    f_beacon_pq_public_key = pq
                  }
                  <:
                  t_VerifiedInitKex)
                <:
                Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError
              | _ ->
                Core_models.Result.Result_Err
                (RegistrationError_InvalidKeyEncoding <: t_RegistrationError)
                <:
                Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError)
          | _ ->
            Core_models.Result.Result_Err
            (RegistrationError_InvalidKeyEncoding <: t_RegistrationError)
            <:
            Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError)
      | _ ->
        Core_models.Result.Result_Err (RegistrationError_InvalidKeyEncoding <: t_RegistrationError)
        <:
        Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError)
  | _ ->
    Core_models.Result.Result_Err (RegistrationError_InvalidKeyEncoding <: t_RegistrationError)
    <:
    Core_models.Result.t_Result t_VerifiedInitKex t_RegistrationError
