import BeaconcryptCore.Refinement.PqxdhBytes

/-!
# The generated key encodings refine the ideal ones

The ideal model of `pqxdh_spec.md` §4 fixes the authenticated public-key encodings
`Tag_sig`, `Tag_X` and `Tag_PQ` (`Pqxdh.tagSig`, `Pqxdh.tagX`, `Pqxdh.tagPQ`) and their
parsers (`Pqxdh.parseSigTag`, `Pqxdh.parseXTag`, `Pqxdh.parsePQTag`).

The generated code builds and parses the same encodings byte by byte with
`core::array::from_fn`.  This file proves that the generated routines compute exactly
the ideal encodings and parsers.
-/

open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM

set_option maxHeartbeats 1000000
set_option relaxedAutoImplicit false
set_option autoImplicit false

open beaconcrypt_core

namespace PqxdhRefinement

/-! ## Pointwise characterisation of a generated byte array -/

/-- If a pure `from_fn` closure produces, at every index, the byte at that index of a
model byte string of the right length, then the generated array abstracts to that
model byte string. -/
theorem from_fn_absBytes {F : Type} (N : Std.Usize)
    (inst : core.ops.function.FnMut F Std.Usize Std.U8) (f : F) (u : ℕ → Std.U8)
    (out : Pqxdh.Bytes) (hlen : out.length = N.val)
    (h : ∀ i, i < N.val → inst.call_mut f ⟨BitVec.ofNat _ i⟩ = ok (u i, f))
    (hu : ∀ i, i < N.val → absByte (u i) = out[i]!) :
    ∃ a : Std.Array Std.U8 N, core.array.from_fn N inst f = ok a ∧ absBytes a = out := by
  obtain ⟨a, ha, hval⟩ := from_fn_pure N inst f u h
  refine ⟨a, ha, ?_⟩
  rw [absBytes, hval, List.map_map]
  have : (List.range N.val).map (absByte ∘ u) = (List.range out.length).map (fun i => out[i]!) := by
    rw [hlen]
    apply List.map_congr_left
    intro i hi
    exact hu i (by simpa using hi)
  rw [this, map_range_getElem!]

/-! ## Reading a model byte string at an index -/

/-- Indexing a concatenation. -/
theorem getElem!_append (l r : Pqxdh.Bytes) (i : ℕ) :
    (l ++ r)[i]! = if i < l.length then l[i]! else r[i - l.length]! := by
  by_cases h : i < l.length
  · have hi : i < (l ++ r).length := by simp only [List.length_append]; omega
    rw [if_pos h, getElem!_pos (l ++ r) i hi, getElem!_pos l i h,
      List.getElem_append_left h]
  · rw [if_neg h]
    by_cases h2 : i - l.length < r.length
    · have hi : i < (l ++ r).length := by simp only [List.length_append]; omega
      rw [getElem!_pos (l ++ r) i hi, getElem!_pos r (i - l.length) h2,
        List.getElem_append_right (by omega)]
    · have hi : ¬ i < (l ++ r).length := by simp only [List.length_append]; omega
      rw [getElem!_neg (l ++ r) i hi, getElem!_neg r (i - l.length) h2]

/-- Indexing the byte abstraction of a generated array. -/
theorem absBytes_getElem! {n : Std.Usize} (a : Std.Array Std.U8 n) (i : ℕ) (h : i < n.val) :
    (absBytes a)[i]! = absByte a.val[i]! := by
  have hl : a.val.length = n.val := a.property
  rw [absBytes, getElem!_pos (a.val.map absByte) i (by simp; omega),
    getElem!_pos a.val i (by omega)]
  simp

/-- Indexing a dropped suffix of an abstracted array. -/
theorem getElem!_drop_absBytes {n : Std.Usize} (a : Std.Array Std.U8 n) (d i : ℕ)
    (h : i + d < n.val) : ((absBytes a).drop d)[i]! = absByte a.val[i + d]! := by
  have hl : a.val.length = n.val := a.property
  have h1 : i < ((absBytes a).drop d).length := by simp [absBytes]; omega
  have h2 : d + i < (absBytes a).length := by simp [absBytes]; omega
  rw [Nat.add_comm i d, getElem!_pos _ i h1, List.getElem_drop,
    ← getElem!_pos (absBytes a) (d + i) h2]
  exact absBytes_getElem! a (d + i) (by omega)

/-- Length of a dropped suffix of an abstracted array. -/
theorem length_drop_absBytes {n : Std.Usize} (a : Std.Array Std.U8 n) (d : ℕ) :
    ((absBytes a).drop d).length = n.val - d := by simp [absBytes]

/-- A nonempty list is its head followed by its tail. -/
theorem list_eq_cons_drop {α : Type} [Inhabited α] (l : List α) (h : 0 < l.length) :
    l = l[0]! :: l.drop 1 := by
  cases l with
  | nil => simp at h
  | cons x xs => simp

/-! ## `Tag_sig` -/

/-- The generated Ed25519 key encoding is the ideal `Tag_sig`. -/
theorem tag_sign_key_abs (key : Std.Array Std.U8 32#usize) :
    ∃ a : Std.Array Std.U8 33#usize,
      pqxdh.tag_sign_key key = ok a ∧ absBytes a = Pqxdh.tagSig (absBytes key) := by
  have hlen : (Pqxdh.tagSig (absBytes key)).length = (33#usize).val := by
    simp [Pqxdh.tagSig]
  have hcall : ∀ i, i < (33#usize).val →
      pqxdh.tag_sign_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut key
        ⟨BitVec.ofNat _ i⟩
        = ok ((if i = 0 then pqxdh.SIGN_TYPE_ED25519 else key.val[i - 1]!), key) := by
    intro i hi
    rw [usize_val_33] at hi
    have hval : (⟨BitVec.ofNat _ i⟩ : Std.Usize).val = i := usize_mk_val i (by omega)
    have hlt1 : ((⟨BitVec.ofNat _ i⟩ : Std.Usize) < 1#usize) ↔ i < 1 := by
      rw [Std.UScalar.lt_equiv, hval, usize_val_1]
    unfold pqxdh.tag_sign_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
    by_cases h0 : i = 0
    · subst h0
      rw [if_pos (hlt1.mpr (by omega))]
      simp
    · rw [if_neg (fun h => absurd (hlt1.mp h) (by omega)), if_neg h0]
      have hsub : (1#usize).val ≤ (⟨BitVec.ofNat _ i⟩ : Std.Usize).val := by
        rw [usize_val_1, hval]; omega
      rw [usize_sub_eq _ _ hsub]
      have h1 : (⟨BitVec.ofNat _ ((⟨BitVec.ofNat _ i⟩ : Std.Usize).val - (1#usize).val)⟩ :
          Std.Usize).val = i - 1 := by
        rw [hval, usize_val_1]
        exact usize_mk_val (i - 1) (by omega)
      simp only [bind_tc_ok]
      rw [index_usize_eq key _ (by rw [h1, usize_val_32]; omega), h1]
      simp
  have hbyte : ∀ i, i < (33#usize).val →
      absByte (if i = 0 then pqxdh.SIGN_TYPE_ED25519 else key.val[i - 1]!)
        = (Pqxdh.tagSig (absBytes key))[i]! := by
    intro i hi
    rw [usize_val_33] at hi
    match i with
    | 0 => simp [Pqxdh.tagSig, absByte, pqxdh.SIGN_TYPE_ED25519]
    | (j + 1) =>
      have hj : j < (32#usize).val := by rw [usize_val_32]; omega
      rw [if_neg (Nat.succ_ne_zero j)]
      simp only [Nat.add_sub_cancel, Pqxdh.tagSig, List.getElem!_cons_succ]
      exact (absBytes_getElem! key j hj).symm
  obtain ⟨a, ha, habs⟩ :=
    from_fn_absBytes (F := pqxdh.tag_sign_key.closure) 33#usize
      pqxdh.tag_sign_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 key _ _ hlen hcall hbyte
  exact ⟨a, by simpa [pqxdh.tag_sign_key] using ha, habs⟩


/-! ## Parsers on a `cons` -/

theorem parseSigTag_cons (b : UInt8) (rest : Pqxdh.Bytes) :
    Pqxdh.parseSigTag (b :: rest) =
      if b = 0x01 ∧ rest.length = 32 then some rest else none := by
  unfold Pqxdh.parseSigTag
  by_cases h : b = 0x01 <;> simp [h]

theorem parseXTag_cons2 (role b0 b1 : UInt8) (rest : Pqxdh.Bytes) :
    Pqxdh.parseXTag role (b0 :: b1 :: rest) =
      if b0 = 0x04 ∧ b1 = role ∧ rest.length = 32 then some rest else none := by
  unfold Pqxdh.parseXTag
  by_cases h : b0 = 0x04 <;> by_cases h1 : b1 = role <;> simp [h, h1]

theorem parsePQTag_cons (b : UInt8) (rest : Pqxdh.Bytes) :
    Pqxdh.parsePQTag (b :: rest) =
      if b = 0x03 ∧ rest.length = 1184 then some rest else none := by
  unfold Pqxdh.parsePQTag
  by_cases h : b = 0x03 <;> simp [h]

/-! ## Bounds -/

/-- Every natural number below `2 ^ 32` fits in a `usize`. -/
theorem lt_numBits (i : ℕ) (h : i < 2 ^ 32) : i < 2 ^ System.Platform.numBits := by
  have h64 : (2 : ℕ) ^ 32 ≤ 2 ^ 64 := by norm_num
  rcases System.Platform.numBits_eq with h' | h' <;> rw [h'] <;> omega

/-! ## `Tag_PQ` -/

/-- The generated ML-KEM-768 key encoding is the ideal `Tag_PQ`. -/
theorem tag_mlkem768_key_abs (key : Std.Array Std.U8 1184#usize) :
    ∃ a : Std.Array Std.U8 1185#usize,
      pqxdh.tag_mlkem768_key key = ok a ∧ absBytes a = Pqxdh.tagPQ (absBytes key) := by
  have hlen : (Pqxdh.tagPQ (absBytes key)).length = (1185#usize).val := by
    simp [Pqxdh.tagPQ]
  have hcall : ∀ i, i < (1185#usize).val →
      pqxdh.tag_mlkem768_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut key
        ⟨BitVec.ofNat _ i⟩
        = ok ((if i = 0 then pqxdh.KEM_TYPE_MLKEM768 else key.val[i - 1]!), key) := by
    intro i hi
    rw [usize_val_1185] at hi
    have hval : (⟨BitVec.ofNat _ i⟩ : Std.Usize).val = i := usize_mk_val i (by omega)
    have hlt1 : ((⟨BitVec.ofNat _ i⟩ : Std.Usize) < 1#usize) ↔ i < 1 := by
      rw [Std.UScalar.lt_equiv, hval, usize_val_1]
    unfold pqxdh.tag_mlkem768_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
    by_cases h0 : i = 0
    · subst h0
      rw [if_pos (hlt1.mpr (by omega))]
      simp
    · rw [if_neg (fun h => absurd (hlt1.mp h) (by omega)), if_neg h0]
      have hsub : (1#usize).val ≤ (⟨BitVec.ofNat _ i⟩ : Std.Usize).val := by
        rw [usize_val_1, hval]; omega
      rw [usize_sub_eq _ _ hsub]
      have h1 : (⟨BitVec.ofNat _ ((⟨BitVec.ofNat _ i⟩ : Std.Usize).val - (1#usize).val)⟩ :
          Std.Usize).val = i - 1 := by
        rw [hval, usize_val_1]
        exact usize_mk_val (i - 1) (by omega)
      simp only [bind_tc_ok]
      rw [index_usize_eq key _ (by rw [h1, usize_val_1184]; omega), h1]
      simp
  have hbyte : ∀ i, i < (1185#usize).val →
      absByte (if i = 0 then pqxdh.KEM_TYPE_MLKEM768 else key.val[i - 1]!)
        = (Pqxdh.tagPQ (absBytes key))[i]! := by
    intro i hi
    rw [usize_val_1185] at hi
    match i with
    | 0 => simp [Pqxdh.tagPQ, absByte, pqxdh.KEM_TYPE_MLKEM768]
    | (j + 1) =>
      have hj : j < (1184#usize).val := by rw [usize_val_1184]; omega
      rw [if_neg (Nat.succ_ne_zero j)]
      simp only [Nat.add_sub_cancel, Pqxdh.tagPQ, List.getElem!_cons_succ]
      exact (absBytes_getElem! key j hj).symm
  obtain ⟨a, ha, habs⟩ :=
    from_fn_absBytes (F := pqxdh.tag_mlkem768_key.closure) 1185#usize
      pqxdh.tag_mlkem768_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 key _ _ hlen hcall
      hbyte
  exact ⟨a, by simpa [pqxdh.tag_mlkem768_key] using ha, habs⟩

/-! ## `Tag_X` -/

/-- The generated `Tag_X` closure, with its captured pair destructured. -/
theorem tag_x25519_call_mut (role : Std.U8) (key : Std.Array Std.U8 32#usize)
    (t : Std.Usize) :
    pqxdh.tag_x25519_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
        ((role, key) : pqxdh.tag_x25519_key.closure) t
      = (if t < 1#usize then
            ok (pqxdh.KEM_TYPE_X25519, ((role, key) : pqxdh.tag_x25519_key.closure))
          else if t < 2#usize then
            ok (role, ((role, key) : pqxdh.tag_x25519_key.closure))
          else do
            let i1 ← t - 2#usize
            let i2 ← Std.Array.index_usize key i1
            ok (i2, ((role, key) : pqxdh.tag_x25519_key.closure))) := rfl

/-- The generated X25519 key encoding is the ideal `Tag_X`. -/
theorem tag_x25519_key_abs (role : Std.U8) (key : Std.Array Std.U8 32#usize) :
    ∃ a : Std.Array Std.U8 34#usize,
      pqxdh.tag_x25519_key role key = ok a ∧
        absBytes a = Pqxdh.tagX (absByte role) (absBytes key) := by
  have hlen : (Pqxdh.tagX (absByte role) (absBytes key)).length = (34#usize).val := by
    simp [Pqxdh.tagX]
  have hcall : ∀ i, i < (34#usize).val →
      pqxdh.tag_x25519_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut (role, key)
        ⟨BitVec.ofNat _ i⟩
        = ok ((if i = 0 then pqxdh.KEM_TYPE_X25519 else if i = 1 then role
                else key.val[i - 2]!), (role, key)) := by
    intro i hi
    rw [usize_val_34] at hi
    have hval : (⟨BitVec.ofNat _ i⟩ : Std.Usize).val = i := usize_mk_val i (by omega)
    have hlt1 : ((⟨BitVec.ofNat _ i⟩ : Std.Usize) < 1#usize) ↔ i < 1 := by
      rw [Std.UScalar.lt_equiv, hval, usize_val_1]
    have hlt2 : ((⟨BitVec.ofNat _ i⟩ : Std.Usize) < 2#usize) ↔ i < 2 := by
      rw [Std.UScalar.lt_equiv, hval, usize_val_2]
    rw [tag_x25519_call_mut]
    by_cases h0 : i = 0
    · subst h0
      rw [if_pos (hlt1.mpr (by omega))]
      simp
    · rw [if_neg (fun h => absurd (hlt1.mp h) (by omega)), if_neg h0]
      by_cases h1 : i = 1
      · subst h1
        rw [if_pos (hlt2.mpr (by omega))]
        simp
      · rw [if_neg (fun h => absurd (hlt2.mp h) (by omega)), if_neg h1]
        have hsub : (2#usize).val ≤ (⟨BitVec.ofNat _ i⟩ : Std.Usize).val := by
          rw [usize_val_2, hval]; omega
        rw [usize_sub_eq _ _ hsub]
        have h2 : (⟨BitVec.ofNat _ ((⟨BitVec.ofNat _ i⟩ : Std.Usize).val - (2#usize).val)⟩ :
            Std.Usize).val = i - 2 := by
          rw [hval, usize_val_2]
          exact usize_mk_val (i - 2) (by omega)
        simp only [bind_tc_ok]
        rw [index_usize_eq key _ (by rw [h2, usize_val_32]; omega), h2]
        simp
  have hbyte : ∀ i, i < (34#usize).val →
      absByte (if i = 0 then pqxdh.KEM_TYPE_X25519 else if i = 1 then role
                else key.val[i - 2]!)
        = (Pqxdh.tagX (absByte role) (absBytes key))[i]! := by
    intro i hi
    rw [usize_val_34] at hi
    match i with
    | 0 => simp [Pqxdh.tagX, absByte, pqxdh.KEM_TYPE_X25519]
    | 1 => simp [Pqxdh.tagX]
    | (j + 2) =>
      have hj : j < (32#usize).val := by rw [usize_val_32]; omega
      rw [if_neg (by omega), if_neg (by omega)]
      simp only [Nat.add_sub_cancel, Pqxdh.tagX, List.getElem!_cons_succ]
      exact (absBytes_getElem! key j hj).symm
  obtain ⟨a, ha, habs⟩ :=
    from_fn_absBytes (F := pqxdh.tag_x25519_key.closure) 34#usize
      pqxdh.tag_x25519_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 (role, key) _ _ hlen
      hcall hbyte
  exact ⟨a, by simpa [pqxdh.tag_x25519_key] using ha, habs⟩


/-! ## Splitting off the tag bytes -/

@[simp] theorem usize_val_0 : (0#usize).val = 0 := by scalar_tac

theorem absBytes_cons1 {n : Std.Usize} (a : Std.Array Std.U8 n) (h : 1 ≤ n.val) :
    absBytes a = absByte a.val[0]! :: (absBytes a).drop 1 := by
  have h0 : (absBytes a)[0]! = absByte a.val[0]! := absBytes_getElem! a 0 (by omega)
  rw [← h0]
  exact list_eq_cons_drop _ (by simp; omega)

theorem absBytes_cons2 {n : Std.Usize} (a : Std.Array Std.U8 n) (h : 2 ≤ n.val) :
    absBytes a = absByte a.val[0]! :: absByte a.val[1]! :: (absBytes a).drop 2 := by
  have e1 := absBytes_cons1 a (by omega)
  have e2 : (absBytes a).drop 1 = absByte a.val[1]! :: (absBytes a).drop 2 := by
    have hlen : 0 < ((absBytes a).drop 1).length := by rw [length_drop_absBytes]; omega
    have e := list_eq_cons_drop ((absBytes a).drop 1) hlen
    rw [List.drop_drop, getElem!_drop_absBytes a 1 0 (by omega)] at e
    simpa using e
  conv_lhs => rw [e1]
  rw [e2]

/-- A generated `from_fn` that reads its input shifted by `d` computes the dropped
suffix of the abstracted input. -/
theorem drop_from_fn {F : Type} {N M : Std.Usize}
    (inst : core.ops.function.FnMut F Std.Usize Std.U8) (f : F)
    (enc : Std.Array Std.U8 M) (d : ℕ) (hd : N.val + d = M.val)
    (h : ∀ i, i < N.val → inst.call_mut f ⟨BitVec.ofNat _ i⟩ = ok (enc.val[i + d]!, f)) :
    ∃ a : Std.Array Std.U8 N,
      core.array.from_fn N inst f = ok a ∧ absBytes a = (absBytes enc).drop d := by
  refine from_fn_absBytes N inst f (fun i => enc.val[i + d]!) _ ?_ h ?_
  · rw [length_drop_absBytes]; omega
  · intro i hi
    exact (getElem!_drop_absBytes enc d i (by omega)).symm

/-! ## Byte constants -/

@[simp] theorem absByte_sign_type : absByte pqxdh.SIGN_TYPE_ED25519 = 0x01 := by
  simp [absByte, pqxdh.SIGN_TYPE_ED25519]

@[simp] theorem absByte_kem_mlkem768 : absByte pqxdh.KEM_TYPE_MLKEM768 = 0x03 := by
  simp [absByte, pqxdh.KEM_TYPE_MLKEM768]

@[simp] theorem absByte_kem_x25519 : absByte pqxdh.KEM_TYPE_X25519 = 0x04 := by
  simp [absByte, pqxdh.KEM_TYPE_X25519]

/-! ## The generated parsers -/

/-- The generated `untag_sign_key` closure. -/
theorem untag_sign_call_mut (enc : Std.Array Std.U8 33#usize) (t : Std.Usize) :
    pqxdh.untag_sign_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
        (enc : pqxdh.untag_sign_key.closure) t
      = (t + 1#usize >>= fun i => Std.Array.index_usize enc i >>= fun i1 =>
          ok (i1, (enc : pqxdh.untag_sign_key.closure))) := rfl

/-- The generated `untag_mlkem768_key` closure. -/
theorem untag_mlkem768_call_mut (enc : Std.Array Std.U8 1185#usize) (t : Std.Usize) :
    pqxdh.untag_mlkem768_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
        (enc : pqxdh.untag_mlkem768_key.closure) t
      = (t + 1#usize >>= fun i => Std.Array.index_usize enc i >>= fun i1 =>
          ok (i1, (enc : pqxdh.untag_mlkem768_key.closure))) := rfl

/-- The generated `untag_x25519_key` closure. -/
theorem untag_x25519_call_mut (enc : Std.Array Std.U8 34#usize) (t : Std.Usize) :
    pqxdh.untag_x25519_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8.call_mut
        (enc : pqxdh.untag_x25519_key.closure) t
      = (t + 2#usize >>= fun i => Std.Array.index_usize enc i >>= fun i1 =>
          ok (i1, (enc : pqxdh.untag_x25519_key.closure))) := rfl

/-- The generated Ed25519 untagging is the ideal `parseSigTag`. -/
theorem untag_sign_key_abs (encoded : Std.Array Std.U8 33#usize) :
    (∃ k : Std.Array Std.U8 32#usize,
        pqxdh.untag_sign_key encoded = ok (core.option.Option.Some k) ∧
        Pqxdh.parseSigTag (absBytes encoded) = some (absBytes k)) ∨
      (pqxdh.untag_sign_key encoded = ok core.option.Option.None ∧
        Pqxdh.parseSigTag (absBytes encoded) = none) := by
  have hcons := absBytes_cons1 encoded (by simp)
  have hlen1 : ((absBytes encoded).drop 1).length = 32 := by
    rw [length_drop_absBytes]; simp
  have hunf : pqxdh.untag_sign_key encoded =
      (if encoded.val[0]! = pqxdh.SIGN_TYPE_ED25519 then
        (core.array.from_fn 32#usize
            pqxdh.untag_sign_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 encoded
          >>= fun key => ok (core.option.Option.Some key))
       else ok core.option.Option.None) := by
    unfold pqxdh.untag_sign_key
    rw [index_usize_eq encoded 0#usize (by simp)]
    simp only [bind_tc_ok, usize_val_0]
  by_cases h : encoded.val[0]! = pqxdh.SIGN_TYPE_ED25519
  · obtain ⟨a, ha, habs⟩ :=
      drop_from_fn (F := pqxdh.untag_sign_key.closure) (N := 32#usize)
        pqxdh.untag_sign_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 encoded encoded 1
        (by simp) (by
          intro i hi
          rw [usize_val_32] at hi
          have hval : (⟨BitVec.ofNat _ i⟩ : Std.Usize).val = i := usize_mk_val i (by omega)
          refine Eq.trans (untag_sign_call_mut encoded _) ?_
          obtain ⟨z, hz, hzv⟩ := usize_add_val ⟨BitVec.ofNat _ i⟩ 1#usize
            (by rw [hval, usize_val_1]; exact lt_numBits _ (by omega))
          have hzv' : z.val = i + 1 := by rw [hzv, hval, usize_val_1]
          rw [hz]
          simp only [bind_tc_ok]
          rw [index_usize_eq encoded z (by rw [hzv', usize_val_33]; omega), hzv']
          rfl)
    refine Or.inl ⟨a, by rw [hunf, if_pos h, ha]; rfl, ?_⟩
    rw [habs]
    conv_lhs => rw [hcons]
    rw [parseSigTag_cons, if_pos ⟨by rw [h]; simp, hlen1⟩]
  · refine Or.inr ⟨by rw [hunf, if_neg h], ?_⟩
    conv_lhs => rw [hcons]
    rw [parseSigTag_cons, if_neg]
    rintro ⟨hb, -⟩
    exact h (absByte_injective (by rw [hb]; simp))

/-- The generated ML-KEM-768 untagging is the ideal `parsePQTag`. -/
theorem untag_mlkem768_key_abs (encoded : Std.Array Std.U8 1185#usize) :
    (∃ k : Std.Array Std.U8 1184#usize,
        pqxdh.untag_mlkem768_key encoded = ok (core.option.Option.Some k) ∧
        Pqxdh.parsePQTag (absBytes encoded) = some (absBytes k)) ∨
      (pqxdh.untag_mlkem768_key encoded = ok core.option.Option.None ∧
        Pqxdh.parsePQTag (absBytes encoded) = none) := by
  have hcons := absBytes_cons1 encoded (by simp)
  have hlen1 : ((absBytes encoded).drop 1).length = 1184 := by
    rw [length_drop_absBytes]; simp
  have hunf : pqxdh.untag_mlkem768_key encoded =
      (if encoded.val[0]! = pqxdh.KEM_TYPE_MLKEM768 then
        (core.array.from_fn 1184#usize
            pqxdh.untag_mlkem768_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 encoded
          >>= fun key => ok (core.option.Option.Some key))
       else ok core.option.Option.None) := by
    unfold pqxdh.untag_mlkem768_key
    rw [index_usize_eq encoded 0#usize (by simp)]
    simp only [bind_tc_ok, usize_val_0]
  by_cases h : encoded.val[0]! = pqxdh.KEM_TYPE_MLKEM768
  · obtain ⟨a, ha, habs⟩ :=
      drop_from_fn (F := pqxdh.untag_mlkem768_key.closure) (N := 1184#usize)
        pqxdh.untag_mlkem768_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 encoded encoded 1
        (by simp) (by
          intro i hi
          rw [usize_val_1184] at hi
          have hval : (⟨BitVec.ofNat _ i⟩ : Std.Usize).val = i := usize_mk_val i (by omega)
          refine Eq.trans (untag_mlkem768_call_mut encoded _) ?_
          obtain ⟨z, hz, hzv⟩ := usize_add_val ⟨BitVec.ofNat _ i⟩ 1#usize
            (by rw [hval, usize_val_1]; exact lt_numBits _ (by omega))
          have hzv' : z.val = i + 1 := by rw [hzv, hval, usize_val_1]
          rw [hz]
          simp only [bind_tc_ok]
          rw [index_usize_eq encoded z (by rw [hzv', usize_val_1185]; omega), hzv']
          rfl)
    refine Or.inl ⟨a, by rw [hunf, if_pos h, ha]; rfl, ?_⟩
    rw [habs]
    conv_lhs => rw [hcons]
    rw [parsePQTag_cons, if_pos ⟨by rw [h]; simp, hlen1⟩]
  · refine Or.inr ⟨by rw [hunf, if_neg h], ?_⟩
    conv_lhs => rw [hcons]
    rw [parsePQTag_cons, if_neg]
    rintro ⟨hb, -⟩
    exact h (absByte_injective (by rw [hb]; simp))

/-- The generated X25519 untagging is the ideal `parseXTag`. -/
theorem untag_x25519_key_abs (encoded : Std.Array Std.U8 34#usize) (role : Std.U8) :
    (∃ k : Std.Array Std.U8 32#usize,
        pqxdh.untag_x25519_key encoded role = ok (core.option.Option.Some k) ∧
        Pqxdh.parseXTag (absByte role) (absBytes encoded) = some (absBytes k)) ∨
      (pqxdh.untag_x25519_key encoded role = ok core.option.Option.None ∧
        Pqxdh.parseXTag (absByte role) (absBytes encoded) = none) := by
  have hcons := absBytes_cons2 encoded (by simp)
  have hlen1 : ((absBytes encoded).drop 2).length = 32 := by
    rw [length_drop_absBytes]; simp
  have hunf : pqxdh.untag_x25519_key encoded role =
      (if encoded.val[0]! = pqxdh.KEM_TYPE_X25519 then
        (if encoded.val[1]! = role then
          (core.array.from_fn 32#usize
              pqxdh.untag_x25519_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 encoded
            >>= fun key => ok (core.option.Option.Some key))
         else ok core.option.Option.None)
       else ok core.option.Option.None) := by
    unfold pqxdh.untag_x25519_key
    rw [index_usize_eq encoded 0#usize (by simp)]
    simp only [bind_tc_ok, usize_val_0]
    by_cases h : encoded.val[0]! = pqxdh.KEM_TYPE_X25519
    · rw [if_pos h, if_pos h, index_usize_eq encoded 1#usize (by simp)]
      simp only [bind_tc_ok, usize_val_1]
    · rw [if_neg h, if_neg h]
  by_cases h : encoded.val[0]! = pqxdh.KEM_TYPE_X25519
  · by_cases h1 : encoded.val[1]! = role
    · obtain ⟨a, ha, habs⟩ :=
        drop_from_fn (F := pqxdh.untag_x25519_key.closure) (N := 32#usize)
          pqxdh.untag_x25519_key.closure.Insts.CoreOpsFunctionFnMutTupleUsizeU8 encoded encoded 2
          (by simp) (by
            intro i hi
            rw [usize_val_32] at hi
            have hval : (⟨BitVec.ofNat _ i⟩ : Std.Usize).val = i := usize_mk_val i (by omega)
            refine Eq.trans (untag_x25519_call_mut encoded _) ?_
            obtain ⟨z, hz, hzv⟩ := usize_add_val ⟨BitVec.ofNat _ i⟩ 2#usize
              (by rw [hval, usize_val_2]; exact lt_numBits _ (by omega))
            have hzv' : z.val = i + 2 := by rw [hzv, hval, usize_val_2]
            rw [hz]
            simp only [bind_tc_ok]
            rw [index_usize_eq encoded z (by rw [hzv', usize_val_34]; omega), hzv']
            rfl)
      refine Or.inl ⟨a, by rw [hunf, if_pos h, if_pos h1, ha]; rfl, ?_⟩
      rw [habs]
      conv_lhs => rw [hcons]
      rw [parseXTag_cons2, if_pos ⟨by rw [h]; simp, by rw [h1], hlen1⟩]
    · refine Or.inr ⟨by rw [hunf, if_pos h, if_neg h1], ?_⟩
      conv_lhs => rw [hcons]
      rw [parseXTag_cons2, if_neg]
      rintro ⟨-, hb, -⟩
      exact h1 (absByte_injective hb)
  · refine Or.inr ⟨by rw [hunf, if_neg h], ?_⟩
    conv_lhs => rw [hcons]
    rw [parseXTag_cons2, if_neg]
    rintro ⟨hb, -⟩
    exact h (absByte_injective (by rw [hb]; simp))

end PqxdhRefinement
