-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [beaconcrypt_core]: type definitions
import Aeneas
import CoreModels
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace beaconcrypt_core

/-- [beaconcrypt_core::commitment::CommitmentTranscript]
    Source: 'beaconcrypt-core/src/commitment.rs', lines 26:0-28:1
    Visibility: public -/
structure commitment.CommitmentTranscript where
  bytes : Array Std.U8 229#usize

/-- [beaconcrypt_core::commitment::build_commitment_transcript::closure]
    Source: 'beaconcrypt-core/src/commitment.rs', lines 66:37-80:5 -/
def commitment.build_commitment_transcript.closure :=
  Array Std.U8 32#usize × Array Std.U8 12#usize × Array Std.U8 153#usize ×
  Array Std.U8 16#usize × Array Std.U8 8#usize × Array Std.U8 8#usize

/-- [beaconcrypt_core::pqxdh::RegistrationError]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 76:0-84:1
    Visibility: public -/
@[discriminant isize]
inductive pqxdh.RegistrationError where
| IdentityMismatch : pqxdh.RegistrationError
| InvalidKeyEncoding : pqxdh.RegistrationError
| InvalidDhOutput : pqxdh.RegistrationError
| RegistrationReplay : pqxdh.RegistrationError
| KeyIdMismatch : pqxdh.RegistrationError
| KeyIdExhausted : pqxdh.RegistrationError
| KeyIdCollision : pqxdh.RegistrationError

/-- [beaconcrypt_core::pqxdh::ServerBinding]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 93:0-96:1
    Visibility: public -/
structure pqxdh.ServerBinding where
  identity_public_key : Array Std.U8 32#usize
  identity_key_id : Std.U64

/-- [beaconcrypt_core::pqxdh::BeaconStartInputs]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 101:0-105:1
    Visibility: public -/
structure pqxdh.BeaconStartInputs where
  identity_public_key : Array Std.U8 32#usize
  prekey_public_key : Array Std.U8 32#usize
  pq_public_key : Array Std.U8 1184#usize

/-- [beaconcrypt_core::pqxdh::BeaconCoins]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 110:0-112:1
    Visibility: public -/
structure pqxdh.BeaconCoins where
  one_time_public_key : Array Std.U8 32#usize

/-- [beaconcrypt_core::pqxdh::InitKex]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 122:0-127:1
    Visibility: public -/
structure pqxdh.InitKex where
  identity_key : Array Std.U8 33#usize
  prekey : Array Std.U8 34#usize
  one_time_key : Array Std.U8 34#usize
  pq_key : Array Std.U8 1185#usize

/-- [beaconcrypt_core::pqxdh::VerifiedInitKex]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 164:0-169:1
    Visibility: public -/
structure pqxdh.VerifiedInitKex where
  beacon_identity_public_key : Array Std.U8 32#usize
  beacon_prekey_public_key : Array Std.U8 32#usize
  beacon_one_time_public_key : Array Std.U8 32#usize
  beacon_pq_public_key : Array Std.U8 1184#usize

/-- [beaconcrypt_core::pqxdh::RegistrationId]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 223:0-225:1
    Visibility: public -/
structure pqxdh.RegistrationId where
  bytes : Array Std.U8 64#usize

/-- [beaconcrypt_core::pqxdh::{beaconcrypt_core::pqxdh::VerifiedInitKex}::registration_id::closure]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 193:69-199:9 -/
@[reducible]
def pqxdh.VerifiedInitKex.registration_id.closure := pqxdh.VerifiedInitKex

/-- [beaconcrypt_core::pqxdh::RegistrationStatus]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 237:0-240:1
    Visibility: public -/
@[discriminant isize]
inductive pqxdh.RegistrationStatus where
| Fresh : pqxdh.RegistrationStatus
| Consumed : pqxdh.RegistrationStatus

/-- [beaconcrypt_core::pqxdh::BeaconFresh]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 254:0-256:1
    Visibility: public -/
structure pqxdh.BeaconFresh where
  expected_server_binding : pqxdh.ServerBinding

/-- [beaconcrypt_core::pqxdh::BeaconInitSent]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 277:0-280:1
    Visibility: public -/
structure pqxdh.BeaconInitSent where
  expected_server_binding : pqxdh.ServerBinding
  beacon_identity_public_key : Array Std.U8 32#usize

/-- [beaconcrypt_core::pqxdh::BeaconStart]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 294:0-297:1
    Visibility: public -/
structure pqxdh.BeaconStart where
  state : pqxdh.BeaconInitSent
  message : pqxdh.InitKex

/-- [beaconcrypt_core::pqxdh::tag_mlkem768_key::closure]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 958:29-958:83 -/
@[reducible]
def pqxdh.tag_mlkem768_key.closure := Array Std.U8 1184#usize

/-- [beaconcrypt_core::pqxdh::tag_x25519_key::closure]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 944:76-952:5 -/
def pqxdh.tag_x25519_key.closure := Std.U8 × Array Std.U8 32#usize

/-- [beaconcrypt_core::pqxdh::tag_sign_key::closure]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 936:29-936:83 -/
@[reducible]
def pqxdh.tag_sign_key.closure := Array Std.U8 32#usize

/-- [beaconcrypt_core::pqxdh::untag_mlkem768_key::closure]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 989:67-989:85 -/
@[reducible]
def pqxdh.untag_mlkem768_key.closure := Array Std.U8 1185#usize

/-- [beaconcrypt_core::pqxdh::untag_x25519_key::closure]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 979:65-979:83 -/
@[reducible]
def pqxdh.untag_x25519_key.closure := Array Std.U8 34#usize

/-- [beaconcrypt_core::pqxdh::untag_sign_key::closure]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 968:63-968:81 -/
@[reducible]
def pqxdh.untag_sign_key.closure := Array Std.U8 33#usize

/-- [beaconcrypt_core::pqxdh::PqxdhSharedSecrets]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 345:0-351:1
    Visibility: public -/
structure pqxdh.PqxdhSharedSecrets where
  dh1 : Array Std.U8 32#usize
  dh2 : Array Std.U8 32#usize
  dh3 : Array Std.U8 32#usize
  dh4 : Array Std.U8 32#usize
  kem_shared_secret : Array Std.U8 32#usize

/-- [beaconcrypt_core::pqxdh::RootKeyInput]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 355:0-357:1
    Visibility: public -/
structure pqxdh.RootKeyInput where
  bytes : Array Std.U8 192#usize

/-- [beaconcrypt_core::pqxdh::build_root_key_input::closure]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 388:64-402:5 -/
@[reducible]
def pqxdh.build_root_key_input.closure := pqxdh.PqxdhSharedSecrets

/-- [beaconcrypt_core::pqxdh::RatchetInitialization]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 410:0-413:1
    Visibility: public -/
structure pqxdh.RatchetInitialization where
  send_offset : Std.U8
  receive_offset : Std.U8

/-- [beaconcrypt_core::ratchet::RatchetChain]
    Source: 'beaconcrypt-core/src/ratchet.rs', lines 69:0-71:1
    Visibility: public -/
structure ratchet.RatchetChain where
  bytes : Array Std.U8 32#usize

/-- [beaconcrypt_core::pqxdh::InitialRatchetChains]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 448:0-451:1
    Visibility: public -/
structure pqxdh.InitialRatchetChains where
  send_chain : ratchet.RatchetChain
  receive_chain : ratchet.RatchetChain

/-- [beaconcrypt_core::pqxdh::split_initial_ratchet_kdf_output::closure#1]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 473:37-473:71 -/
@[reducible]
def pqxdh.split_initial_ratchet_kdf_output.closure_1 := Array Std.U8 64#usize

/-- [beaconcrypt_core::pqxdh::split_initial_ratchet_kdf_output::closure]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 472:36-472:49 -/
@[reducible]
def pqxdh.split_initial_ratchet_kdf_output.closure := Array Std.U8 64#usize

/-- [beaconcrypt_core::pqxdh::BeaconRegistrationCandidate]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 492:0-497:1
    Visibility: public -/
structure pqxdh.BeaconRegistrationCandidate where
  server_binding : pqxdh.ServerBinding
  assigned_key_id : Std.U64
  root_key_input : pqxdh.RootKeyInput
  associated_data : Array Std.U8 153#usize

/-- [beaconcrypt_core::pqxdh::RegistrationKeyIdBinding]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 567:0-569:1
    Visibility: public -/
structure pqxdh.RegistrationKeyIdBinding where
  bytes : Array Std.U8 8#usize

/-- [beaconcrypt_core::pqxdh::BeaconFinishInputs]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 533:0-537:1
    Visibility: public -/
structure pqxdh.BeaconFinishInputs where
  response_server_identity : Array Std.U8 32#usize
  assigned_key_id : Std.U64
  shared_secrets : pqxdh.PqxdhSharedSecrets

/-- [beaconcrypt_core::pqxdh::build_associated_data::closure]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 920:66-930:5 -/
def pqxdh.build_associated_data.closure :=
  Array Std.U8 33#usize × Array Std.U8 33#usize

/-- [beaconcrypt_core::pqxdh::AuthenticatedBeaconRegistration]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 594:0-596:1
    Visibility: public -/
structure pqxdh.AuthenticatedBeaconRegistration where
  candidate : pqxdh.BeaconRegistrationCandidate

/-- [beaconcrypt_core::pqxdh::BeaconEstablished]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 630:0-633:1
    Visibility: public -/
structure pqxdh.BeaconEstablished where
  server_binding : pqxdh.ServerBinding
  assigned_key_id : Std.U64

/-- [beaconcrypt_core::pqxdh::BeaconAborted]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 651:0-653:1
    Visibility: public -/
structure pqxdh.BeaconAborted where
  server_key_id : Std.U64

/-- [beaconcrypt_core::pqxdh::ServerState]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 694:0-696:1
    Visibility: public -/
structure pqxdh.ServerState where
  last_key_id : Std.U64

/-- [beaconcrypt_core::pqxdh::ServerCoins]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 711:0-714:1
    Visibility: public -/
structure pqxdh.ServerCoins where
  ephemeral_public_key : Array Std.U8 32#usize
  kem_ciphertext : Array Std.U8 1088#usize

/-- [beaconcrypt_core::pqxdh::PendingServerRegistration]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 718:0-725:1
    Visibility: public -/
structure pqxdh.PendingServerRegistration where
  server_binding : pqxdh.ServerBinding
  registration_id : pqxdh.RegistrationId
  beacon_identity_public_key : Array Std.U8 32#usize
  ephemeral_public_key : Array Std.U8 32#usize
  kem_ciphertext : Array Std.U8 1088#usize
  root_key_input : pqxdh.RootKeyInput

/-- [beaconcrypt_core::pqxdh::ServerRegistrationCandidate]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 778:0-788:1
    Visibility: public -/
structure pqxdh.ServerRegistrationCandidate where
  previous_state : pqxdh.ServerState
  next_state : pqxdh.ServerState
  key_id : Std.U64
  beacon_identity_public_key : Array Std.U8 32#usize
  server_identity_public_key : Array Std.U8 32#usize
  server_identity_key_id : Std.U64
  ephemeral_public_key : Array Std.U8 32#usize
  kem_ciphertext : Array Std.U8 1088#usize
  associated_data : Array Std.U8 153#usize

/-- [beaconcrypt_core::pqxdh::KeyIdAvailability]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 830:0-833:1
    Visibility: public -/
@[discriminant isize]
inductive pqxdh.KeyIdAvailability where
| Available : pqxdh.KeyIdAvailability
| Occupied : pqxdh.KeyIdAvailability

/-- [beaconcrypt_core::pqxdh::EstablishedPeer]
    Source: 'beaconcrypt-core/src/pqxdh.rs', lines 884:0-888:1
    Visibility: public -/
structure pqxdh.EstablishedPeer where
  key_id : Std.U64
  identity_public_key : Array Std.U8 32#usize
  associated_data : Array Std.U8 153#usize

/-- [beaconcrypt_core::ratchet::control::SequenceCache]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 15:0-18:1
    Visibility: public -/
structure ratchet.control.SequenceCache where
  entries : Array Std.U64 50#usize
  len : Std.U8

/-- [beaconcrypt_core::ratchet::control::RatchetState]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 61:0-65:1
    Visibility: public -/
structure ratchet.control.RatchetState where
  send_sequence : Std.U64
  receive_sequence : Std.U64
  receive_cache : ratchet.control.SequenceCache

/-- [beaconcrypt_core::ratchet::control::SendKey]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 109:0-112:1
    Visibility: public -/
structure ratchet.control.SendKey where
  sequence : Std.U64
  available : Bool

/-- [beaconcrypt_core::ratchet::control::SendAdvance]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 138:0-142:1
    Visibility: public -/
structure ratchet.control.SendAdvance where
  state : ratchet.control.RatchetState
  sequence : core.option.Option Std.U64
  key : ratchet.control.SendKey

/-- [beaconcrypt_core::ratchet::control::SendFinish]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 176:0-179:1
    Visibility: public -/
structure ratchet.control.SendFinish where
  key : ratchet.control.SendKey
  consumed : Bool

/-- [beaconcrypt_core::ratchet::control::ReceivePlan]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 209:0-212:1
    Visibility: public -/
structure ratchet.control.ReceivePlan where
  sequence : core.option.Option Std.U64
  derivations : Std.U64

/-- [beaconcrypt_core::ratchet::control::ReceiveAdvance]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 242:0-246:1
    Visibility: public -/
structure ratchet.control.ReceiveAdvance where
  state : ratchet.control.RatchetState
  sequence : core.option.Option Std.U64
  slot : core.option.Option Std.U8

/-- [beaconcrypt_core::ratchet::control::ReceiveDisposition]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 285:0-292:1
    Visibility: public -/
@[discriminant isize]
inductive ratchet.control.ReceiveDisposition where
| Missing : ratchet.control.ReceiveDisposition
| Retained : ratchet.control.ReceiveDisposition
| Consumed : ratchet.control.ReceiveDisposition

/-- [beaconcrypt_core::ratchet::control::ReceiveFinish]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 297:0-300:1
    Visibility: public -/
structure ratchet.control.ReceiveFinish where
  state : ratchet.control.RatchetState
  disposition : ratchet.control.ReceiveDisposition

/-- [beaconcrypt_core::ratchet::control::ReceiveRemoval]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 305:0-310:1
    Visibility: public -/
structure ratchet.control.ReceiveRemoval where
  target_slot : Std.U8
  last_slot : Std.U8

/-- [beaconcrypt_core::ratchet::control::ReceiveFinishWithRemoval]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 315:0-319:1
    Visibility: public -/
structure ratchet.control.ReceiveFinishWithRemoval where
  state : ratchet.control.RatchetState
  disposition : ratchet.control.ReceiveDisposition
  removal : core.option.Option ratchet.control.ReceiveRemoval

/-- [beaconcrypt_core::ratchet::control::RatchetRestore]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 429:0-432:1
    Visibility: public -/
structure ratchet.control.RatchetRestore where
  state : ratchet.control.RatchetState
  last_sequence : Std.U64

/-- [beaconcrypt_core::ratchet::control::ReceiveRestoreStep]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 444:0-447:1
    Visibility: public -/
structure ratchet.control.ReceiveRestoreStep where
  restore : ratchet.control.RatchetRestore
  slot : Std.U8

/-- [beaconcrypt_core::ratchet::control::restore_receive_key::closure]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 478:57-478:76 -/
@[reducible]
def ratchet.control.restore_receive_key.closure := Unit

/-- [beaconcrypt_core::ratchet::control::PeerRatchetState]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 487:0-490:1
    Visibility: public -/
structure ratchet.control.PeerRatchetState where
  peer_id : Std.U64
  ratchet : ratchet.control.RatchetState

/-- [beaconcrypt_core::ratchet::control::PeerSendAdvance]
    Source: 'beaconcrypt-core/src/ratchet/control.rs', lines 514:0-518:1
    Visibility: public -/
structure ratchet.control.PeerSendAdvance where
  peer : ratchet.control.PeerRatchetState
  sequence : core.option.Option Std.U64
  key : ratchet.control.SendKey

/-- [beaconcrypt_core::ratchet::RatchetKey]
    Source: 'beaconcrypt-core/src/ratchet.rs', lines 89:0-91:1
    Visibility: public -/
structure ratchet.RatchetKey where
  bytes : Array Std.U8 32#usize

/-- [beaconcrypt_core::ratchet::RatchetNonce]
    Source: 'beaconcrypt-core/src/ratchet.rs', lines 109:0-111:1
    Visibility: public -/
structure ratchet.RatchetNonce where
  bytes : Array Std.U8 12#usize

/-- [beaconcrypt_core::ratchet::RatchetMaterial]
    Source: 'beaconcrypt-core/src/ratchet.rs', lines 129:0-132:1
    Visibility: public -/
structure ratchet.RatchetMaterial where
  key : ratchet.RatchetKey
  nonce : ratchet.RatchetNonce

/-- [beaconcrypt_core::ratchet::SymmetricRatchetKdfRequest]
    Source: 'beaconcrypt-core/src/ratchet.rs', lines 163:0-166:1
    Visibility: public -/
structure ratchet.SymmetricRatchetKdfRequest where
  input : Array Std.U8 32#usize
  info : Array Std.U8 41#usize

/-- [beaconcrypt_core::ratchet::RatchetKdfOutput]
    Source: 'beaconcrypt-core/src/ratchet.rs', lines 186:0-190:1
    Visibility: public -/
structure ratchet.RatchetKdfOutput where
  key : ratchet.RatchetKey
  next_chain : ratchet.RatchetChain
  nonce : ratchet.RatchetNonce

/-- [beaconcrypt_core::ratchet::split_ratchet_kdf_output::closure#2]
    Source: 'beaconcrypt-core/src/ratchet.rs', lines 213:29-213:98 -/
@[reducible]
def ratchet.split_ratchet_kdf_output.closure_2 := Array Std.U8 76#usize

/-- [beaconcrypt_core::ratchet::split_ratchet_kdf_output::closure#1]
    Source: 'beaconcrypt-core/src/ratchet.rs', lines 210:42-210:90 -/
@[reducible]
def ratchet.split_ratchet_kdf_output.closure_1 := Array Std.U8 76#usize

/-- [beaconcrypt_core::ratchet::split_ratchet_kdf_output::closure]
    Source: 'beaconcrypt-core/src/ratchet.rs', lines 208:35-208:48 -/
@[reducible]
def ratchet.split_ratchet_kdf_output.closure := Array Std.U8 76#usize

end beaconcrypt_core
