# This workflow builds and uploads a Python package to PyPI when a tag is pushed.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - "**"

permissions:
  contents: read

jobs:
  sdist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Set up Python
        run: uv python install 3.14
      - name: Install deps
        run: uv sync
      - name: Install cap'n proto
        run: |
          sudo apt install capnproto

      - name: Build source distribution
        run: uv run maturin sdist --out dist

      - name: Upload source distribution
        uses: actions/upload-artifact@v4
        with:
          name: release-sdist
          path: dist/

  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Set up Python
        run: uv python install 3.14

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.0
        with:
          output-dir: dist/

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: release-wheels-${{ matrix.os }}
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - sdist
      - wheels
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: pypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      # url: https://pypi.org/p/YOURPROJECT
      url: https://pypi.org/project/beaconcrypt/${{ github.ref_name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          pattern: release-*
          path: dist/
          merge-multiple: true

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
