name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7
    - name: Install cap'n proto
      run: sudo apt update && sudo apt install capnproto
    - name: Build
      run: cargo build --verbose
    - name: Check PQXDH server build
      run: cargo check --no-default-features --features pqxdh,server --lib
    - name: Check PQXDH beacon build
      run: cargo check --no-default-features --features pqxdh,beacon --lib
    - name: Run tests
      run: cargo test --verbose
