// SPDX-License-Identifier: 0BSD

//! Pure PQXDH composition and registration typestates.
//!
//! Cryptographic primitives, entropy acquisition, wire parsing, and storage
//! remain in the production adapter. This module owns the deterministic
//! buffers and state transitions that connect those operations.

pub const SIGN_PUBLIC_KEY_SIZE: usize = 32;
pub const X25519_PUBLIC_KEY_SIZE: usize = 32;
pub const MLKEM768_PUBLIC_KEY_SIZE: usize = 1_184;
pub const MLKEM768_CIPHERTEXT_SIZE: usize = 1_088;
pub const SHARED_SECRET_SIZE: usize = 32;
pub const DH_SECRET_SIZE: usize = 32;
pub const PQXDH_PADDING_SIZE: usize = 32;
pub const RATCHET_CHAIN_SIZE: usize = 32;

pub const SIGN_TYPE_ED25519: u8 = 1;
pub const KEM_TYPE_MLKEM768: u8 = 3;
pub const KEM_TYPE_X25519: u8 = 4;

pub const ENCODED_SIGN_PUBLIC_KEY_SIZE: usize = SIGN_PUBLIC_KEY_SIZE + 1;
pub const ENCODED_X25519_PUBLIC_KEY_SIZE: usize = X25519_PUBLIC_KEY_SIZE + 1;
pub const ENCODED_MLKEM768_PUBLIC_KEY_SIZE: usize = MLKEM768_PUBLIC_KEY_SIZE + 1;

// https://signal.org/docs/specifications/pqxdh/#pqxdh-parameters
pub const PQXDH_INFO: &[u8; 46] = b"BeaconcryptPqxdh_CURVE25519_SHA-512_ML-KEM-768";
pub const SYM_RATCHET_INFO: &[u8; 41] = b"SymRatchet_HKDF_SHA-512_CHACHA20_POLY1305";

pub const ROOT_KEY_INPUT_SIZE: usize =
	PQXDH_PADDING_SIZE + (4 * DH_SECRET_SIZE) + SHARED_SECRET_SIZE;
pub const ASSOCIATED_DATA_SIZE: usize =
	(2 * ENCODED_SIGN_PUBLIC_KEY_SIZE) + PQXDH_INFO.len() + SYM_RATCHET_INFO.len();

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RegistrationError {
	IdentityMismatch,
	InvalidKeyEncoding,
	InvalidDhOutput,
}

/// Public material generated by the beacon adapter before registration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconStartInputs {
	pub identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	pub prekey_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	pub pq_public_key: [u8; MLKEM768_PUBLIC_KEY_SIZE],
}

/// Per-registration randomness generated by the beacon adapter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconCoins {
	pub one_time_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
}

/// The deterministic, unsigned payloads of an InitKex message.
///
/// The adapter signs `prekey`, `one_time_key`, and `pq_key`, then places the
/// resulting signed buffers and `identity_key` into Cap'n Proto.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct InitKex {
	identity_key: [u8; ENCODED_SIGN_PUBLIC_KEY_SIZE],
	prekey: [u8; ENCODED_X25519_PUBLIC_KEY_SIZE],
	one_time_key: [u8; ENCODED_X25519_PUBLIC_KEY_SIZE],
	pq_key: [u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE],
}

impl InitKex {
	pub const fn from_encoded(
		identity_key: [u8; ENCODED_SIGN_PUBLIC_KEY_SIZE],
		prekey: [u8; ENCODED_X25519_PUBLIC_KEY_SIZE],
		one_time_key: [u8; ENCODED_X25519_PUBLIC_KEY_SIZE],
		pq_key: [u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE],
	) -> Self {
		Self {
			identity_key,
			prekey,
			one_time_key,
			pq_key,
		}
	}

	pub const fn identity_key(&self) -> &[u8; ENCODED_SIGN_PUBLIC_KEY_SIZE] {
		&self.identity_key
	}

	pub const fn prekey(&self) -> &[u8; ENCODED_X25519_PUBLIC_KEY_SIZE] {
		&self.prekey
	}

	pub const fn one_time_key(&self) -> &[u8; ENCODED_X25519_PUBLIC_KEY_SIZE] {
		&self.one_time_key
	}

	pub const fn pq_key(&self) -> &[u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE] {
		&self.pq_key
	}
}

/// Signature-checked and type-checked InitKex public keys.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct VerifiedInitKex {
	beacon_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	beacon_prekey_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	beacon_one_time_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	beacon_pq_public_key: [u8; MLKEM768_PUBLIC_KEY_SIZE],
}

impl VerifiedInitKex {
	pub const fn beacon_identity_public_key(&self) -> &[u8; SIGN_PUBLIC_KEY_SIZE] {
		&self.beacon_identity_public_key
	}

	pub const fn beacon_prekey_public_key(&self) -> &[u8; X25519_PUBLIC_KEY_SIZE] {
		&self.beacon_prekey_public_key
	}

	pub const fn beacon_one_time_public_key(&self) -> &[u8; X25519_PUBLIC_KEY_SIZE] {
		&self.beacon_one_time_public_key
	}

	pub const fn beacon_pq_public_key(&self) -> &[u8; MLKEM768_PUBLIC_KEY_SIZE] {
		&self.beacon_pq_public_key
	}
}

/// Fresh beacon state. Calling [`beacon_start`] consumes this state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconFresh {
	server_key_id: u64,
}

impl BeaconFresh {
	pub const fn new(server_key_id: u64) -> Self {
		Self { server_key_id }
	}

	pub const fn server_key_id(&self) -> u64 {
		self.server_key_id
	}
}

/// Beacon state tied to exactly one emitted InitKex.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconInitSent {
	server_key_id: u64,
	beacon_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
}

impl BeaconInitSent {
	pub const fn server_key_id(&self) -> u64 {
		self.server_key_id
	}
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconStart {
	pub state: BeaconInitSent,
	pub message: InitKex,
}

/// Construct the exact tagged InitKex payloads from explicit generated
/// material and advance the beacon to its single pending registration.
pub fn beacon_start(
	state: BeaconFresh,
	inputs: BeaconStartInputs,
	coins: BeaconCoins,
) -> BeaconStart {
	BeaconStart {
		state: BeaconInitSent {
			server_key_id: state.server_key_id,
			beacon_identity_public_key: inputs.identity_public_key,
		},
		message: InitKex {
			identity_key: tag_sign_key(inputs.identity_public_key),
			prekey: tag_x25519_key(inputs.prekey_public_key),
			one_time_key: tag_x25519_key(coins.one_time_public_key),
			pq_key: tag_mlkem768_key(inputs.pq_public_key),
		},
	}
}

/// Re-establish typed, verified registration keys after signature checks in
/// the adapter. Incorrect or non-disjoint algorithm tags are rejected here.
pub fn validate_init_kex(message: InitKex) -> Result<VerifiedInitKex, RegistrationError> {
	let Some(identity) = untag_sign_key(message.identity_key) else {
		return Err(RegistrationError::InvalidKeyEncoding);
	};
	let Some(prekey) = untag_x25519_key(message.prekey) else {
		return Err(RegistrationError::InvalidKeyEncoding);
	};
	let Some(one_time) = untag_x25519_key(message.one_time_key) else {
		return Err(RegistrationError::InvalidKeyEncoding);
	};
	let Some(pq) = untag_mlkem768_key(message.pq_key) else {
		return Err(RegistrationError::InvalidKeyEncoding);
	};

	Ok(VerifiedInitKex {
		beacon_identity_public_key: identity,
		beacon_prekey_public_key: prekey,
		beacon_one_time_public_key: one_time,
		beacon_pq_public_key: pq,
	})
}

/// Four classical DH results followed by the post-quantum KEM secret.
pub struct PqxdhSharedSecrets {
	pub dh1: [u8; DH_SECRET_SIZE],
	pub dh2: [u8; DH_SECRET_SIZE],
	pub dh3: [u8; DH_SECRET_SIZE],
	pub dh4: [u8; DH_SECRET_SIZE],
	pub kem_shared_secret: [u8; SHARED_SECRET_SIZE],
}

/// Exact `Padding || DH1 || DH2 || DH3 || DH4 || SS` input to the opaque
/// PQXDH HKDF operation.
pub struct RootKeyInput {
	bytes: [u8; ROOT_KEY_INPUT_SIZE],
}

impl RootKeyInput {
	pub const fn as_bytes(&self) -> &[u8; ROOT_KEY_INPUT_SIZE] {
		&self.bytes
	}

	/// Mutable access is reserved for the production adapter's zeroization of
	/// the concrete transcript immediately after the opaque HKDF call.
	pub fn as_mut_bytes(&mut self) -> &mut [u8; ROOT_KEY_INPUT_SIZE] {
		&mut self.bytes
	}
}

pub fn build_root_key_input(
	secrets: &PqxdhSharedSecrets,
) -> Result<RootKeyInput, RegistrationError> {
	if is_all_zero(&secrets.dh1)
		|| is_all_zero(&secrets.dh2)
		|| is_all_zero(&secrets.dh3)
		|| is_all_zero(&secrets.dh4)
	{
		return Err(RegistrationError::InvalidDhOutput);
	}

	let mut bytes = [0xff; ROOT_KEY_INPUT_SIZE];
	let mut offset = PQXDH_PADDING_SIZE;
	copy_32(&mut bytes, offset, &secrets.dh1);
	offset += DH_SECRET_SIZE;
	copy_32(&mut bytes, offset, &secrets.dh2);
	offset += DH_SECRET_SIZE;
	copy_32(&mut bytes, offset, &secrets.dh3);
	offset += DH_SECRET_SIZE;
	copy_32(&mut bytes, offset, &secrets.dh4);
	offset += DH_SECRET_SIZE;
	copy_32(&mut bytes, offset, &secrets.kem_shared_secret);
	Ok(RootKeyInput { bytes })
}

/// The core-owned direction plan for splitting the opaque 64-byte ratchet
/// KDF result. Offsets are bytes into `LHS || RHS`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RatchetInitialization {
	send_offset: u8,
	receive_offset: u8,
}

impl RatchetInitialization {
	pub const fn send_offset(&self) -> u8 {
		self.send_offset
	}

	pub const fn receive_offset(&self) -> u8 {
		self.receive_offset
	}
}

const BEACON_RATCHETS: RatchetInitialization = RatchetInitialization {
	send_offset: RATCHET_CHAIN_SIZE as u8,
	receive_offset: 0,
};
const SERVER_RATCHETS: RatchetInitialization = RatchetInitialization {
	send_offset: 0,
	receive_offset: RATCHET_CHAIN_SIZE as u8,
};

/// Test and adapter utility for non-handshake ratchet fixtures. Production
/// PQXDH code obtains the same plan from a beacon candidate typestate.
pub const fn beacon_ratchet_initialization() -> RatchetInitialization {
	BEACON_RATCHETS
}

/// Test and adapter utility for non-handshake ratchet fixtures. Production
/// PQXDH code obtains the same plan from a server candidate typestate.
pub const fn server_ratchet_initialization() -> RatchetInitialization {
	SERVER_RATCHETS
}

/// Candidate beacon session. Its root, AD, identity assignment, and ratchet
/// direction have been validated, but its initial ciphertext has not yet
/// authenticated. It must be consumed by [`beacon_commit`] or
/// [`beacon_abort_candidate`].
pub struct BeaconRegistrationCandidate {
	server_key_id: u64,
	assigned_key_id: u64,
	root_key_input: RootKeyInput,
	associated_data: [u8; ASSOCIATED_DATA_SIZE],
}

impl BeaconRegistrationCandidate {
	pub const fn server_key_id(&self) -> u64 {
		self.server_key_id
	}

	pub const fn assigned_key_id(&self) -> u64 {
		self.assigned_key_id
	}

	pub const fn root_key_input(&self) -> &RootKeyInput {
		&self.root_key_input
	}

	pub fn root_key_input_mut(&mut self) -> &mut RootKeyInput {
		&mut self.root_key_input
	}

	pub const fn associated_data(&self) -> &[u8; ASSOCIATED_DATA_SIZE] {
		&self.associated_data
	}

	pub const fn ratchet_initialization(&self) -> RatchetInitialization {
		BEACON_RATCHETS
	}
}

pub struct BeaconFinishInputs {
	pub expected_server_identity: [u8; SIGN_PUBLIC_KEY_SIZE],
	pub response_server_identity: [u8; SIGN_PUBLIC_KEY_SIZE],
	pub assigned_key_id: u64,
	pub shared_secrets: PqxdhSharedSecrets,
}

pub fn beacon_prepare_finish(
	state: BeaconInitSent,
	inputs: &BeaconFinishInputs,
) -> Result<BeaconRegistrationCandidate, RegistrationError> {
	if inputs.expected_server_identity != inputs.response_server_identity {
		return Err(RegistrationError::IdentityMismatch);
	}
	let root_key_input = build_root_key_input(&inputs.shared_secrets)?;
	let associated_data = build_associated_data(
		inputs.response_server_identity,
		state.beacon_identity_public_key,
	);
	Ok(BeaconRegistrationCandidate {
		server_key_id: state.server_key_id,
		assigned_key_id: inputs.assigned_key_id,
		root_key_input,
		associated_data,
	})
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconEstablished {
	server_key_id: u64,
	assigned_key_id: u64,
}

impl BeaconEstablished {
	pub const fn server_key_id(&self) -> u64 {
		self.server_key_id
	}

	pub const fn assigned_key_id(&self) -> u64 {
		self.assigned_key_id
	}
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconAborted {
	server_key_id: u64,
}

impl BeaconAborted {
	pub const fn new(server_key_id: u64) -> Self {
		Self { server_key_id }
	}

	pub const fn server_key_id(&self) -> u64 {
		self.server_key_id
	}
}

pub const fn beacon_commit(candidate: BeaconRegistrationCandidate) -> BeaconEstablished {
	BeaconEstablished {
		server_key_id: candidate.server_key_id,
		assigned_key_id: candidate.assigned_key_id,
	}
}

pub const fn beacon_abort_candidate(candidate: BeaconRegistrationCandidate) -> BeaconAborted {
	BeaconAborted {
		server_key_id: candidate.server_key_id,
	}
}

pub const fn beacon_abort_init(state: BeaconInitSent) -> BeaconAborted {
	BeaconAborted {
		server_key_id: state.server_key_id,
	}
}

pub const fn beacon_abort_fresh(state: BeaconFresh) -> BeaconAborted {
	BeaconAborted {
		server_key_id: state.server_key_id,
	}
}

/// Active server state. Pending registrations do not mutate it.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ServerState {
	last_key_id: u64,
}

impl ServerState {
	pub const fn new(last_key_id: u64) -> Self {
		Self { last_key_id }
	}

	pub const fn last_key_id(&self) -> u64 {
		self.last_key_id
	}
}

/// Explicit ephemeral/KEM outputs generated by the server adapter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ServerCoins {
	pub ephemeral_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	pub kem_ciphertext: [u8; MLKEM768_CIPHERTEXT_SIZE],
}

/// Stable identity of the server adapter that accepted a registration.
///
/// Pending registration tokens are checked against this binding before they
/// can prepare a commit, preventing a token created by one server instance
/// from mutating a differently identified server.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ServerBinding {
	pub identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	pub identity_key_id: u64,
}

/// Registration material that has passed parsing, signatures, key tags, DH
/// validation, and transcript construction but has not changed server state.
pub struct PendingServerRegistration {
	server_binding: ServerBinding,
	beacon_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	ephemeral_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	kem_ciphertext: [u8; MLKEM768_CIPHERTEXT_SIZE],
	root_key_input: RootKeyInput,
}

impl PendingServerRegistration {
	pub const fn beacon_identity_public_key(&self) -> &[u8; SIGN_PUBLIC_KEY_SIZE] {
		&self.beacon_identity_public_key
	}

	pub const fn root_key_input(&self) -> &RootKeyInput {
		&self.root_key_input
	}

	pub fn root_key_input_mut(&mut self) -> &mut RootKeyInput {
		&mut self.root_key_input
	}
}

/// Accept a verified InitKex without committing any peer or counter state.
pub fn server_accept(
	state: ServerState,
	registration: VerifiedInitKex,
	server_binding: ServerBinding,
	coins: ServerCoins,
	shared_secrets: &PqxdhSharedSecrets,
) -> Result<(ServerState, PendingServerRegistration), RegistrationError> {
	let root_key_input = build_root_key_input(shared_secrets)?;
	Ok((
		state,
		PendingServerRegistration {
			server_binding,
			beacon_identity_public_key: registration.beacon_identity_public_key,
			ephemeral_public_key: coins.ephemeral_public_key,
			kem_ciphertext: coins.kem_ciphertext,
			root_key_input,
		},
	))
}

/// Candidate server commit. The adapter must initialize a fresh ratchet,
/// encrypt the initial message, and serialize the response before consuming it
/// with [`server_commit`]. Dropping it leaves the active server unchanged.
pub struct ServerRegistrationCandidate {
	previous_state: ServerState,
	next_state: ServerState,
	key_id: u64,
	beacon_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	server_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	server_identity_key_id: u64,
	ephemeral_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	kem_ciphertext: [u8; MLKEM768_CIPHERTEXT_SIZE],
	associated_data: [u8; ASSOCIATED_DATA_SIZE],
}

impl ServerRegistrationCandidate {
	pub const fn key_id(&self) -> u64 {
		self.key_id
	}

	pub const fn beacon_identity_public_key(&self) -> &[u8; SIGN_PUBLIC_KEY_SIZE] {
		&self.beacon_identity_public_key
	}

	pub const fn server_identity_public_key(&self) -> &[u8; SIGN_PUBLIC_KEY_SIZE] {
		&self.server_identity_public_key
	}

	pub const fn server_identity_key_id(&self) -> u64 {
		self.server_identity_key_id
	}

	pub const fn ephemeral_public_key(&self) -> &[u8; X25519_PUBLIC_KEY_SIZE] {
		&self.ephemeral_public_key
	}

	pub const fn kem_ciphertext(&self) -> &[u8; MLKEM768_CIPHERTEXT_SIZE] {
		&self.kem_ciphertext
	}

	pub const fn associated_data(&self) -> &[u8; ASSOCIATED_DATA_SIZE] {
		&self.associated_data
	}

	pub const fn ratchet_initialization(&self) -> RatchetInitialization {
		SERVER_RATCHETS
	}
}

/// Prepare the next server key ID using the current Stage-4 allocation rule.
/// Collision-safe checked allocation remains a Stage-5 obligation.
pub fn server_prepare_commit(
	state: ServerState,
	pending: PendingServerRegistration,
	current_server_binding: ServerBinding,
) -> Result<ServerRegistrationCandidate, RegistrationError> {
	if pending.server_binding != current_server_binding {
		return Err(RegistrationError::IdentityMismatch);
	}
	let key_id = state.last_key_id.wrapping_add(1);
	Ok(ServerRegistrationCandidate {
		previous_state: state,
		next_state: ServerState {
			last_key_id: key_id,
		},
		key_id,
		beacon_identity_public_key: pending.beacon_identity_public_key,
		server_identity_public_key: current_server_binding.identity_public_key,
		server_identity_key_id: current_server_binding.identity_key_id,
		ephemeral_public_key: pending.ephemeral_public_key,
		kem_ciphertext: pending.kem_ciphertext,
		associated_data: build_associated_data(
			current_server_binding.identity_public_key,
			pending.beacon_identity_public_key,
		),
	})
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EstablishedPeer {
	pub key_id: u64,
	pub identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	pub associated_data: [u8; ASSOCIATED_DATA_SIZE],
}

pub fn server_commit(candidate: ServerRegistrationCandidate) -> (ServerState, EstablishedPeer) {
	(
		candidate.next_state,
		EstablishedPeer {
			key_id: candidate.key_id,
			identity_public_key: candidate.beacon_identity_public_key,
			associated_data: candidate.associated_data,
		},
	)
}

pub const fn server_abort_candidate(candidate: &ServerRegistrationCandidate) -> ServerState {
	candidate.previous_state
}

/// Associated data is always encoded server identity first, beacon identity
/// second, then the key-exchange and ratchet domain-separation strings.
pub fn build_associated_data(
	server_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	beacon_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
) -> [u8; ASSOCIATED_DATA_SIZE] {
	let encoded_server = tag_sign_key(server_identity_public_key);
	let encoded_beacon = tag_sign_key(beacon_identity_public_key);
	let mut output = [0; ASSOCIATED_DATA_SIZE];
	let mut offset = 0;
	copy_associated_data(&mut output, offset, &encoded_server);
	offset += ENCODED_SIGN_PUBLIC_KEY_SIZE;
	copy_associated_data(&mut output, offset, &encoded_beacon);
	offset += ENCODED_SIGN_PUBLIC_KEY_SIZE;
	copy_associated_data(&mut output, offset, PQXDH_INFO);
	offset += PQXDH_INFO.len();
	copy_associated_data(&mut output, offset, SYM_RATCHET_INFO);
	output
}

fn tag_sign_key(key: [u8; SIGN_PUBLIC_KEY_SIZE]) -> [u8; ENCODED_SIGN_PUBLIC_KEY_SIZE] {
	let mut output = [0; ENCODED_SIGN_PUBLIC_KEY_SIZE];
	output[0] = SIGN_TYPE_ED25519;
	copy_32_to_encoded(&mut output, &key);
	output
}

fn tag_x25519_key(key: [u8; X25519_PUBLIC_KEY_SIZE]) -> [u8; ENCODED_X25519_PUBLIC_KEY_SIZE] {
	let mut output = [0; ENCODED_X25519_PUBLIC_KEY_SIZE];
	output[0] = KEM_TYPE_X25519;
	copy_32_to_encoded(&mut output, &key);
	output
}

fn tag_mlkem768_key(key: [u8; MLKEM768_PUBLIC_KEY_SIZE]) -> [u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE] {
	let mut output = [0; ENCODED_MLKEM768_PUBLIC_KEY_SIZE];
	output[0] = KEM_TYPE_MLKEM768;
	copy_mlkem768_to_encoded(&mut output, &key);
	output
}

fn untag_sign_key(
	encoded: [u8; ENCODED_SIGN_PUBLIC_KEY_SIZE],
) -> Option<[u8; SIGN_PUBLIC_KEY_SIZE]> {
	if encoded[0] != SIGN_TYPE_ED25519 {
		return None;
	}
	let mut key = [0; SIGN_PUBLIC_KEY_SIZE];
	copy_32_from_encoded(&mut key, &encoded);
	Some(key)
}

fn untag_x25519_key(
	encoded: [u8; ENCODED_X25519_PUBLIC_KEY_SIZE],
) -> Option<[u8; X25519_PUBLIC_KEY_SIZE]> {
	if encoded[0] != KEM_TYPE_X25519 {
		return None;
	}
	let mut key = [0; X25519_PUBLIC_KEY_SIZE];
	copy_32_from_encoded(&mut key, &encoded);
	Some(key)
}

fn untag_mlkem768_key(
	encoded: [u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE],
) -> Option<[u8; MLKEM768_PUBLIC_KEY_SIZE]> {
	if encoded[0] != KEM_TYPE_MLKEM768 {
		return None;
	}
	let mut key = [0; MLKEM768_PUBLIC_KEY_SIZE];
	copy_mlkem768_from_encoded(&mut key, &encoded);
	Some(key)
}

fn is_all_zero(bytes: &[u8; DH_SECRET_SIZE]) -> bool {
	*bytes == [0; DH_SECRET_SIZE]
}

fn copy_32(output: &mut [u8; ROOT_KEY_INPUT_SIZE], offset: usize, input: &[u8; 32]) {
	let mut index = 0;
	while index < 32 {
		// hax does not infer a loop invariant from the `while` condition. Keep
		// the indexing obligations explicit so the generated F* remains total.
		if index >= 32 || offset > ROOT_KEY_INPUT_SIZE || index >= ROOT_KEY_INPUT_SIZE - offset {
			return;
		}
		output[offset + index] = input[index];
		index += 1;
	}
}

fn copy_associated_data(output: &mut [u8; ASSOCIATED_DATA_SIZE], offset: usize, input: &[u8]) {
	let mut index = 0;
	while index < input.len() {
		if index >= input.len()
			|| offset > ASSOCIATED_DATA_SIZE
			|| index >= ASSOCIATED_DATA_SIZE - offset
		{
			return;
		}
		output[offset + index] = input[index];
		index += 1;
	}
}

fn copy_32_to_encoded(
	output: &mut [u8; ENCODED_SIGN_PUBLIC_KEY_SIZE],
	input: &[u8; SIGN_PUBLIC_KEY_SIZE],
) {
	let mut index = 0;
	while index < SIGN_PUBLIC_KEY_SIZE {
		if index >= SIGN_PUBLIC_KEY_SIZE {
			return;
		}
		output[1 + index] = input[index];
		index += 1;
	}
}

fn copy_mlkem768_to_encoded(
	output: &mut [u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE],
	input: &[u8; MLKEM768_PUBLIC_KEY_SIZE],
) {
	let mut index = 0;
	while index < MLKEM768_PUBLIC_KEY_SIZE {
		if index >= MLKEM768_PUBLIC_KEY_SIZE {
			return;
		}
		output[1 + index] = input[index];
		index += 1;
	}
}

fn copy_32_from_encoded(
	output: &mut [u8; SIGN_PUBLIC_KEY_SIZE],
	input: &[u8; ENCODED_SIGN_PUBLIC_KEY_SIZE],
) {
	let mut index = 0;
	while index < SIGN_PUBLIC_KEY_SIZE {
		if index >= SIGN_PUBLIC_KEY_SIZE {
			return;
		}
		output[index] = input[1 + index];
		index += 1;
	}
}

fn copy_mlkem768_from_encoded(
	output: &mut [u8; MLKEM768_PUBLIC_KEY_SIZE],
	input: &[u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE],
) {
	let mut index = 0;
	while index < MLKEM768_PUBLIC_KEY_SIZE {
		if index >= MLKEM768_PUBLIC_KEY_SIZE {
			return;
		}
		output[index] = input[1 + index];
		index += 1;
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	fn shared_secrets() -> PqxdhSharedSecrets {
		PqxdhSharedSecrets {
			dh1: [0x11; DH_SECRET_SIZE],
			dh2: [0x22; DH_SECRET_SIZE],
			dh3: [0x33; DH_SECRET_SIZE],
			dh4: [0x44; DH_SECRET_SIZE],
			kem_shared_secret: [0x55; SHARED_SECRET_SIZE],
		}
	}

	fn init_message() -> InitKex {
		beacon_start(
			BeaconFresh::new(7),
			BeaconStartInputs {
				identity_public_key: [0x61; SIGN_PUBLIC_KEY_SIZE],
				prekey_public_key: [0x62; X25519_PUBLIC_KEY_SIZE],
				pq_public_key: [0x63; MLKEM768_PUBLIC_KEY_SIZE],
			},
			BeaconCoins {
				one_time_public_key: [0x64; X25519_PUBLIC_KEY_SIZE],
			},
		)
		.message
	}

	#[test]
	fn beacon_start_is_deterministic_and_tags_disjoint_key_types() {
		let message = init_message();
		assert_eq!(message.identity_key()[0], SIGN_TYPE_ED25519);
		assert_eq!(message.prekey()[0], KEM_TYPE_X25519);
		assert_eq!(message.one_time_key()[0], KEM_TYPE_X25519);
		assert_eq!(message.pq_key()[0], KEM_TYPE_MLKEM768);
		assert_eq!(message, init_message());
		assert!(validate_init_kex(message).is_ok());
	}

	#[test]
	fn wrong_registration_key_tag_is_rejected() {
		let message = init_message();
		let mut pq_key = *message.pq_key();
		pq_key[0] = KEM_TYPE_X25519;
		let wrong = InitKex::from_encoded(
			*message.identity_key(),
			*message.prekey(),
			*message.one_time_key(),
			pq_key,
		);
		assert_eq!(
			validate_init_kex(wrong),
			Err(RegistrationError::InvalidKeyEncoding)
		);
	}

	#[test]
	fn root_input_has_the_implemented_pqxdh_order() {
		let secrets = shared_secrets();
		let root = build_root_key_input(&secrets).unwrap();
		let bytes = root.as_bytes();
		assert_eq!(&bytes[..32], &[0xff; 32]);
		assert_eq!(&bytes[32..64], &[0x11; 32]);
		assert_eq!(&bytes[64..96], &[0x22; 32]);
		assert_eq!(&bytes[96..128], &[0x33; 32]);
		assert_eq!(&bytes[128..160], &[0x44; 32]);
		assert_eq!(&bytes[160..192], &[0x55; 32]);
	}

	#[test]
	fn every_zero_dh_output_is_rejected() {
		for selected in 0..4 {
			let mut secrets = shared_secrets();
			match selected {
				0 => secrets.dh1 = [0; DH_SECRET_SIZE],
				1 => secrets.dh2 = [0; DH_SECRET_SIZE],
				2 => secrets.dh3 = [0; DH_SECRET_SIZE],
				_ => secrets.dh4 = [0; DH_SECRET_SIZE],
			}
			assert!(matches!(
				build_root_key_input(&secrets),
				Err(RegistrationError::InvalidDhOutput)
			));
		}
	}

	#[test]
	fn associated_data_and_ratchet_directions_are_role_ordered() {
		let server_id = [0x71; SIGN_PUBLIC_KEY_SIZE];
		let beacon_id = [0x72; SIGN_PUBLIC_KEY_SIZE];
		let ad = build_associated_data(server_id, beacon_id);
		assert_eq!(ad[0], SIGN_TYPE_ED25519);
		assert_eq!(&ad[1..33], &server_id);
		assert_eq!(ad[33], SIGN_TYPE_ED25519);
		assert_eq!(&ad[34..66], &beacon_id);
		assert_eq!(&ad[66..112], PQXDH_INFO);
		assert_eq!(&ad[112..], SYM_RATCHET_INFO);

		assert_eq!(BEACON_RATCHETS.receive_offset(), 0);
		assert_eq!(BEACON_RATCHETS.send_offset(), 32);
		assert_eq!(SERVER_RATCHETS.receive_offset(), 32);
		assert_eq!(SERVER_RATCHETS.send_offset(), 0);
	}

	#[test]
	fn beacon_candidate_commits_or_aborts_explicitly() {
		let started = beacon_start(
			BeaconFresh::new(9),
			BeaconStartInputs {
				identity_public_key: [0x81; SIGN_PUBLIC_KEY_SIZE],
				prekey_public_key: [0x82; X25519_PUBLIC_KEY_SIZE],
				pq_public_key: [0x83; MLKEM768_PUBLIC_KEY_SIZE],
			},
			BeaconCoins {
				one_time_public_key: [0x84; X25519_PUBLIC_KEY_SIZE],
			},
		);
		let candidate = || {
			let inputs = BeaconFinishInputs {
				expected_server_identity: [0x91; SIGN_PUBLIC_KEY_SIZE],
				response_server_identity: [0x91; SIGN_PUBLIC_KEY_SIZE],
				assigned_key_id: 12,
				shared_secrets: shared_secrets(),
			};
			beacon_prepare_finish(started.state, &inputs).unwrap()
		};
		assert_eq!(beacon_commit(candidate()).assigned_key_id(), 12);
		assert_eq!(beacon_abort_candidate(candidate()).server_key_id(), 9);
	}

	#[test]
	fn server_candidate_does_not_commit_until_explicit_completion() {
		let verified = validate_init_kex(init_message()).unwrap();
		let state = ServerState::new(4);
		let secrets = shared_secrets();
		let (unchanged, pending) = server_accept(
			state,
			verified,
			ServerBinding {
				identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
				identity_key_id: 3,
			},
			ServerCoins {
				ephemeral_public_key: [0xa1; X25519_PUBLIC_KEY_SIZE],
				kem_ciphertext: [0xa2; MLKEM768_CIPHERTEXT_SIZE],
			},
			&secrets,
		)
		.unwrap();
		assert_eq!(unchanged, state);
		let (_, mismatched_pending) = server_accept(
			state,
			verified,
			ServerBinding {
				identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
				identity_key_id: 3,
			},
			ServerCoins {
				ephemeral_public_key: [0xa1; X25519_PUBLIC_KEY_SIZE],
				kem_ciphertext: [0xa2; MLKEM768_CIPHERTEXT_SIZE],
			},
			&secrets,
		)
		.unwrap();
		assert!(matches!(
			server_prepare_commit(
				state,
				mismatched_pending,
				ServerBinding {
					identity_public_key: [0xb3; SIGN_PUBLIC_KEY_SIZE],
					identity_key_id: 3,
				},
			),
			Err(RegistrationError::IdentityMismatch)
		));
		let candidate = server_prepare_commit(
			unchanged,
			pending,
			ServerBinding {
				identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
				identity_key_id: 3,
			},
		)
		.unwrap();
		assert_eq!(server_abort_candidate(&candidate), state);
		let (committed, peer) = server_commit(candidate);
		assert_eq!(committed.last_key_id(), 5);
		assert_eq!(peer.key_id, 5);
	}
}
