// SPDX-License-Identifier: 0BSD

//! Pure PQXDH composition and registration typestates.
//!
//! Cryptographic primitives, entropy acquisition, wire parsing, and storage
//! remain in the production adapter. This module owns the deterministic
//! buffers and state transitions that connect those operations.

pub const SIGN_PUBLIC_KEY_SIZE: usize = 32;
pub const X25519_PUBLIC_KEY_SIZE: usize = 32;
pub const MLKEM768_PUBLIC_KEY_SIZE: usize = 1_184;
pub const MLKEM768_CIPHERTEXT_SIZE: usize = 1_088;
pub const SHARED_SECRET_SIZE: usize = 32;
pub const DH_SECRET_SIZE: usize = 32;
pub const PQXDH_PADDING_SIZE: usize = 32;
pub const RATCHET_CHAIN_SIZE: usize = crate::ratchet::RATCHET_CHAIN_SIZE;
/// Number of bytes returned when the session root is expanded into both directional chains.
pub const INITIAL_RATCHET_KDF_OUTPUT_SIZE: usize = RATCHET_CHAIN_SIZE * 2;
const _: () = assert!(INITIAL_RATCHET_KDF_OUTPUT_SIZE == 64);
pub const REGISTRATION_KEY_ID_BINDING_SIZE: usize = 8;
pub const REGISTRATION_ID_SIZE: usize = SIGN_PUBLIC_KEY_SIZE + X25519_PUBLIC_KEY_SIZE;

pub const SIGN_TYPE_ED25519: u8 = 1;
pub const KEM_TYPE_MLKEM768: u8 = 3;
pub const KEM_TYPE_X25519: u8 = 4;

/// Key-role markers occupy the high half of the byte domain, while all
/// algorithm/type markers occupy the low half. This makes a type byte
/// impossible to reinterpret as a role byte.
pub const KEY_ROLE_PREKEY: u8 = 0x80;
pub const KEY_ROLE_ONE_TIME: u8 = 0x81;

pub const ENCODED_SIGN_PUBLIC_KEY_SIZE: usize = SIGN_PUBLIC_KEY_SIZE + 1;
pub const ENCODED_X25519_PUBLIC_KEY_SIZE: usize = X25519_PUBLIC_KEY_SIZE + 2;
pub const ENCODED_MLKEM768_PUBLIC_KEY_SIZE: usize = MLKEM768_PUBLIC_KEY_SIZE + 1;

// https://signal.org/docs/specifications/pqxdh/#pqxdh-parameters
pub const PQXDH_INFO: &[u8; 46] = b"BeaconcryptPqxdh_CURVE25519_SHA-512_ML-KEM-768";
pub const SYM_RATCHET_INFO_SIZE: usize = crate::ratchet::SYM_RATCHET_INFO_SIZE;
pub const SYM_RATCHET_INFO: &[u8; SYM_RATCHET_INFO_SIZE] = crate::ratchet::SYM_RATCHET_INFO;

pub const ROOT_KEY_INPUT_SIZE: usize =
	PQXDH_PADDING_SIZE + (4 * DH_SECRET_SIZE) + SHARED_SECRET_SIZE;
pub const ASSOCIATED_DATA_SIZE: usize =
	(2 * ENCODED_SIGN_PUBLIC_KEY_SIZE) + PQXDH_INFO.len() + SYM_RATCHET_INFO.len();

// The fixed ranges below are deliberately literal so hax exposes exact slice
// boundaries to F*. Keep those proof-visible bounds tied to the public sizes.
const _: () = assert!(SIGN_PUBLIC_KEY_SIZE == 32);
const _: () = assert!(X25519_PUBLIC_KEY_SIZE == 32);
const _: () = assert!(MLKEM768_PUBLIC_KEY_SIZE == 1_184);
const _: () = assert!(DH_SECRET_SIZE == 32);
const _: () = assert!(SHARED_SECRET_SIZE == 32);
const _: () = assert!(RATCHET_CHAIN_SIZE == 32);
const _: () = assert!(ROOT_KEY_INPUT_SIZE == 192);
const _: () = assert!(ASSOCIATED_DATA_SIZE == 153);
const _: () = assert!(REGISTRATION_KEY_ID_BINDING_SIZE == 8);
const _: () = assert!(REGISTRATION_ID_SIZE == 64);
const _: () = assert!(SIGN_TYPE_ED25519 < 0x80);
const _: () = assert!(KEM_TYPE_MLKEM768 < 0x80);
const _: () = assert!(KEM_TYPE_X25519 < 0x80);
const _: () = assert!(KEY_ROLE_PREKEY >= 0x80);
const _: () = assert!(KEY_ROLE_ONE_TIME >= 0x80);
const _: () = assert!(KEY_ROLE_PREKEY != KEY_ROLE_ONE_TIME);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RegistrationError {
	IdentityMismatch,
	InvalidKeyEncoding,
	InvalidDhOutput,
	RegistrationReplay,
	KeyIdMismatch,
	KeyIdExhausted,
	KeyIdCollision,
}

/// Stable expected or accepting server identity.
///
/// Keeping the public key and its numeric identifier in one proof-visible
/// value prevents adapters from changing either half of the trust anchor
/// independently during registration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ServerBinding {
	pub identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	pub identity_key_id: u64,
}

/// Public material generated by the beacon adapter before registration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconStartInputs {
	pub identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	pub prekey_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	pub pq_public_key: [u8; MLKEM768_PUBLIC_KEY_SIZE],
}

/// Per-registration randomness generated by the beacon adapter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconCoins {
	pub one_time_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
}

/// The deterministic, unsigned payloads of an InitKex message.
///
/// The adapter signs `prekey`, `one_time_key`, and `pq_key`, then places the
/// resulting signed buffers and `identity_key` into Cap'n Proto. The X25519
/// payloads are `[type, role, key]`; validation assigns meaning from the
/// authenticated role byte rather than from the wire field position alone.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct InitKex {
	identity_key: [u8; ENCODED_SIGN_PUBLIC_KEY_SIZE],
	prekey: [u8; ENCODED_X25519_PUBLIC_KEY_SIZE],
	one_time_key: [u8; ENCODED_X25519_PUBLIC_KEY_SIZE],
	pq_key: [u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE],
}

impl InitKex {
	pub const fn from_encoded(
		identity_key: [u8; ENCODED_SIGN_PUBLIC_KEY_SIZE],
		prekey: [u8; ENCODED_X25519_PUBLIC_KEY_SIZE],
		one_time_key: [u8; ENCODED_X25519_PUBLIC_KEY_SIZE],
		pq_key: [u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE],
	) -> Self {
		Self {
			identity_key,
			prekey,
			one_time_key,
			pq_key,
		}
	}

	pub const fn identity_key(&self) -> &[u8; ENCODED_SIGN_PUBLIC_KEY_SIZE] {
		&self.identity_key
	}

	pub const fn prekey(&self) -> &[u8; ENCODED_X25519_PUBLIC_KEY_SIZE] {
		&self.prekey
	}

	pub const fn one_time_key(&self) -> &[u8; ENCODED_X25519_PUBLIC_KEY_SIZE] {
		&self.one_time_key
	}

	pub const fn pq_key(&self) -> &[u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE] {
		&self.pq_key
	}
}

/// Signature-checked and type-checked InitKex public keys.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct VerifiedInitKex {
	beacon_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	beacon_prekey_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	beacon_one_time_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	beacon_pq_public_key: [u8; MLKEM768_PUBLIC_KEY_SIZE],
}

impl VerifiedInitKex {
	pub const fn beacon_identity_public_key(&self) -> &[u8; SIGN_PUBLIC_KEY_SIZE] {
		&self.beacon_identity_public_key
	}

	pub const fn beacon_prekey_public_key(&self) -> &[u8; X25519_PUBLIC_KEY_SIZE] {
		&self.beacon_prekey_public_key
	}

	pub const fn beacon_one_time_public_key(&self) -> &[u8; X25519_PUBLIC_KEY_SIZE] {
		&self.beacon_one_time_public_key
	}

	pub const fn beacon_pq_public_key(&self) -> &[u8; MLKEM768_PUBLIC_KEY_SIZE] {
		&self.beacon_pq_public_key
	}

	/// Stable, authenticated identifier for this one-time registration.
	///
	/// Exact equality is used by the adapter's consumed-registration set; no
	/// hash or collision-resistance assumption is needed.
	pub fn registration_id(&self) -> RegistrationId {
		let mut bytes = [0; REGISTRATION_ID_SIZE];
		bytes[..32].copy_from_slice(&self.beacon_identity_public_key);
		bytes[32..].copy_from_slice(&self.beacon_one_time_public_key);
		RegistrationId { bytes }
	}
}

/// Production abstraction used by the replay adapter and the ProVerif model.
///
/// The backend replacement below is deliberately limited to the exact
/// identity/one-time-key projection proved by the Stage 6 F* lemmas. It does
/// not replace the Rust implementation on ordinary builds.
#[cfg_attr(
	feature = "proverif",
	hax_lib::proverif::replace(
		"reduc forall identity: bitstring, prekey: bitstring, one_time: bitstring, pq: bitstring;\n  ${registration_id}(beaconcrypt_protocol_core__pqxdh__VerifiedInitKex(identity, prekey, one_time, pq)) = beaconcrypt_protocol_core__pqxdh__RegistrationId(registration_identifier(identity, one_time))."
	)
)]
pub fn registration_id(registration: &VerifiedInitKex) -> RegistrationId {
	registration.registration_id()
}

/// The signed beacon identity and one-time X25519 public key consumed by an
/// accepted `InitKex`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RegistrationId {
	bytes: [u8; REGISTRATION_ID_SIZE],
}

impl RegistrationId {
	pub const fn as_bytes(&self) -> &[u8; REGISTRATION_ID_SIZE] {
		&self.bytes
	}
}

/// Adapter-supplied result of looking up a registration ID in the persistent
/// consumed-registration set.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RegistrationStatus {
	Fresh,
	Consumed,
}

pub fn validate_registration_status(
	registration_status: RegistrationStatus,
) -> Result<(), RegistrationError> {
	if matches!(registration_status, RegistrationStatus::Consumed) {
		return Err(RegistrationError::RegistrationReplay);
	}
	Ok(())
}

/// Fresh beacon state. Calling [`beacon_start`] consumes this state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconFresh {
	expected_server_binding: ServerBinding,
}

impl BeaconFresh {
	pub const fn new(expected_server_binding: ServerBinding) -> Self {
		Self {
			expected_server_binding,
		}
	}

	pub const fn server_key_id(&self) -> u64 {
		self.expected_server_binding.identity_key_id
	}

	pub const fn expected_server_binding(&self) -> ServerBinding {
		self.expected_server_binding
	}
}

/// Beacon state tied to exactly one emitted InitKex.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconInitSent {
	expected_server_binding: ServerBinding,
	beacon_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
}

impl BeaconInitSent {
	pub const fn server_key_id(&self) -> u64 {
		self.expected_server_binding.identity_key_id
	}

	pub const fn expected_server_binding(&self) -> ServerBinding {
		self.expected_server_binding
	}
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconStart {
	pub state: BeaconInitSent,
	pub message: InitKex,
}

/// Construct the exact tagged InitKex payloads from explicit generated
/// material and advance the beacon to its single pending registration.
pub fn beacon_start(
	state: BeaconFresh,
	inputs: BeaconStartInputs,
	coins: BeaconCoins,
) -> BeaconStart {
	BeaconStart {
		state: BeaconInitSent {
			expected_server_binding: state.expected_server_binding,
			beacon_identity_public_key: inputs.identity_public_key,
		},
		message: InitKex {
			identity_key: tag_sign_key(inputs.identity_public_key),
			prekey: tag_x25519_key(KEY_ROLE_PREKEY, inputs.prekey_public_key),
			one_time_key: tag_x25519_key(KEY_ROLE_ONE_TIME, coins.one_time_public_key),
			pq_key: tag_mlkem768_key(inputs.pq_public_key),
		},
	}
}

/// Re-establish typed, verified registration keys after signature checks in
/// the adapter. Incorrect type tags or X25519 field roles are rejected here.
pub fn validate_init_kex(message: InitKex) -> Result<VerifiedInitKex, RegistrationError> {
	let Some(identity) = untag_sign_key(message.identity_key) else {
		return Err(RegistrationError::InvalidKeyEncoding);
	};
	let Some(prekey) = untag_x25519_key(message.prekey, KEY_ROLE_PREKEY) else {
		return Err(RegistrationError::InvalidKeyEncoding);
	};
	let Some(one_time) = untag_x25519_key(message.one_time_key, KEY_ROLE_ONE_TIME) else {
		return Err(RegistrationError::InvalidKeyEncoding);
	};
	let Some(pq) = untag_mlkem768_key(message.pq_key) else {
		return Err(RegistrationError::InvalidKeyEncoding);
	};

	Ok(VerifiedInitKex {
		beacon_identity_public_key: identity,
		beacon_prekey_public_key: prekey,
		beacon_one_time_public_key: one_time,
		beacon_pq_public_key: pq,
	})
}

/// Four classical DH results followed by the post-quantum KEM secret.
pub struct PqxdhSharedSecrets {
	pub dh1: [u8; DH_SECRET_SIZE],
	pub dh2: [u8; DH_SECRET_SIZE],
	pub dh3: [u8; DH_SECRET_SIZE],
	pub dh4: [u8; DH_SECRET_SIZE],
	pub kem_shared_secret: [u8; SHARED_SECRET_SIZE],
}

/// Exact `Padding || DH1 || DH2 || DH3 || DH4 || SS` input to the opaque
/// PQXDH HKDF operation.
pub struct RootKeyInput {
	bytes: [u8; ROOT_KEY_INPUT_SIZE],
}

impl RootKeyInput {
	pub const fn as_bytes(&self) -> &[u8; ROOT_KEY_INPUT_SIZE] {
		&self.bytes
	}

	/// Mutable access is reserved for the production adapter's zeroization of
	/// the concrete transcript immediately after the opaque HKDF call.
	pub fn as_mut_bytes(&mut self) -> &mut [u8; ROOT_KEY_INPUT_SIZE] {
		&mut self.bytes
	}
}

#[cfg_attr(
	feature = "proverif",
	hax_lib::proverif::replace(
		"reduc forall dh1: bitstring, dh2: bitstring, dh3: bitstring, dh4: bitstring, kem: bitstring;\n  ${build_root_key_input}(beaconcrypt_protocol_core__pqxdh__PqxdhSharedSecrets(dh1, dh2, dh3, dh4, kem)) = beaconcrypt_protocol_core__pqxdh__RootKeyInput(pqxdh_root_input(dh1, dh2, dh3, dh4, kem))."
	)
)]
pub fn build_root_key_input(
	secrets: &PqxdhSharedSecrets,
) -> Result<RootKeyInput, RegistrationError> {
	if is_all_zero(&secrets.dh1)
		|| is_all_zero(&secrets.dh2)
		|| is_all_zero(&secrets.dh3)
		|| is_all_zero(&secrets.dh4)
	{
		return Err(RegistrationError::InvalidDhOutput);
	}

	let mut bytes = [0xff; ROOT_KEY_INPUT_SIZE];
	bytes[32..64].copy_from_slice(&secrets.dh1);
	bytes[64..96].copy_from_slice(&secrets.dh2);
	bytes[96..128].copy_from_slice(&secrets.dh3);
	bytes[128..160].copy_from_slice(&secrets.dh4);
	bytes[160..192].copy_from_slice(&secrets.kem_shared_secret);
	Ok(RootKeyInput { bytes })
}

/// The core-owned direction plan for splitting the opaque 64-byte ratchet
/// KDF result. Offsets are bytes into `LHS || RHS`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RatchetInitialization {
	send_offset: u8,
	receive_offset: u8,
}

impl RatchetInitialization {
	pub const fn send_offset(&self) -> u8 {
		self.send_offset
	}

	pub const fn receive_offset(&self) -> u8 {
		self.receive_offset
	}
}

const BEACON_RATCHETS: RatchetInitialization = RatchetInitialization {
	send_offset: RATCHET_CHAIN_SIZE as u8,
	receive_offset: 0,
};
const SERVER_RATCHETS: RatchetInitialization = RatchetInitialization {
	send_offset: 0,
	receive_offset: RATCHET_CHAIN_SIZE as u8,
};

/// Test and adapter utility for non-handshake ratchet fixtures. Production
/// PQXDH code obtains the same plan from a beacon candidate typestate.
pub const fn beacon_ratchet_initialization() -> RatchetInitialization {
	BEACON_RATCHETS
}

/// Test and adapter utility for non-handshake ratchet fixtures. Production
/// PQXDH code obtains the same plan from a server candidate typestate.
pub const fn server_ratchet_initialization() -> RatchetInitialization {
	SERVER_RATCHETS
}

/// Role-ordered fixed-width initial send and receive chains.
pub struct InitialRatchetChains {
	send_chain: crate::ratchet::RatchetChain,
	receive_chain: crate::ratchet::RatchetChain,
}

/// Fixed-output executor for expanding one authenticated session root into
/// the two initial directional chain values.
pub type InitialRatchetKdfExecutor =
	fn(&crate::ratchet::SymmetricRatchetKdfRequest) -> [u8; INITIAL_RATCHET_KDF_OUTPUT_SIZE];

impl InitialRatchetChains {
	pub const fn send_chain(&self) -> &crate::ratchet::RatchetChain {
		&self.send_chain
	}

	pub const fn receive_chain(&self) -> &crate::ratchet::RatchetChain {
		&self.receive_chain
	}

	pub fn into_parts(self) -> (crate::ratchet::RatchetChain, crate::ratchet::RatchetChain) {
		(self.send_chain, self.receive_chain)
	}
}

/// Split an opaque 64-byte initial expansion into role-ordered fixed-width chains.
pub fn split_initial_ratchet_kdf_output(
	output: &[u8; INITIAL_RATCHET_KDF_OUTPUT_SIZE],
	initialization: RatchetInitialization,
) -> InitialRatchetChains {
	let mut left = [0u8; RATCHET_CHAIN_SIZE];
	left.copy_from_slice(&output[0..32]);
	let mut right = [0u8; RATCHET_CHAIN_SIZE];
	right.copy_from_slice(&output[32..64]);
	if initialization.send_offset == 0 {
		InitialRatchetChains {
			send_chain: crate::ratchet::RatchetChain::from_bytes(left),
			receive_chain: crate::ratchet::RatchetChain::from_bytes(right),
		}
	} else {
		InitialRatchetChains {
			send_chain: crate::ratchet::RatchetChain::from_bytes(right),
			receive_chain: crate::ratchet::RatchetChain::from_bytes(left),
		}
	}
}

/// Apply the sole opaque initial-chain primitive to the exact session root and order its output.
///
/// The primitive's complete production-facing type is `32-byte root -> 64-byte output`.
/// Label selection and HKDF details are private to that domain-specific primitive.
/// Input selection, output size, role ordering, partitioning, and fixed-width construction are owned here.
pub fn derive_initial_ratchet_chains(
	root: &[u8; RATCHET_CHAIN_SIZE],
	initialization: RatchetInitialization,
	kdf: InitialRatchetKdfExecutor,
) -> InitialRatchetChains {
	let request = crate::ratchet::SymmetricRatchetKdfRequest::new(*root);
	let output = kdf(&request);
	split_initial_ratchet_kdf_output(&output, initialization)
}

/// Construct a concrete kernel directly from one root, one fixed role plan,
/// and the executors for initial and subsequent core-owned KDF requests.
pub fn derive_initial_ratchet_kernel(
	root: &[u8; RATCHET_CHAIN_SIZE],
	initialization: RatchetInitialization,
	initial_kdf: InitialRatchetKdfExecutor,
	ratchet_kdf: crate::ratchet::RatchetKdfExecutor,
) -> crate::ratchet::ConcreteRatchetKernel {
	let chains = derive_initial_ratchet_chains(root, initialization, initial_kdf);
	let (send_chain, receive_chain) = chains.into_parts();
	crate::ratchet::ConcreteRatchetKernel::new(send_chain, receive_chain, ratchet_kdf)
}

/// Construct the beacon role's complementary concrete kernel.
pub fn derive_beacon_ratchet_kernel(
	root: &[u8; RATCHET_CHAIN_SIZE],
	initial_kdf: InitialRatchetKdfExecutor,
	ratchet_kdf: crate::ratchet::RatchetKdfExecutor,
) -> crate::ratchet::ConcreteRatchetKernel {
	derive_initial_ratchet_kernel(root, BEACON_RATCHETS, initial_kdf, ratchet_kdf)
}

/// Construct the server role's complementary concrete kernel.
pub fn derive_server_ratchet_kernel(
	root: &[u8; RATCHET_CHAIN_SIZE],
	initial_kdf: InitialRatchetKdfExecutor,
	ratchet_kdf: crate::ratchet::RatchetKdfExecutor,
) -> crate::ratchet::ConcreteRatchetKernel {
	derive_initial_ratchet_kernel(root, SERVER_RATCHETS, initial_kdf, ratchet_kdf)
}

/// Candidate beacon session. Its root, AD, identity assignment, and ratchet
/// direction have been validated, but its initial ciphertext has not yet
/// authenticated. It must be consumed by [`beacon_commit`] or
/// [`beacon_abort_candidate`].
pub struct BeaconRegistrationCandidate {
	server_binding: ServerBinding,
	assigned_key_id: u64,
	root_key_input: RootKeyInput,
	associated_data: [u8; ASSOCIATED_DATA_SIZE],
}

impl BeaconRegistrationCandidate {
	pub const fn server_key_id(&self) -> u64 {
		self.server_binding.identity_key_id
	}

	pub const fn server_binding(&self) -> ServerBinding {
		self.server_binding
	}

	pub const fn assigned_key_id(&self) -> u64 {
		self.assigned_key_id
	}

	pub const fn root_key_input(&self) -> &RootKeyInput {
		&self.root_key_input
	}

	pub fn root_key_input_mut(&mut self) -> &mut RootKeyInput {
		&mut self.root_key_input
	}

	pub const fn associated_data(&self) -> &[u8; ASSOCIATED_DATA_SIZE] {
		&self.associated_data
	}

	pub const fn ratchet_initialization(&self) -> RatchetInitialization {
		BEACON_RATCHETS
	}

	pub const fn key_id_binding(&self) -> RegistrationKeyIdBinding {
		registration_key_id_binding(self.assigned_key_id)
	}

	/// Bind the authenticated candidate's beacon direction directly to a
	/// concrete core ratchet kernel.
	pub fn derive_ratchet_kernel(
		&self,
		root: &[u8; RATCHET_CHAIN_SIZE],
		initial_kdf: InitialRatchetKdfExecutor,
		ratchet_kdf: crate::ratchet::RatchetKdfExecutor,
	) -> crate::ratchet::ConcreteRatchetKernel {
		derive_beacon_ratchet_kernel(root, initial_kdf, ratchet_kdf)
	}
}

pub struct BeaconFinishInputs {
	pub response_server_identity: [u8; SIGN_PUBLIC_KEY_SIZE],
	pub assigned_key_id: u64,
	pub shared_secrets: PqxdhSharedSecrets,
}

pub fn beacon_prepare_finish(
	state: BeaconInitSent,
	inputs: &BeaconFinishInputs,
) -> Result<BeaconRegistrationCandidate, RegistrationError> {
	if state.expected_server_binding.identity_public_key != inputs.response_server_identity {
		return Err(RegistrationError::IdentityMismatch);
	}
	let root_key_input = build_root_key_input(&inputs.shared_secrets)?;
	let associated_data = build_associated_data(
		state.expected_server_binding.identity_public_key,
		state.beacon_identity_public_key,
	);
	Ok(BeaconRegistrationCandidate {
		server_binding: state.expected_server_binding,
		assigned_key_id: inputs.assigned_key_id,
		root_key_input,
		associated_data,
	})
}

/// Fixed-width authenticated binding carried inside the encrypted initial
/// registration payload. The adapter strips it before returning application
/// plaintext.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RegistrationKeyIdBinding {
	bytes: [u8; REGISTRATION_KEY_ID_BINDING_SIZE],
}

impl RegistrationKeyIdBinding {
	pub const fn as_bytes(&self) -> &[u8; REGISTRATION_KEY_ID_BINDING_SIZE] {
		&self.bytes
	}
}

pub const fn registration_key_id_binding(key_id: u64) -> RegistrationKeyIdBinding {
	RegistrationKeyIdBinding {
		bytes: [
			key_id as u8,
			(key_id >> 8) as u8,
			(key_id >> 16) as u8,
			(key_id >> 24) as u8,
			(key_id >> 32) as u8,
			(key_id >> 40) as u8,
			(key_id >> 48) as u8,
			(key_id >> 56) as u8,
		],
	}
}

/// A beacon candidate whose assigned key ID matches the authenticated prefix
/// carried inside `appCipherText`.
pub struct AuthenticatedBeaconRegistration {
	candidate: BeaconRegistrationCandidate,
}

impl AuthenticatedBeaconRegistration {
	pub const fn server_binding(&self) -> ServerBinding {
		self.candidate.server_binding
	}

	pub const fn server_key_id(&self) -> u64 {
		self.candidate.server_binding.identity_key_id
	}

	pub const fn assigned_key_id(&self) -> u64 {
		self.candidate.assigned_key_id
	}
}

/// Check the authenticated sender ID and the assigned key-ID prefix returned
/// by the initial response open. Only the resulting typestate can be committed.
pub fn authenticate_registration_key_id_binding(
	candidate: BeaconRegistrationCandidate,
	authenticated_server_key_id: u64,
	authenticated_binding: [u8; REGISTRATION_KEY_ID_BINDING_SIZE],
) -> Result<AuthenticatedBeaconRegistration, RegistrationError> {
	if authenticated_server_key_id != candidate.server_binding.identity_key_id {
		return Err(RegistrationError::IdentityMismatch);
	}
	if authenticated_binding != candidate.key_id_binding().bytes {
		return Err(RegistrationError::KeyIdMismatch);
	}
	Ok(AuthenticatedBeaconRegistration { candidate })
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconEstablished {
	server_binding: ServerBinding,
	assigned_key_id: u64,
}

impl BeaconEstablished {
	pub const fn server_key_id(&self) -> u64 {
		self.server_binding.identity_key_id
	}

	pub const fn server_binding(&self) -> ServerBinding {
		self.server_binding
	}

	pub const fn assigned_key_id(&self) -> u64 {
		self.assigned_key_id
	}
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BeaconAborted {
	server_key_id: u64,
}

impl BeaconAborted {
	pub const fn new(server_key_id: u64) -> Self {
		Self { server_key_id }
	}

	pub const fn server_key_id(&self) -> u64 {
		self.server_key_id
	}
}

pub const fn beacon_commit(authenticated: AuthenticatedBeaconRegistration) -> BeaconEstablished {
	let candidate = authenticated.candidate;
	BeaconEstablished {
		server_binding: candidate.server_binding,
		assigned_key_id: candidate.assigned_key_id,
	}
}

pub const fn beacon_abort_candidate(candidate: BeaconRegistrationCandidate) -> BeaconAborted {
	BeaconAborted {
		server_key_id: candidate.server_binding.identity_key_id,
	}
}

pub const fn beacon_abort_init(state: BeaconInitSent) -> BeaconAborted {
	BeaconAborted {
		server_key_id: state.expected_server_binding.identity_key_id,
	}
}

pub const fn beacon_abort_fresh(state: BeaconFresh) -> BeaconAborted {
	BeaconAborted {
		server_key_id: state.expected_server_binding.identity_key_id,
	}
}

/// Active server state. Pending registrations do not mutate it.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ServerState {
	last_key_id: u64,
}

impl ServerState {
	pub const fn new(last_key_id: u64) -> Self {
		Self { last_key_id }
	}

	pub const fn last_key_id(&self) -> u64 {
		self.last_key_id
	}
}

/// Explicit ephemeral/KEM outputs generated by the server adapter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ServerCoins {
	pub ephemeral_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	pub kem_ciphertext: [u8; MLKEM768_CIPHERTEXT_SIZE],
}

/// Registration material that has passed parsing, signatures, key tags, DH
/// validation, and transcript construction but has not changed server state.
pub struct PendingServerRegistration {
	server_binding: ServerBinding,
	registration_id: RegistrationId,
	beacon_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	ephemeral_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	kem_ciphertext: [u8; MLKEM768_CIPHERTEXT_SIZE],
	root_key_input: RootKeyInput,
}

impl PendingServerRegistration {
	pub const fn registration_id(&self) -> RegistrationId {
		self.registration_id
	}

	pub const fn beacon_identity_public_key(&self) -> &[u8; SIGN_PUBLIC_KEY_SIZE] {
		&self.beacon_identity_public_key
	}

	pub const fn root_key_input(&self) -> &RootKeyInput {
		&self.root_key_input
	}

	pub fn root_key_input_mut(&mut self) -> &mut RootKeyInput {
		&mut self.root_key_input
	}
}

/// Accept a verified InitKex without committing any peer or counter state.
pub fn server_accept(
	state: ServerState,
	registration: VerifiedInitKex,
	registration_status: RegistrationStatus,
	server_binding: ServerBinding,
	coins: ServerCoins,
	shared_secrets: &PqxdhSharedSecrets,
) -> Result<(ServerState, PendingServerRegistration), RegistrationError> {
	validate_registration_status(registration_status)?;
	let root_key_input = build_root_key_input(shared_secrets)?;
	Ok((
		state,
		PendingServerRegistration {
			server_binding,
			registration_id: registration_id(&registration),
			beacon_identity_public_key: registration.beacon_identity_public_key,
			ephemeral_public_key: coins.ephemeral_public_key,
			kem_ciphertext: coins.kem_ciphertext,
			root_key_input,
		},
	))
}

/// Candidate server commit. The adapter must initialize a fresh ratchet,
/// encrypt the initial message, and serialize the response before consuming it
/// with [`server_commit`]. Dropping it leaves the active server unchanged.
pub struct ServerRegistrationCandidate {
	previous_state: ServerState,
	next_state: ServerState,
	key_id: u64,
	beacon_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	server_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	server_identity_key_id: u64,
	ephemeral_public_key: [u8; X25519_PUBLIC_KEY_SIZE],
	kem_ciphertext: [u8; MLKEM768_CIPHERTEXT_SIZE],
	associated_data: [u8; ASSOCIATED_DATA_SIZE],
}

impl ServerRegistrationCandidate {
	pub const fn key_id(&self) -> u64 {
		self.key_id
	}

	pub const fn beacon_identity_public_key(&self) -> &[u8; SIGN_PUBLIC_KEY_SIZE] {
		&self.beacon_identity_public_key
	}

	pub const fn server_identity_public_key(&self) -> &[u8; SIGN_PUBLIC_KEY_SIZE] {
		&self.server_identity_public_key
	}

	pub const fn server_identity_key_id(&self) -> u64 {
		self.server_identity_key_id
	}

	pub const fn ephemeral_public_key(&self) -> &[u8; X25519_PUBLIC_KEY_SIZE] {
		&self.ephemeral_public_key
	}

	pub const fn kem_ciphertext(&self) -> &[u8; MLKEM768_CIPHERTEXT_SIZE] {
		&self.kem_ciphertext
	}

	pub const fn associated_data(&self) -> &[u8; ASSOCIATED_DATA_SIZE] {
		&self.associated_data
	}

	pub const fn ratchet_initialization(&self) -> RatchetInitialization {
		SERVER_RATCHETS
	}

	pub const fn key_id_binding(&self) -> RegistrationKeyIdBinding {
		registration_key_id_binding(self.key_id)
	}

	/// Bind the accepted server candidate's direction directly to a concrete
	/// core ratchet kernel.
	pub fn derive_ratchet_kernel(
		&self,
		root: &[u8; RATCHET_CHAIN_SIZE],
		initial_kdf: InitialRatchetKdfExecutor,
		ratchet_kdf: crate::ratchet::RatchetKdfExecutor,
	) -> crate::ratchet::ConcreteRatchetKernel {
		derive_server_ratchet_kernel(root, initial_kdf, ratchet_kdf)
	}
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum KeyIdAvailability {
	Available,
	Occupied,
}

/// Return the next key ID without wrapping an exhausted counter.
pub const fn server_next_key_id(state: ServerState) -> Result<u64, RegistrationError> {
	if state.last_key_id == u64::MAX {
		Err(RegistrationError::KeyIdExhausted)
	} else {
		Ok(state.last_key_id + 1)
	}
}

/// Prepare the next checked, explicitly unoccupied server key ID.
pub fn server_prepare_commit(
	state: ServerState,
	pending: PendingServerRegistration,
	current_server_binding: ServerBinding,
	key_id_availability: KeyIdAvailability,
) -> Result<ServerRegistrationCandidate, RegistrationError> {
	if pending.server_binding.identity_key_id != current_server_binding.identity_key_id
		|| pending.server_binding.identity_public_key != current_server_binding.identity_public_key
	{
		return Err(RegistrationError::IdentityMismatch);
	}
	let key_id = server_next_key_id(state)?;
	if matches!(key_id_availability, KeyIdAvailability::Occupied) {
		return Err(RegistrationError::KeyIdCollision);
	}
	Ok(ServerRegistrationCandidate {
		previous_state: state,
		next_state: ServerState {
			last_key_id: key_id,
		},
		key_id,
		beacon_identity_public_key: pending.beacon_identity_public_key,
		server_identity_public_key: current_server_binding.identity_public_key,
		server_identity_key_id: current_server_binding.identity_key_id,
		ephemeral_public_key: pending.ephemeral_public_key,
		kem_ciphertext: pending.kem_ciphertext,
		associated_data: build_associated_data(
			current_server_binding.identity_public_key,
			pending.beacon_identity_public_key,
		),
	})
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EstablishedPeer {
	pub key_id: u64,
	pub identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	pub associated_data: [u8; ASSOCIATED_DATA_SIZE],
}

pub fn server_commit(candidate: ServerRegistrationCandidate) -> (ServerState, EstablishedPeer) {
	(
		candidate.next_state,
		EstablishedPeer {
			key_id: candidate.key_id,
			identity_public_key: candidate.beacon_identity_public_key,
			associated_data: candidate.associated_data,
		},
	)
}

pub const fn server_abort_candidate(candidate: &ServerRegistrationCandidate) -> ServerState {
	candidate.previous_state
}

/// Associated data is always encoded server identity first, beacon identity
/// second, then the key-exchange and ratchet domain-separation strings.
#[cfg_attr(
	feature = "proverif",
	hax_lib::proverif::replace(
		"fun ${build_associated_data}(bitstring, bitstring): bitstring [data]."
	)
)]
pub fn build_associated_data(
	server_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
	beacon_identity_public_key: [u8; SIGN_PUBLIC_KEY_SIZE],
) -> [u8; ASSOCIATED_DATA_SIZE] {
	let encoded_server = tag_sign_key(server_identity_public_key);
	let encoded_beacon = tag_sign_key(beacon_identity_public_key);
	let mut output = [0; ASSOCIATED_DATA_SIZE];
	output[..33].copy_from_slice(&encoded_server);
	output[33..66].copy_from_slice(&encoded_beacon);
	output[66..112].copy_from_slice(PQXDH_INFO);
	output[112..].copy_from_slice(SYM_RATCHET_INFO);
	output
}

fn tag_sign_key(key: [u8; SIGN_PUBLIC_KEY_SIZE]) -> [u8; ENCODED_SIGN_PUBLIC_KEY_SIZE] {
	let mut output = [0; ENCODED_SIGN_PUBLIC_KEY_SIZE];
	output[0] = SIGN_TYPE_ED25519;
	output[1..33].copy_from_slice(&key);
	output
}

fn tag_x25519_key(
	role: u8,
	key: [u8; X25519_PUBLIC_KEY_SIZE],
) -> [u8; ENCODED_X25519_PUBLIC_KEY_SIZE] {
	let mut output = [0; ENCODED_X25519_PUBLIC_KEY_SIZE];
	output[0] = KEM_TYPE_X25519;
	output[1] = role;
	output[2..34].copy_from_slice(&key);
	output
}

fn tag_mlkem768_key(key: [u8; MLKEM768_PUBLIC_KEY_SIZE]) -> [u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE] {
	let mut output = [0; ENCODED_MLKEM768_PUBLIC_KEY_SIZE];
	output[0] = KEM_TYPE_MLKEM768;
	output[1..1185].copy_from_slice(&key);
	output
}

fn untag_sign_key(
	encoded: [u8; ENCODED_SIGN_PUBLIC_KEY_SIZE],
) -> Option<[u8; SIGN_PUBLIC_KEY_SIZE]> {
	if encoded[0] != SIGN_TYPE_ED25519 {
		return None;
	}
	let mut key = [0; SIGN_PUBLIC_KEY_SIZE];
	key.copy_from_slice(&encoded[1..33]);
	Some(key)
}

fn untag_x25519_key(
	encoded: [u8; ENCODED_X25519_PUBLIC_KEY_SIZE],
	expected_role: u8,
) -> Option<[u8; X25519_PUBLIC_KEY_SIZE]> {
	if encoded[0] != KEM_TYPE_X25519 || encoded[1] != expected_role {
		return None;
	}
	let mut key = [0; X25519_PUBLIC_KEY_SIZE];
	key.copy_from_slice(&encoded[2..34]);
	Some(key)
}

fn untag_mlkem768_key(
	encoded: [u8; ENCODED_MLKEM768_PUBLIC_KEY_SIZE],
) -> Option<[u8; MLKEM768_PUBLIC_KEY_SIZE]> {
	if encoded[0] != KEM_TYPE_MLKEM768 {
		return None;
	}
	let mut key = [0; MLKEM768_PUBLIC_KEY_SIZE];
	key.copy_from_slice(&encoded[1..1185]);
	Some(key)
}

fn is_all_zero(bytes: &[u8; DH_SECRET_SIZE]) -> bool {
	*bytes == [0; DH_SECRET_SIZE]
}

#[cfg(test)]
mod tests {
	use super::*;

	fn shared_secrets() -> PqxdhSharedSecrets {
		PqxdhSharedSecrets {
			dh1: [0x11; DH_SECRET_SIZE],
			dh2: [0x22; DH_SECRET_SIZE],
			dh3: [0x33; DH_SECRET_SIZE],
			dh4: [0x44; DH_SECRET_SIZE],
			kem_shared_secret: [0x55; SHARED_SECRET_SIZE],
		}
	}

	const fn server_binding(identity_key_id: u64, identity_byte: u8) -> ServerBinding {
		ServerBinding {
			identity_public_key: [identity_byte; SIGN_PUBLIC_KEY_SIZE],
			identity_key_id,
		}
	}

	fn init_message() -> InitKex {
		beacon_start(
			BeaconFresh::new(server_binding(7, 0x70)),
			BeaconStartInputs {
				identity_public_key: [0x61; SIGN_PUBLIC_KEY_SIZE],
				prekey_public_key: [0x62; X25519_PUBLIC_KEY_SIZE],
				pq_public_key: [0x63; MLKEM768_PUBLIC_KEY_SIZE],
			},
			BeaconCoins {
				one_time_public_key: [0x64; X25519_PUBLIC_KEY_SIZE],
			},
		)
		.message
	}

	#[test]
	fn beacon_start_is_deterministic_and_tags_disjoint_key_types_and_roles() {
		let fresh = BeaconFresh::new(server_binding(7, 0x70));
		assert_eq!(fresh.server_key_id(), 7);
		let message = init_message();
		assert_eq!(message.identity_key()[0], SIGN_TYPE_ED25519);
		assert_eq!(message.prekey()[0], KEM_TYPE_X25519);
		assert_eq!(message.prekey()[1], KEY_ROLE_PREKEY);
		assert_eq!(message.one_time_key()[0], KEM_TYPE_X25519);
		assert_eq!(message.one_time_key()[1], KEY_ROLE_ONE_TIME);
		assert_eq!(message.pq_key()[0], KEM_TYPE_MLKEM768);
		assert_eq!(message, init_message());
		let verified = validate_init_kex(message).unwrap();
		let registration_id = verified.registration_id();
		assert_eq!(
			&registration_id.as_bytes()[..SIGN_PUBLIC_KEY_SIZE],
			&[0x61; SIGN_PUBLIC_KEY_SIZE]
		);
		assert_eq!(
			&registration_id.as_bytes()[SIGN_PUBLIC_KEY_SIZE..],
			&[0x64; X25519_PUBLIC_KEY_SIZE]
		);
	}

	#[test]
	fn tagged_key_round_trip_preserves_nonuniform_byte_order() {
		let identity_public_key = core::array::from_fn(|index| index as u8);
		let prekey_public_key = core::array::from_fn(|index| (index as u8).wrapping_add(0x20));
		let one_time_public_key = core::array::from_fn(|index| (index as u8).wrapping_add(0x40));
		let pq_public_key = core::array::from_fn(|index| (index as u8).wrapping_mul(17));
		let started = beacon_start(
			BeaconFresh::new(server_binding(7, 0x70)),
			BeaconStartInputs {
				identity_public_key,
				prekey_public_key,
				pq_public_key,
			},
			BeaconCoins {
				one_time_public_key,
			},
		);

		assert_eq!(&started.message.identity_key()[1..], &identity_public_key);
		assert_eq!(&started.message.prekey()[2..], &prekey_public_key);
		assert_eq!(&started.message.one_time_key()[2..], &one_time_public_key);
		assert_eq!(&started.message.pq_key()[1..], &pq_public_key);
		let verified = validate_init_kex(started.message).unwrap();
		assert_eq!(verified.beacon_identity_public_key(), &identity_public_key);
		assert_eq!(verified.beacon_prekey_public_key(), &prekey_public_key);
		assert_eq!(verified.beacon_one_time_public_key(), &one_time_public_key);
		assert_eq!(verified.beacon_pq_public_key(), &pq_public_key);
	}

	#[test]
	fn wrong_registration_key_tag_is_rejected() {
		let message = init_message();
		let mut pq_key = *message.pq_key();
		pq_key[0] = KEM_TYPE_X25519;
		let wrong = InitKex::from_encoded(
			*message.identity_key(),
			*message.prekey(),
			*message.one_time_key(),
			pq_key,
		);
		assert_eq!(
			validate_init_kex(wrong),
			Err(RegistrationError::InvalidKeyEncoding)
		);
	}

	#[test]
	fn swapped_or_duplicated_x25519_roles_are_rejected() {
		let message = init_message();
		let swapped = InitKex::from_encoded(
			*message.identity_key(),
			*message.one_time_key(),
			*message.prekey(),
			*message.pq_key(),
		);
		assert_eq!(
			validate_init_kex(swapped),
			Err(RegistrationError::InvalidKeyEncoding)
		);

		let duplicated = InitKex::from_encoded(
			*message.identity_key(),
			*message.prekey(),
			*message.prekey(),
			*message.pq_key(),
		);
		assert_eq!(
			validate_init_kex(duplicated),
			Err(RegistrationError::InvalidKeyEncoding)
		);
	}

	#[test]
	fn root_input_has_the_implemented_pqxdh_order() {
		let secrets = shared_secrets();
		let root = build_root_key_input(&secrets).unwrap();
		let bytes = root.as_bytes();
		assert_eq!(&bytes[..32], &[0xff; 32]);
		assert_eq!(&bytes[32..64], &[0x11; 32]);
		assert_eq!(&bytes[64..96], &[0x22; 32]);
		assert_eq!(&bytes[96..128], &[0x33; 32]);
		assert_eq!(&bytes[128..160], &[0x44; 32]);
		assert_eq!(&bytes[160..192], &[0x55; 32]);
	}

	#[test]
	fn every_zero_dh_output_is_rejected() {
		for selected in 0..4 {
			let mut secrets = shared_secrets();
			match selected {
				0 => secrets.dh1 = [0; DH_SECRET_SIZE],
				1 => secrets.dh2 = [0; DH_SECRET_SIZE],
				2 => secrets.dh3 = [0; DH_SECRET_SIZE],
				_ => secrets.dh4 = [0; DH_SECRET_SIZE],
			}
			assert!(matches!(
				build_root_key_input(&secrets),
				Err(RegistrationError::InvalidDhOutput)
			));
		}
	}

	#[test]
	fn associated_data_and_ratchet_directions_are_role_ordered() {
		let server_id = [0x71; SIGN_PUBLIC_KEY_SIZE];
		let beacon_id = [0x72; SIGN_PUBLIC_KEY_SIZE];
		let ad = build_associated_data(server_id, beacon_id);
		assert_eq!(ad[0], SIGN_TYPE_ED25519);
		assert_eq!(&ad[1..33], &server_id);
		assert_eq!(ad[33], SIGN_TYPE_ED25519);
		assert_eq!(&ad[34..66], &beacon_id);
		assert_eq!(&ad[66..112], PQXDH_INFO);
		assert_eq!(&ad[112..], SYM_RATCHET_INFO);

		assert_eq!(BEACON_RATCHETS.receive_offset(), 0);
		assert_eq!(BEACON_RATCHETS.send_offset(), 32);
		assert_eq!(SERVER_RATCHETS.receive_offset(), 32);
		assert_eq!(SERVER_RATCHETS.send_offset(), 0);
	}

	fn test_initial_ratchet_kdf(
		request: &crate::ratchet::SymmetricRatchetKdfRequest,
	) -> [u8; INITIAL_RATCHET_KDF_OUTPUT_SIZE] {
		assert_eq!(request.info(), SYM_RATCHET_INFO);
		let root = request.input();
		let mut output = [0u8; INITIAL_RATCHET_KDF_OUTPUT_SIZE];
		output[0..32].copy_from_slice(root);
		for index in 0..RATCHET_CHAIN_SIZE {
			output[32 + index] = root[index] ^ 0xff;
		}
		output
	}

	fn test_ratchet_kdf(
		request: &crate::ratchet::SymmetricRatchetKdfRequest,
	) -> [u8; crate::ratchet::RATCHET_KDF_OUTPUT_SIZE] {
		assert_eq!(request.info(), SYM_RATCHET_INFO);
		let input = request.input();
		let mut output = [0u8; crate::ratchet::RATCHET_KDF_OUTPUT_SIZE];
		for index in 0..RATCHET_CHAIN_SIZE {
			output[index] = input[index] ^ 0x5a;
			output[32 + index] = input[index].wrapping_add(1);
		}
		output[64..76].copy_from_slice(&input[0..12]);
		output
	}

	type CapturedMaterial = (u64, [u8; 32], [u8; 12]);

	fn capture_material(
		material: &crate::ratchet::RatchetMaterial,
		sequence: u64,
		_context: &(),
	) -> Option<CapturedMaterial> {
		Some((
			sequence,
			*material.key().as_bytes(),
			*material.nonce().as_bytes(),
		))
	}

	fn open_matching_material(
		material: &crate::ratchet::RatchetMaterial,
		sequence: u64,
		expected: &CapturedMaterial,
	) -> Option<()> {
		(sequence == expected.0
			&& material.key().as_bytes() == &expected.1
			&& material.nonce().as_bytes() == &expected.2)
			.then_some(())
	}

	#[test]
	fn initial_ratchet_boundary_passes_the_exact_root_and_orders_fixed_chains() {
		let root = core::array::from_fn::<_, RATCHET_CHAIN_SIZE, _>(|index| index as u8);
		let right = core::array::from_fn::<_, RATCHET_CHAIN_SIZE, _>(|index| root[index] ^ 0xff);
		let beacon = derive_initial_ratchet_chains(
			&root,
			beacon_ratchet_initialization(),
			test_initial_ratchet_kdf,
		);
		let server = derive_initial_ratchet_chains(
			&root,
			server_ratchet_initialization(),
			test_initial_ratchet_kdf,
		);

		assert_eq!(beacon.receive_chain().as_bytes(), &root);
		assert_eq!(beacon.send_chain().as_bytes(), &right);
		assert_eq!(server.receive_chain().as_bytes(), &right);
		assert_eq!(server.send_chain().as_bytes(), &root);
	}

	#[test]
	fn concrete_role_kernels_share_material_through_public_seal_and_open() {
		let root = core::array::from_fn::<_, RATCHET_CHAIN_SIZE, _>(|index| index as u8);
		let mut beacon =
			derive_beacon_ratchet_kernel(&root, test_initial_ratchet_kdf, test_ratchet_kdf);
		let mut server =
			derive_server_ratchet_kernel(&root, test_initial_ratchet_kdf, test_ratchet_kdf);

		assert_eq!(
			beacon.send_chain().as_bytes(),
			server.receive_chain().as_bytes()
		);
		assert_eq!(
			server.send_chain().as_bytes(),
			beacon.receive_chain().as_bytes()
		);

		for sequence in 1..=4 {
			let sent = crate::ratchet::concrete_seal_next(&mut beacon, &(), capture_material)
				.expect("beacon send should allocate concrete material");
			assert_eq!(sent.0, sequence);
			assert_eq!(
				crate::ratchet::concrete_open_and_finish(
					&mut server,
					sequence,
					&sent,
					open_matching_material,
				),
				Some(())
			);

			let reply = crate::ratchet::concrete_seal_next(&mut server, &(), capture_material)
				.expect("server send should allocate concrete material");
			assert_eq!(reply.0, sequence);
			assert_eq!(
				crate::ratchet::concrete_open_and_finish(
					&mut beacon,
					sequence,
					&reply,
					open_matching_material,
				),
				Some(())
			);
		}
	}

	#[test]
	fn registration_key_id_binding_is_exact_little_endian() {
		for key_id in [0, 1, 0x0102_0304_0506_0708, u32::MAX as u64, u64::MAX] {
			assert_eq!(
				registration_key_id_binding(key_id).as_bytes(),
				&key_id.to_le_bytes()
			);
		}
	}

	#[test]
	fn beacon_candidate_commits_or_aborts_explicitly() {
		let expected_server = server_binding(9, 0x91);
		let started = beacon_start(
			BeaconFresh::new(expected_server),
			BeaconStartInputs {
				identity_public_key: [0x81; SIGN_PUBLIC_KEY_SIZE],
				prekey_public_key: [0x82; X25519_PUBLIC_KEY_SIZE],
				pq_public_key: [0x83; MLKEM768_PUBLIC_KEY_SIZE],
			},
			BeaconCoins {
				one_time_public_key: [0x84; X25519_PUBLIC_KEY_SIZE],
			},
		);
		let candidate = || {
			let inputs = BeaconFinishInputs {
				response_server_identity: [0x91; SIGN_PUBLIC_KEY_SIZE],
				assigned_key_id: 12,
				shared_secrets: shared_secrets(),
			};
			beacon_prepare_finish(started.state, &inputs).unwrap()
		};
		assert_eq!(started.state.expected_server_binding(), expected_server);
		assert_eq!(started.state.server_key_id(), 9);
		assert_eq!(candidate().server_binding(), expected_server);
		assert_eq!(candidate().server_key_id(), 9);
		assert_eq!(candidate().assigned_key_id(), 12);
		for response_server_identity in [[0x90; SIGN_PUBLIC_KEY_SIZE], [0x92; SIGN_PUBLIC_KEY_SIZE]]
		{
			assert!(matches!(
				beacon_prepare_finish(
					started.state,
					&BeaconFinishInputs {
						response_server_identity,
						assigned_key_id: 12,
						shared_secrets: shared_secrets(),
					},
				),
				Err(RegistrationError::IdentityMismatch)
			));
		}
		let candidate_for_binding = candidate();
		assert_eq!(
			candidate_for_binding.key_id_binding().as_bytes(),
			&12u64.to_le_bytes()
		);
		assert!(
			authenticate_registration_key_id_binding(
				candidate_for_binding,
				expected_server.identity_key_id,
				12u64.to_le_bytes(),
			)
			.is_ok()
		);
		assert!(matches!(
			authenticate_registration_key_id_binding(
				candidate(),
				expected_server.identity_key_id,
				13u64.to_le_bytes(),
			),
			Err(RegistrationError::KeyIdMismatch)
		));
		assert!(matches!(
			authenticate_registration_key_id_binding(
				candidate(),
				expected_server.identity_key_id + 1,
				12u64.to_le_bytes(),
			),
			Err(RegistrationError::IdentityMismatch)
		));
		let authenticated = authenticate_registration_key_id_binding(
			candidate(),
			expected_server.identity_key_id,
			12u64.to_le_bytes(),
		)
		.unwrap();
		assert_eq!(authenticated.server_key_id(), 9);
		let established = beacon_commit(authenticated);
		assert_eq!(established.assigned_key_id(), 12);
		assert_eq!(established.server_key_id(), 9);
		assert_eq!(established.server_binding(), expected_server);
		assert_eq!(beacon_abort_candidate(candidate()).server_key_id(), 9);
	}

	#[test]
	fn server_candidate_does_not_commit_until_explicit_completion() {
		let verified = validate_init_kex(init_message()).unwrap();
		let state = ServerState::new(4);
		let secrets = shared_secrets();
		let (unchanged, pending) = server_accept(
			state,
			verified,
			RegistrationStatus::Fresh,
			ServerBinding {
				identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
				identity_key_id: 3,
			},
			ServerCoins {
				ephemeral_public_key: [0xa1; X25519_PUBLIC_KEY_SIZE],
				kem_ciphertext: [0xa2; MLKEM768_CIPHERTEXT_SIZE],
			},
			&secrets,
		)
		.unwrap();
		assert_eq!(unchanged, state);
		let (_, mismatched_pending) = server_accept(
			state,
			verified,
			RegistrationStatus::Fresh,
			ServerBinding {
				identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
				identity_key_id: 3,
			},
			ServerCoins {
				ephemeral_public_key: [0xa1; X25519_PUBLIC_KEY_SIZE],
				kem_ciphertext: [0xa2; MLKEM768_CIPHERTEXT_SIZE],
			},
			&secrets,
		)
		.unwrap();
		assert!(matches!(
			server_prepare_commit(
				state,
				mismatched_pending,
				ServerBinding {
					identity_public_key: [0xb3; SIGN_PUBLIC_KEY_SIZE],
					identity_key_id: 3,
				},
				KeyIdAvailability::Available,
			),
			Err(RegistrationError::IdentityMismatch)
		));
		let (_, mismatched_key_id_pending) = server_accept(
			state,
			verified,
			RegistrationStatus::Fresh,
			ServerBinding {
				identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
				identity_key_id: 3,
			},
			ServerCoins {
				ephemeral_public_key: [0xa1; X25519_PUBLIC_KEY_SIZE],
				kem_ciphertext: [0xa2; MLKEM768_CIPHERTEXT_SIZE],
			},
			&secrets,
		)
		.unwrap();
		assert!(matches!(
			server_prepare_commit(
				state,
				mismatched_key_id_pending,
				ServerBinding {
					identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
					identity_key_id: 4,
				},
				KeyIdAvailability::Available,
			),
			Err(RegistrationError::IdentityMismatch)
		));
		let candidate = server_prepare_commit(
			unchanged,
			pending,
			ServerBinding {
				identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
				identity_key_id: 3,
			},
			KeyIdAvailability::Available,
		)
		.unwrap();
		assert_eq!(candidate.key_id_binding().as_bytes(), &5u64.to_le_bytes());
		assert_eq!(server_abort_candidate(&candidate), state);
		let (committed, peer) = server_commit(candidate);
		assert_eq!(committed.last_key_id(), 5);
		assert_eq!(peer.key_id, 5);
	}

	#[test]
	fn server_rejects_consumed_registration_before_building_a_root() {
		let verified = validate_init_kex(init_message()).unwrap();
		let mut invalid_secrets = shared_secrets();
		invalid_secrets.dh1 = [0; DH_SECRET_SIZE];
		let result = server_accept(
			ServerState::new(4),
			verified,
			RegistrationStatus::Consumed,
			ServerBinding {
				identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
				identity_key_id: 3,
			},
			ServerCoins {
				ephemeral_public_key: [0xa1; X25519_PUBLIC_KEY_SIZE],
				kem_ciphertext: [0xa2; MLKEM768_CIPHERTEXT_SIZE],
			},
			&invalid_secrets,
		);

		assert!(matches!(result, Err(RegistrationError::RegistrationReplay)));
	}

	#[test]
	fn server_key_id_allocation_is_checked_and_collision_safe() {
		assert_eq!(server_next_key_id(ServerState::new(4)), Ok(5));
		assert_eq!(
			server_next_key_id(ServerState::new(u64::MAX)),
			Err(RegistrationError::KeyIdExhausted)
		);

		let verified = validate_init_kex(init_message()).unwrap();
		let (_, pending) = server_accept(
			ServerState::new(4),
			verified,
			RegistrationStatus::Fresh,
			ServerBinding {
				identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
				identity_key_id: 3,
			},
			ServerCoins {
				ephemeral_public_key: [0xa1; X25519_PUBLIC_KEY_SIZE],
				kem_ciphertext: [0xa2; MLKEM768_CIPHERTEXT_SIZE],
			},
			&shared_secrets(),
		)
		.unwrap();
		assert!(matches!(
			server_prepare_commit(
				ServerState::new(4),
				pending,
				ServerBinding {
					identity_public_key: [0xa3; SIGN_PUBLIC_KEY_SIZE],
					identity_key_id: 3,
				},
				KeyIdAvailability::Occupied,
			),
			Err(RegistrationError::KeyIdCollision)
		));
	}
}
